-- Migration 0024: Admin master disease tree i18n keys

INSERT OR IGNORE INTO i18n_translations (
  id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at
) VALUES
  ('i24-admin-master-001', 'admin.master.error_category_not_found', 'admin', '카테고리를 찾을 수 없습니다.', 'Category not found.', 'カテゴリが見つかりません。', '找不到分类。', '找不到分類。', 'No se encontró la categoría.', 'Catégorie introuvable.', 'Kategorie nicht gefunden.', 'Categoria não encontrada.', 'Không tìm thấy danh mục.', 'ไม่พบหมวดหมู่', 'Kategori tidak ditemukan.', 'تعذر العثور على الفئة.', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-002', 'admin.master.disease_nav_title', 'admin', '질병/식단/알러지 빠른 이동', 'Quick Navigation: Disease/Diet/Allergy', '疾患・食事・アレルギー クイック移動', '疾病/饮食/过敏 快速导航', '疾病/飲食/過敏 快速導覽', 'Navegación rápida: Enfermedad/Dieta/Alergia', 'Navigation rapide : Maladie/Régime/Allergie', 'Schnellnavigation: Krankheit/Ernährung/Allergie', 'Navegação rápida: Doença/Dieta/Alergia', 'Điều hướng nhanh: Bệnh/Chế độ ăn/Dị ứng', 'ทางลัด: โรค/อาหาร/ภูมิแพ้', 'Navigasi cepat: Penyakit/Diet/Alergi', 'تنقل سريع: المرض/النظام الغذائي/الحساسية', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-003', 'admin.master.nav_disease_group', 'admin', '질병군', 'Disease Group', '疾患群', '疾病组', '疾病群組', 'Grupo de enfermedad', 'Groupe de maladies', 'Krankheitsgruppe', 'Grupo de doença', 'Nhóm bệnh', 'กลุ่มโรค', 'Kelompok penyakit', 'مجموعة الأمراض', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-004', 'admin.master.nav_disease_type', 'admin', '질병', 'Disease', '疾患', '疾病', '疾病', 'Enfermedad', 'Maladie', 'Krankheit', 'Doença', 'Bệnh', 'โรค', 'Penyakit', 'مرض', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-005', 'admin.master.nav_disease_device_type', 'admin', '질병 장치', 'Disease Device', '疾患デバイス', '疾病设备', '疾病裝置', 'Dispositivo de enfermedad', 'Appareil de maladie', 'Krankheitsgerät', 'Dispositivo de doença', 'Thiết bị bệnh', 'อุปกรณ์โรค', 'Perangkat penyakit', 'جهاز المرض', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-006', 'admin.master.nav_disease_measurement_type', 'admin', '측정 항목', 'Measurement Type', '測定項目', '测量项', '測量項目', 'Tipo de medición', 'Type de mesure', 'Messtyp', 'Tipo de medição', 'Loại đo', 'ประเภทการวัด', 'Jenis pengukuran', 'نوع القياس', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-007', 'admin.master.nav_disease_measurement_context', 'admin', '측정 컨텍스트', 'Measurement Context', '測定コンテキスト', '测量上下文', '測量情境', 'Contexto de medición', 'Contexte de mesure', 'Messkontext', 'Contexto de medição', 'Ngữ cảnh đo', 'บริบทการวัด', 'Konteks pengukuran', 'سياق القياس', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-008', 'admin.master.nav_diet_type', 'admin', '식단 상위', 'Diet Type', '食事タイプ', '饮食类型', '飲食類型', 'Tipo de dieta', 'Type de régime', 'Ernährungstyp', 'Tipo de dieta', 'Loại chế độ ăn', 'ประเภทอาหาร', 'Jenis diet', 'نوع النظام الغذائي', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-009', 'admin.master.nav_diet_subtype', 'admin', '식단 하위', 'Diet Subtype', '食事サブタイプ', '饮食子类型', '飲食子類型', 'Subtipo de dieta', 'Sous-type de régime', 'Ernährungsuntertyp', 'Subtipo de dieta', 'Loại phụ chế độ ăn', 'ประเภทย่อยอาหาร', 'Subtipe diet', 'نوع فرعي للنظام الغذائي', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-010', 'admin.master.nav_allergy_group', 'admin', '알러지 그룹', 'Allergy Group', 'アレルギー群', '过敏组', '過敏群組', 'Grupo de alergia', 'Groupe d''allergies', 'Allergiegruppe', 'Grupo de alergia', 'Nhóm dị ứng', 'กลุ่มภูมิแพ้', 'Kelompok alergi', 'مجموعة الحساسية', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-011', 'admin.master.nav_allergy_type', 'admin', '알러지 타입', 'Allergy Type', 'アレルギータイプ', '过敏类型', '過敏類型', 'Tipo de alergia', 'Type d''allergie', 'Allergietyp', 'Tipo de alergia', 'Loại dị ứng', 'ประเภทภูมิแพ้', 'Tipe alergi', 'نوع الحساسية', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-012', 'admin.master.disease_nav_desc_prefix', 'admin', '질병 장치 등록은', 'To register a disease device, use', '疾患デバイス登録は', '要注册疾病设备，请使用', '若要註冊疾病裝置，請使用', 'Para registrar un dispositivo de enfermedad, use', 'Pour enregistrer un appareil de maladie, utilisez', 'Für die Registrierung eines Krankheitsgeräts verwenden Sie', 'Para registrar um dispositivo de doença, use', 'Để đăng ký thiết bị bệnh, hãy dùng', 'การลงทะเบียนอุปกรณ์โรค ให้ใช้', 'Untuk mendaftarkan perangkat penyakit, gunakan', 'لتسجيل جهاز مرض، استخدم', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-013', 'admin.master.disease_nav_desc_middle', 'admin', '에서 아이템 추가 시', ' and add an item there with', 'でアイテム追加時に', '并在该分类添加条目时将', '並在該分類新增項目時將', ' y al agregar un ítem allí con', ' et lors de l''ajout d''un élément avec', ' und fügen Sie dort ein Element hinzu mit', ' e ao adicionar item ali com', ' và khi thêm mục tại đó với', ' และเมื่อเพิ่มรายการในนั้นโดยตั้งค่า', ' dan saat menambah item di sana dengan', ' وعند إضافة عنصر هناك مع تعيين', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-014', 'admin.master.disease_nav_desc_suffix', 'admin', '= 질병(disease_type)으로 지정하면 됩니다.', ' to Disease (disease_type).', 'を疾患(disease_type)に設定してください。', '父项设为疾病(disease_type)即可。', '父項設為疾病(disease_type)即可。', ' padre como Enfermedad (disease_type).', ' parent sur Maladie (disease_type).', ' als Elternwert auf Krankheit (disease_type).', ' o pai para Doença (disease_type).', ' mục cha là Bệnh (disease_type).', ' ค่า parent เป็น Disease (disease_type)', ' parent ke Disease (disease_type).', ' العنصر الأب على Disease (disease_type).', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-015', 'admin.master.disease_tree_title', 'admin', '질병군 > 질병 > 장치 트리', 'Disease Group > Disease > Device Tree', '疾患群 > 疾患 > デバイス ツリー', '疾病组 > 疾病 > 设备树', '疾病群組 > 疾病 > 裝置樹', 'Árbol Grupo de enfermedad > Enfermedad > Dispositivo', 'Arbre Groupe de maladies > Maladie > Appareil', 'Baum Krankheitsgruppe > Krankheit > Gerät', 'Árvore Grupo de doença > Doença > Dispositivo', 'Cây Nhóm bệnh > Bệnh > Thiết bị', 'ผัง กลุ่มโรค > โรค > อุปกรณ์', 'Pohon Kelompok penyakit > Penyakit > Perangkat', 'شجرة مجموعة المرض > المرض > الجهاز', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-016', 'admin.master.tree_add_group', 'admin', '+ 질병군', '+ Disease Group', '+ 疾患群', '+ 疾病组', '+ 疾病群組', '+ Grupo de enfermedad', '+ Groupe de maladies', '+ Krankheitsgruppe', '+ Grupo de doença', '+ Nhóm bệnh', '+ กลุ่มโรค', '+ Kelompok penyakit', '+ مجموعة أمراض', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-017', 'admin.master.tree_loading', 'admin', '데이터를 불러오는 중입니다...', 'Loading data...', 'データを読み込み中です...', '正在加载数据...', '正在載入資料...', 'Cargando datos...', 'Chargement des données...', 'Daten werden geladen...', 'Carregando dados...', 'Đang tải dữ liệu...', 'กำลังโหลดข้อมูล...', 'Memuat data...', 'جارٍ تحميل البيانات...', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-018', 'admin.master.tree_no_group', 'admin', '질병군 데이터가 없습니다.', 'No disease group data.', '疾患群データがありません。', '没有疾病组数据。', '沒有疾病群組資料。', 'No hay datos de grupos de enfermedad.', 'Aucune donnée de groupe de maladies.', 'Keine Krankheitsgruppendaten.', 'Sem dados de grupo de doença.', 'Không có dữ liệu nhóm bệnh.', 'ไม่มีข้อมูลกลุ่มโรค', 'Tidak ada data kelompok penyakit.', 'لا توجد بيانات مجموعة أمراض.', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-019', 'admin.master.tree_add_disease', 'admin', '+ 질병', '+ Disease', '+ 疾患', '+ 疾病', '+ 疾病', '+ Enfermedad', '+ Maladie', '+ Krankheit', '+ Doença', '+ Bệnh', '+ โรค', '+ Penyakit', '+ مرض', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-020', 'admin.master.tree_no_disease', 'admin', '등록된 질병이 없습니다.', 'No registered disease.', '登録された疾患がありません。', '没有已注册疾病。', '沒有已註冊疾病。', 'No hay enfermedades registradas.', 'Aucune maladie enregistrée.', 'Keine registrierte Krankheit.', 'Sem doença registrada.', 'Không có bệnh đã đăng ký.', 'ไม่มีโรคที่ลงทะเบียน', 'Tidak ada penyakit terdaftar.', 'لا توجد أمراض مسجلة.', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-021', 'admin.master.tree_add_device', 'admin', '+ 장치', '+ Device', '+ デバイス', '+ 设备', '+ 裝置', '+ Dispositivo', '+ Appareil', '+ Gerät', '+ Dispositivo', '+ Thiết bị', '+ อุปกรณ์', '+ Perangkat', '+ جهاز', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-022', 'admin.master.tree_no_device', 'admin', '등록된 장치가 없습니다.', 'No registered device.', '登録されたデバイスがありません。', '没有已注册设备。', '沒有已註冊裝置。', 'No hay dispositivos registrados.', 'Aucun appareil enregistré.', 'Kein registriertes Gerät.', 'Sem dispositivo registrado.', 'Không có thiết bị đã đăng ký.', 'ไม่มีอุปกรณ์ที่ลงทะเบียน', 'Tidak ada perangkat terdaftar.', 'لا توجد أجهزة مسجلة.', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-023', 'admin.common.refresh', 'admin', '새로고침', 'Refresh', '更新', '刷新', '重新整理', 'Actualizar', 'Rafraîchir', 'Aktualisieren', 'Atualizar', 'Làm mới', 'รีเฟรช', 'Segarkan', 'تحديث', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-024', 'admin.common.open', 'admin', '열기', 'Open', '開く', '打开', '打開', 'Abrir', 'Ouvrir', 'Öffnen', 'Abrir', 'Mở', 'เปิด', 'Buka', 'فتح', 1, datetime('now'), datetime('now')),
  ('i24-admin-master-025', 'admin.common.loading', 'admin', '로딩...', 'Loading...', '読み込み中...', '加载中...', '載入中...', 'Cargando...', 'Chargement...', 'Laden...', 'Carregando...', 'Đang tải...', 'กำลังโหลด...', 'Memuat...', 'جارٍ التحميل...', 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO schema_migrations (version) VALUES ('0024_admin_master_disease_tree_i18n');
