-- Migration 0026: Guardian gallery upload modal i18n keys

INSERT OR IGNORE INTO i18n_translations (
  id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at
) VALUES
  ('i26-gallery-001', 'guardian.pet.gallery.add_photo.open', 'guardian', '사진 추가', 'Add Photo', '写真を追加', '添加照片', '新增照片', 'Agregar foto', 'Ajouter une photo', 'Foto hinzufügen', 'Adicionar foto', 'Thêm ảnh', 'เพิ่มรูปภาพ', 'Tambah foto', 'إضافة صورة', 1, datetime('now'), datetime('now')),
  ('i26-gallery-002', 'guardian.pet.gallery.add_photo.title', 'guardian', '사진 추가', 'Add Photo', '写真を追加', '添加照片', '新增照片', 'Agregar foto', 'Ajouter une photo', 'Foto hinzufügen', 'Adicionar foto', 'Thêm ảnh', 'เพิ่มรูปภาพ', 'Tambah foto', 'إضافة صورة', 1, datetime('now'), datetime('now')),
  ('i26-gallery-003', 'guardian.pet.gallery.add_photo.file', 'guardian', '사진 업로드', 'Upload Photo', '写真アップロード', '上传照片', '上傳照片', 'Subir foto', 'Téléverser une photo', 'Foto hochladen', 'Enviar foto', 'Tải ảnh lên', 'อัปโหลดรูปภาพ', 'Unggah foto', 'تحميل صورة', 1, datetime('now'), datetime('now')),
  ('i26-gallery-004', 'guardian.pet.gallery.add_photo.file_hint', 'guardian', '파일을 선택하거나 여기로 드래그하세요 (JPG/PNG/WEBP, 최대 10MB)', 'Select a file or drag it here (JPG/PNG/WEBP, max 10MB)', 'ファイルを選択するか、ここにドラッグしてください (JPG/PNG/WEBP、最大10MB)', '选择文件或拖放到此处（JPG/PNG/WEBP，最大10MB）', '選擇檔案或拖曳到此處（JPG/PNG/WEBP，最大10MB）', 'Selecciona un archivo o arrástralo aquí (JPG/PNG/WEBP, máx 10MB)', 'Sélectionnez un fichier ou glissez-le ici (JPG/PNG/WEBP, max 10 Mo)', 'Datei auswählen oder hierher ziehen (JPG/PNG/WEBP, max. 10 MB)', 'Selecione um arquivo ou arraste para cá (JPG/PNG/WEBP, máx. 10MB)', 'Chọn tệp hoặc kéo vào đây (JPG/PNG/WEBP, tối đa 10MB)', 'เลือกไฟล์หรือลากมาที่นี่ (JPG/PNG/WEBP สูงสุด 10MB)', 'Pilih file atau tarik ke sini (JPG/PNG/WEBP, maks 10MB)', 'اختر ملفًا أو اسحبه هنا (JPG/PNG/WEBP، الحد الأقصى 10MB)', 1, datetime('now'), datetime('now')),
  ('i26-gallery-005', 'guardian.pet.gallery.add_photo.select_file', 'guardian', '파일 선택', 'Select File', 'ファイルを選択', '选择文件', '選擇檔案', 'Seleccionar archivo', 'Sélectionner un fichier', 'Datei auswählen', 'Selecionar arquivo', 'Chọn tệp', 'เลือกไฟล์', 'Pilih file', 'اختيار ملف', 1, datetime('now'), datetime('now')),
  ('i26-gallery-006', 'guardian.pet.gallery.add_photo.preview', 'guardian', '미리보기', 'Preview', 'プレビュー', '预览', '預覽', 'Vista previa', 'Aperçu', 'Vorschau', 'Pré-visualização', 'Xem trước', 'ตัวอย่าง', 'Pratinjau', 'معاينة', 1, datetime('now'), datetime('now')),
  ('i26-gallery-007', 'guardian.pet.gallery.add_photo.preview_alt', 'guardian', '업로드 미리보기', 'Upload preview', 'アップロードプレビュー', '上传预览', '上傳預覽', 'Vista previa de carga', 'Aperçu du téléversement', 'Upload-Vorschau', 'Pré-visualização do upload', 'Xem trước khi tải lên', 'ตัวอย่างการอัปโหลด', 'Pratinjau unggahan', 'معاينة الرفع', 1, datetime('now'), datetime('now')),
  ('i26-gallery-008', 'guardian.pet.gallery.add_photo.reselect', 'guardian', '다시 선택', 'Choose Again', '再選択', '重新选择', '重新選擇', 'Elegir de nuevo', 'Choisir à nouveau', 'Erneut auswählen', 'Escolher novamente', 'Chọn lại', 'เลือกใหม่', 'Pilih ulang', 'اختر مرة أخرى', 1, datetime('now'), datetime('now')),
  ('i26-gallery-009', 'guardian.pet.gallery.add_photo.uploading', 'guardian', '업로드 중', 'Uploading', 'アップロード中', '上传中', '上傳中', 'Subiendo', 'Téléversement', 'Wird hochgeladen', 'Enviando', 'Đang tải lên', 'กำลังอัปโหลด', 'Mengunggah', 'جارٍ الرفع', 1, datetime('now'), datetime('now')),
  ('i26-gallery-010', 'guardian.pet.gallery.add_photo.upload_type', 'guardian', '업로드 유형', 'Upload Type', 'アップロード種別', '上传类型', '上傳類型', 'Tipo de carga', 'Type de téléversement', 'Upload-Typ', 'Tipo de envio', 'Loại tải lên', 'ประเภทการอัปโหลด', 'Jenis unggahan', 'نوع الرفع', 1, datetime('now'), datetime('now')),
  ('i26-gallery-011', 'guardian.pet.gallery.add_photo.type.manual_upload', 'guardian', '일반 앨범', 'General Album', '一般アルバム', '普通相册', '一般相簿', 'Álbum general', 'Album général', 'Allgemeines Album', 'Álbum geral', 'Album chung', 'อัลบั้มทั่วไป', 'Album umum', 'ألبوم عام', 1, datetime('now'), datetime('now')),
  ('i26-gallery-012', 'guardian.pet.gallery.add_photo.type.feed', 'guardian', '피드 연결', 'Feed Linked', 'フィード連携', '关联动态', '關聯動態', 'Vincular feed', 'Lier au fil', 'Mit Feed verknüpfen', 'Vincular ao feed', 'Liên kết feed', 'เชื่อมกับฟีด', 'Tautkan ke feed', 'ربط بالمنشور', 1, datetime('now'), datetime('now')),
  ('i26-gallery-013', 'guardian.pet.gallery.add_photo.type.booking_completed', 'guardian', '예약 완료 사진', 'Booking Completion', '予約完了写真', '预约完成照片', '預約完成照片', 'Foto de reserva completada', 'Photo de réservation terminée', 'Foto nach Buchungsabschluss', 'Foto de conclusão da reserva', 'Ảnh hoàn tất đặt lịch', 'รูปภาพการจองเสร็จสิ้น', 'Foto penyelesaian booking', 'صورة إتمام الحجز', 1, datetime('now'), datetime('now')),
  ('i26-gallery-014', 'guardian.pet.gallery.add_photo.type.health_record', 'guardian', '건강 기록 연결', 'Health Record Linked', '健康記録連携', '关联健康记录', '關聯健康紀錄', 'Vincular registro de salud', 'Lier au dossier santé', 'Mit Gesundheitsdaten verknüpfen', 'Vincular ao registro de saúde', 'Liên kết hồ sơ sức khỏe', 'เชื่อมกับบันทึกสุขภาพ', 'Tautkan catatan kesehatan', 'ربط بالسجل الصحي', 1, datetime('now'), datetime('now')),
  ('i26-gallery-015', 'guardian.pet.gallery.add_photo.type.profile', 'guardian', '프로필 사진으로 설정', 'Set as Profile Photo', 'プロフィール写真に設定', '设为头像', '設為頭像', 'Establecer como foto de perfil', 'Définir comme photo de profil', 'Als Profilfoto festlegen', 'Definir como foto de perfil', 'Đặt làm ảnh hồ sơ', 'ตั้งเป็นรูปโปรไฟล์', 'Jadikan foto profil', 'تعيين كصورة ملف شخصي', 1, datetime('now'), datetime('now')),
  ('i26-gallery-016', 'guardian.pet.gallery.add_photo.visibility', 'guardian', '공개 범위', 'Visibility', '公開範囲', '可见范围', '可見範圍', 'Visibilidad', 'Visibilité', 'Sichtbarkeit', 'Visibilidade', 'Phạm vi hiển thị', 'การมองเห็น', 'Visibilitas', 'نطاق الظهور', 1, datetime('now'), datetime('now')),
  ('i26-gallery-017', 'guardian.pet.gallery.add_photo.caption', 'guardian', '캡션', 'Caption', 'キャプション', '说明', '說明', 'Descripción', 'Légende', 'Bildunterschrift', 'Legenda', 'Chú thích', 'คำบรรยาย', 'Keterangan', 'تعليق', 1, datetime('now'), datetime('now')),
  ('i26-gallery-018', 'guardian.pet.gallery.add_photo.tags', 'guardian', '태그', 'Tags', 'タグ', '标签', '標籤', 'Etiquetas', 'Tags', 'Tags', 'Tags', 'Thẻ', 'แท็ก', 'Tag', 'الوسوم', 1, datetime('now'), datetime('now')),
  ('i26-gallery-019', 'guardian.pet.gallery.add_photo.tags_placeholder', 'guardian', 'cute, spring', 'cute, spring', 'cute, spring', 'cute, spring', 'cute, spring', 'cute, spring', 'cute, spring', 'cute, spring', 'cute, spring', 'cute, spring', 'cute, spring', 'cute, spring', 'cute, spring', 1, datetime('now'), datetime('now')),
  ('i26-gallery-020', 'guardian.pet.gallery.add_photo.cancel', 'guardian', '취소', 'Cancel', 'キャンセル', '取消', '取消', 'Cancelar', 'Annuler', 'Abbrechen', 'Cancelar', 'Hủy', 'ยกเลิก', 'Batal', 'إلغاء', 1, datetime('now'), datetime('now')),
  ('i26-gallery-021', 'guardian.pet.gallery.add_photo.save', 'guardian', '저장', 'Save', '保存', '保存', '儲存', 'Guardar', 'Enregistrer', 'Speichern', 'Salvar', 'Lưu', 'บันทึก', 'Simpan', 'حفظ', 1, datetime('now'), datetime('now')),
  ('i26-gallery-022', 'guardian.pet.gallery.add_photo.saving', 'guardian', '저장 중...', 'Saving...', '保存中...', '保存中...', '儲存中...', 'Guardando...', 'Enregistrement...', 'Speichern...', 'Salvando...', 'Đang lưu...', 'กำลังบันทึก...', 'Menyimpan...', 'جارٍ الحفظ...', 1, datetime('now'), datetime('now')),
  ('i26-gallery-023', 'guardian.pet.gallery.add_photo.error.file_required', 'guardian', '업로드할 사진을 선택해 주세요.', 'Please select a photo to upload.', 'アップロードする写真を選択してください。', '请选择要上传的照片。', '請選擇要上傳的照片。', 'Selecciona una foto para subir.', 'Veuillez sélectionner une photo à téléverser.', 'Bitte wählen Sie ein Foto zum Hochladen aus.', 'Selecione uma foto para enviar.', 'Vui lòng chọn ảnh để tải lên.', 'กรุณาเลือกรูปภาพที่จะอัปโหลด', 'Pilih foto untuk diunggah.', 'يرجى اختيار صورة للتحميل.', 1, datetime('now'), datetime('now')),
  ('i26-gallery-024', 'guardian.pet.gallery.add_photo.error.invalid_file_type', 'guardian', 'JPG, JPEG, PNG, WEBP 파일만 업로드할 수 있습니다.', 'Only JPG, JPEG, PNG, and WEBP files are allowed.', 'JPG、JPEG、PNG、WEBP ファイルのみアップロードできます。', '仅支持 JPG、JPEG、PNG、WEBP 文件。', '僅支援 JPG、JPEG、PNG、WEBP 檔案。', 'Solo se permiten archivos JPG, JPEG, PNG y WEBP.', 'Seuls les fichiers JPG, JPEG, PNG et WEBP sont autorisés.', 'Nur JPG-, JPEG-, PNG- und WEBP-Dateien sind erlaubt.', 'Apenas arquivos JPG, JPEG, PNG e WEBP são permitidos.', 'Chỉ cho phép tệp JPG, JPEG, PNG, WEBP.', 'รองรับเฉพาะไฟล์ JPG, JPEG, PNG, WEBP', 'Hanya file JPG, JPEG, PNG, WEBP yang diizinkan.', 'يُسمح فقط بملفات JPG وJPEG وPNG وWEBP.', 1, datetime('now'), datetime('now')),
  ('i26-gallery-025', 'guardian.pet.gallery.add_photo.error.file_too_large', 'guardian', '파일 크기는 10MB 이하만 허용됩니다.', 'File size must be 10MB or less.', 'ファイルサイズは10MB以下である必要があります。', '文件大小必须不超过 10MB。', '檔案大小必須小於 10MB。', 'El tamaño del archivo debe ser de 10 MB o menos.', 'La taille du fichier doit être inférieure ou égale à 10 Mo.', 'Die Dateigröße darf maximal 10 MB betragen.', 'O arquivo deve ter no máximo 10MB.', 'Kích thước tệp phải từ 10MB trở xuống.', 'ขนาดไฟล์ต้องไม่เกิน 10MB', 'Ukuran file harus 10MB atau kurang.', 'يجب ألا يتجاوز حجم الملف 10MB.', 1, datetime('now'), datetime('now')),
  ('i26-gallery-026', 'guardian.pet.gallery.add_photo.error.upload_failed', 'guardian', '파일 업로드에 실패했습니다.', 'File upload failed.', 'ファイルのアップロードに失敗しました。', '文件上传失败。', '檔案上傳失敗。', 'La carga del archivo falló.', 'Échec du téléversement du fichier.', 'Datei-Upload fehlgeschlagen.', 'Falha no upload do arquivo.', 'Tải tệp lên thất bại.', 'อัปโหลดไฟล์ล้มเหลว', 'Unggah file gagal.', 'فشل تحميل الملف.', 1, datetime('now'), datetime('now')),
  ('i26-gallery-027', 'guardian.pet.gallery.empty.no_pet', 'guardian', '등록된 펫이 없어 Gallery를 표시할 수 없습니다.', 'No registered pet. Gallery cannot be displayed.', '登録されたペットがないため、ギャラリーを表示できません。', '没有已注册宠物，无法显示相册。', '沒有已註冊寵物，無法顯示相簿。', 'No hay mascota registrada. No se puede mostrar la galería.', 'Aucun animal enregistré. Impossible d''afficher la galerie.', 'Kein registriertes Haustier. Galerie kann nicht angezeigt werden.', 'Nenhum pet registrado. Não é possível exibir a galeria.', 'Không có thú cưng đã đăng ký. Không thể hiển thị thư viện.', 'ไม่มีสัตว์เลี้ยงที่ลงทะเบียน จึงไม่สามารถแสดงแกลเลอรีได้', 'Tidak ada hewan peliharaan terdaftar. Galeri tidak dapat ditampilkan.', 'لا يوجد حيوان أليف مسجل. لا يمكن عرض المعرض.', 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO schema_migrations (version) VALUES ('0026_guardian_gallery_upload_i18n');
