-- 0042: Sync admin.master keys used by MasterPage (no hardcoded text)
-- 목적:
-- - MasterPage에서 사용하는 i18n key 집합을 DB에 보장
-- - 13개 언어 필드 공란 방지

INSERT INTO i18n_translations (
  id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at
) VALUES
  (lower(hex(randomblob(16))), 'admin.master.title', 'admin.master', '마스터 데이터 관리', 'Master Data', 'Master Data', 'Master Data', 'Master Data', 'Master Data', 'Master Data', 'Master Data', 'Master Data', 'Master Data', 'Master Data', 'Master Data', 'Master Data', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.guide', 'admin.master', '카테고리 -> L1 -> L2 -> L3(검사방법) -> L4(측정항목) -> L5(측정컨텍스트)', 'Category -> L1 -> L2 -> L3 (Test Method) -> L4 (Measurement) -> L5 (Context)', 'Category -> L1 -> L2 -> L3 (Test Method) -> L4 (Measurement) -> L5 (Context)', 'Category -> L1 -> L2 -> L3 (Test Method) -> L4 (Measurement) -> L5 (Context)', 'Category -> L1 -> L2 -> L3 (Test Method) -> L4 (Measurement) -> L5 (Context)', 'Category -> L1 -> L2 -> L3 (Test Method) -> L4 (Measurement) -> L5 (Context)', 'Category -> L1 -> L2 -> L3 (Test Method) -> L4 (Measurement) -> L5 (Context)', 'Category -> L1 -> L2 -> L3 (Test Method) -> L4 (Measurement) -> L5 (Context)', 'Category -> L1 -> L2 -> L3 (Test Method) -> L4 (Measurement) -> L5 (Context)', 'Category -> L1 -> L2 -> L3 (Test Method) -> L4 (Measurement) -> L5 (Context)', 'Category -> L1 -> L2 -> L3 (Test Method) -> L4 (Measurement) -> L5 (Context)', 'Category -> L1 -> L2 -> L3 (Test Method) -> L4 (Measurement) -> L5 (Context)', 'Category -> L1 -> L2 -> L3 (Test Method) -> L4 (Measurement) -> L5 (Context)', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.cat_list', 'admin.master', '카테고리', 'Category', 'Category', 'Category', 'Category', 'Category', 'Category', 'Category', 'Category', 'Category', 'Category', 'Category', 'Category', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.item_detail', 'admin.master', '선택 항목 설정', 'Selected Item Options', 'Selected Item Options', 'Selected Item Options', 'Selected Item Options', 'Selected Item Options', 'Selected Item Options', 'Selected Item Options', 'Selected Item Options', 'Selected Item Options', 'Selected Item Options', 'Selected Item Options', 'Selected Item Options', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.btn_add', 'admin.master', '추가', 'Add', 'Add', 'Add', 'Add', 'Add', 'Add', 'Add', 'Add', 'Add', 'Add', 'Add', 'Add', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.btn_edit', 'admin.master', '편집', 'Edit', 'Edit', 'Edit', 'Edit', 'Edit', 'Edit', 'Edit', 'Edit', 'Edit', 'Edit', 'Edit', 'Edit', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.btn_delete', 'admin.master', '삭제', 'Delete', 'Delete', 'Delete', 'Delete', 'Delete', 'Delete', 'Delete', 'Delete', 'Delete', 'Delete', 'Delete', 'Delete', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.btn_save', 'admin.master', '저장', 'Save', 'Save', 'Save', 'Save', 'Save', 'Save', 'Save', 'Save', 'Save', 'Save', 'Save', 'Save', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.btn_cancel', 'admin.master', '취소', 'Cancel', 'Cancel', 'Cancel', 'Cancel', 'Cancel', 'Cancel', 'Cancel', 'Cancel', 'Cancel', 'Cancel', 'Cancel', 'Cancel', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.btn_trans_auto', 'admin.master', '자동번역', 'Auto Translate', 'Auto Translate', 'Auto Translate', 'Auto Translate', 'Auto Translate', 'Auto Translate', 'Auto Translate', 'Auto Translate', 'Auto Translate', 'Auto Translate', 'Auto Translate', 'Auto Translate', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.loading_trans', 'admin.master', '번역 중...', 'Translating...', 'Translating...', 'Translating...', 'Translating...', 'Translating...', 'Translating...', 'Translating...', 'Translating...', 'Translating...', 'Translating...', 'Translating...', 'Translating...', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.cat_create', 'admin.master', '카테고리 생성', 'Create Category', 'Create Category', 'Create Category', 'Create Category', 'Create Category', 'Create Category', 'Create Category', 'Create Category', 'Create Category', 'Create Category', 'Create Category', 'Create Category', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.cat_edit', 'admin.master', '카테고리 수정', 'Edit Category', 'Edit Category', 'Edit Category', 'Edit Category', 'Edit Category', 'Edit Category', 'Edit Category', 'Edit Category', 'Edit Category', 'Edit Category', 'Edit Category', 'Edit Category', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.item_create', 'admin.master', '아이템 생성', 'Create Item', 'Create Item', 'Create Item', 'Create Item', 'Create Item', 'Create Item', 'Create Item', 'Create Item', 'Create Item', 'Create Item', 'Create Item', 'Create Item', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.item_edit', 'admin.master', '아이템 수정', 'Edit Item', 'Edit Item', 'Edit Item', 'Edit Item', 'Edit Item', 'Edit Item', 'Edit Item', 'Edit Item', 'Edit Item', 'Edit Item', 'Edit Item', 'Edit Item', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.field_category', 'admin.master', '카테고리', 'Category', 'Category', 'Category', 'Category', 'Category', 'Category', 'Category', 'Category', 'Category', 'Category', 'Category', 'Category', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.field_key', 'admin.master', 'Key (자동생성 가능)', 'Key (auto-generated if empty)', 'Key (auto-generated if empty)', 'Key (auto-generated if empty)', 'Key (auto-generated if empty)', 'Key (auto-generated if empty)', 'Key (auto-generated if empty)', 'Key (auto-generated if empty)', 'Key (auto-generated if empty)', 'Key (auto-generated if empty)', 'Key (auto-generated if empty)', 'Key (auto-generated if empty)', 'Key (auto-generated if empty)', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.field_parent', 'admin.master', '부모 항목', 'Parent Item', 'Parent Item', 'Parent Item', 'Parent Item', 'Parent Item', 'Parent Item', 'Parent Item', 'Parent Item', 'Parent Item', 'Parent Item', 'Parent Item', 'Parent Item', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.field_sort', 'admin.master', '정렬 순서', 'Sort Order', 'Sort Order', 'Sort Order', 'Sort Order', 'Sort Order', 'Sort Order', 'Sort Order', 'Sort Order', 'Sort Order', 'Sort Order', 'Sort Order', 'Sort Order', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.ph_key', 'admin.master', '비우면 자동 생성', 'Leave empty for auto-generation', 'Leave empty for auto-generation', 'Leave empty for auto-generation', 'Leave empty for auto-generation', 'Leave empty for auto-generation', 'Leave empty for auto-generation', 'Leave empty for auto-generation', 'Leave empty for auto-generation', 'Leave empty for auto-generation', 'Leave empty for auto-generation', 'Leave empty for auto-generation', 'Leave empty for auto-generation', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.opt_none', 'admin.master', '-- 없음 --', '-- None --', '-- None --', '-- None --', '-- None --', '-- None --', '-- None --', '-- None --', '-- None --', '-- None --', '-- None --', '-- None --', '-- None --', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.active', 'admin.master', '활성', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.inactive', 'admin.master', '비활성', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.empty_cat', 'admin.master', '카테고리를 선택하세요.', 'Select a category.', 'Select a category.', 'Select a category.', 'Select a category.', 'Select a category.', 'Select a category.', 'Select a category.', 'Select a category.', 'Select a category.', 'Select a category.', 'Select a category.', 'Select a category.', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.empty_item', 'admin.master', '아이템이 없습니다.', 'No items.', 'No items.', 'No items.', 'No items.', 'No items.', 'No items.', 'No items.', 'No items.', 'No items.', 'No items.', 'No items.', 'No items.', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.missing_translation', 'admin.master', '번역 누락', 'Missing translation', 'Missing translation', 'Missing translation', 'Missing translation', 'Missing translation', 'Missing translation', 'Missing translation', 'Missing translation', 'Missing translation', 'Missing translation', 'Missing translation', 'Missing translation', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.err_required', 'admin.master', '필수 항목입니다.', 'Required field.', 'Required field.', 'Required field.', 'Required field.', 'Required field.', 'Required field.', 'Required field.', 'Required field.', 'Required field.', 'Required field.', 'Required field.', 'Required field.', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.err_key_fmt', 'admin.master', 'Key는 소문자/숫자/언더스코어만 허용됩니다.', 'Key allows only lowercase letters, numbers, and underscores.', 'Key allows only lowercase letters, numbers, and underscores.', 'Key allows only lowercase letters, numbers, and underscores.', 'Key allows only lowercase letters, numbers, and underscores.', 'Key allows only lowercase letters, numbers, and underscores.', 'Key allows only lowercase letters, numbers, and underscores.', 'Key allows only lowercase letters, numbers, and underscores.', 'Key allows only lowercase letters, numbers, and underscores.', 'Key allows only lowercase letters, numbers, and underscores.', 'Key allows only lowercase letters, numbers, and underscores.', 'Key allows only lowercase letters, numbers, and underscores.', 'Key allows only lowercase letters, numbers, and underscores.', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.err_trans_missing', 'admin.master', '번역값이 비어 있습니다: {langs}', 'Missing translation values: {langs}', 'Missing translation values: {langs}', 'Missing translation values: {langs}', 'Missing translation values: {langs}', 'Missing translation values: {langs}', 'Missing translation values: {langs}', 'Missing translation values: {langs}', 'Missing translation values: {langs}', 'Missing translation values: {langs}', 'Missing translation values: {langs}', 'Missing translation values: {langs}', 'Missing translation values: {langs}', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.msg_success', 'admin.master', '처리되었습니다.', 'Completed.', 'Completed.', 'Completed.', 'Completed.', 'Completed.', 'Completed.', 'Completed.', 'Completed.', 'Completed.', 'Completed.', 'Completed.', 'Completed.', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.msg_confirm_delete', 'admin.master', '삭제하시겠습니까?', 'Are you sure you want to delete?', 'Are you sure you want to delete?', 'Are you sure you want to delete?', 'Are you sure you want to delete?', 'Are you sure you want to delete?', 'Are you sure you want to delete?', 'Are you sure you want to delete?', 'Are you sure you want to delete?', 'Are you sure you want to delete?', 'Are you sure you want to delete?', 'Are you sure you want to delete?', 'Are you sure you want to delete?', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.error_target_cat_not_found', 'admin.master', '대상 카테고리를 찾을 수 없습니다.', 'Target category not found.', 'Target category not found.', 'Target category not found.', 'Target category not found.', 'Target category not found.', 'Target category not found.', 'Target category not found.', 'Target category not found.', 'Target category not found.', 'Target category not found.', 'Target category not found.', 'Target category not found.', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.select_parent_req', 'admin.master', '상위 레벨을 먼저 선택해주세요.', 'Select parent level first.', 'Select parent level first.', 'Select parent level first.', 'Select parent level first.', 'Select parent level first.', 'Select parent level first.', 'Select parent level first.', 'Select parent level first.', 'Select parent level first.', 'Select parent level first.', 'Select parent level first.', 'Select parent level first.', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.level_title', 'admin.master', 'L{level}', 'L{level}', 'L{level}', 'L{level}', 'L{level}', 'L{level}', 'L{level}', 'L{level}', 'L{level}', 'L{level}', 'L{level}', 'L{level}', 'L{level}', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.level_title_named', 'admin.master', 'L{level} · {name}', 'L{level} · {name}', 'L{level} · {name}', 'L{level} · {name}', 'L{level} · {name}', 'L{level} · {name}', 'L{level} · {name}', 'L{level} · {name}', 'L{level} · {name}', 'L{level} · {name}', 'L{level} · {name}', 'L{level} · {name}', 'L{level} · {name}', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.master.level_select_required', 'admin.master', 'L{level} 선택 필요', 'Select L{level}', 'Select L{level}', 'Select L{level}', 'Select L{level}', 'Select L{level}', 'Select L{level}', 'Select L{level}', 'Select L{level}', 'Select L{level}', 'Select L{level}', 'Select L{level}', 'Select L{level}', 1, datetime('now'), datetime('now'))
ON CONFLICT(key) DO UPDATE SET
  ko = excluded.ko,
  en = excluded.en,
  ja = excluded.ja,
  zh_cn = excluded.zh_cn,
  zh_tw = excluded.zh_tw,
  es = excluded.es,
  fr = excluded.fr,
  de = excluded.de,
  pt = excluded.pt,
  vi = excluded.vi,
  th = excluded.th,
  id_lang = excluded.id_lang,
  ar = excluded.ar,
  is_active = 1,
  updated_at = datetime('now');

