-- 0042: Admin UI Full i18n
-- Insert translations for Admin Web UI elements (admin.master.*)
-- NOTE:
-- Existing rows may already use page='admin.master', so delete by key prefix only.

DELETE FROM i18n_translations
WHERE key LIKE 'admin.master.%';

INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at)
VALUES
('ui-admin-m-001', 'admin.master.title', 'admin', '마스터 데이터 관리', 'Master Data Management', 'マスターデータ管理', '主数据管理', '主數據管理', 'Gestión de datos maestros', 'Gestion des données de base', 'Stammdatenverwaltung', 'Gerenciamento de dados mestres', 'Quản lý dữ liệu chủ', 'การจัดการข้อมูลหลัก', 'Manajemen Data Master', 'إدارة البيانات الرئيسية', 1, datetime('now'), datetime('now')),
('ui-admin-m-002', 'admin.master.guide', 'admin', '질병군, 펫 타입 등 시스템 전반의 기준 정보를 계층 구조로 관리합니다.', 'Manage system-wide reference data like disease groups and pet types in a hierarchy.', '疾患群、ペットタイプなど、システム全般の基準情報を階層構造で管理します。', '分层管理疾病组、宠物类型等全系统参考数据。', '分層管理疾病組、寵物類型等全系統參考數據。', 'Administre datos de referencia en todo el sistema, como grupos de enfermedades y tipos de mascotas, en una jerarquía.', 'Gérez les données de référence à l''échelle du système, comme les groupes de maladies et les types d''animaux, dans une hiérarchie.', 'Verwalten Sie systemweite Referenzdaten wie Krankheitsgruppen und Haustiertypen in einer Hierarchie.', 'Gerencie dados de referência em todo o sistema, como grupos de doenças e tipos de animais de estimação, em uma hierarquia.', 'Quản lý dữ liệu tham chiếu toàn hệ thống như nhóm bệnh và loại thú cưng theo phân cấp.', 'จัดการข้อมูลอ้างอิงทั่วทั้งระบบ เช่น กลุ่มโรคและประเภทสัตว์เลี้ยง ตามลำดับชั้น', 'Kelola data referensi seluruh sistem seperti kelompok penyakit dan jenis hewan peliharaan dalam hierarki.', 'إدارة البيانات المرجعية على مستوى النظام مثل مجموعات الأمراض وأنواع الحيوانات الأليفة في تسلسل هرمي.', 1, datetime('now'), datetime('now')),
-- (Button labels)
('ui-admin-m-010', 'admin.master.btn_add', 'admin', '추가', 'Add', '追加', '添加', '添加', 'Añadir', 'Ajouter', 'Hinzufügen', 'Adicionar', 'Thêm', 'เพิ่ม', 'Tambah', 'إضافة', 1, datetime('now'), datetime('now')),
('ui-admin-m-011', 'admin.master.btn_edit', 'admin', '수정', 'Edit', '編集', '编辑', '編輯', 'Editar', 'Modifier', 'Bearbeiten', 'Editar', 'Sửa', 'แก้ไข', 'Edit', 'تعديل', 1, datetime('now'), datetime('now')),
('ui-admin-m-012', 'admin.master.btn_delete', 'admin', '삭제', 'Delete', '削除', '删除', '刪除', 'Eliminar', 'Supprimer', 'Löschen', 'Excluir', 'Xóa', 'ลบ', 'Hapus', 'حذف', 1, datetime('now'), datetime('now')),
('ui-admin-m-013', 'admin.master.btn_save', 'admin', '저장', 'Save', '保存', '保存', '保存', 'Guardar', 'Enregistrer', 'Speichern', 'Salvar', 'Lưu', 'บันทึก', 'Simpan', 'حفظ', 1, datetime('now'), datetime('now')),
('ui-admin-m-014', 'admin.master.btn_cancel', 'admin', '취소', 'Cancel', 'キャンセル', '取消', '取消', 'Cancelar', 'Annuler', 'Abbrechen', 'Cancelar', 'Hủy', 'ยกเลิก', 'Batal', 'إلغاء', 1, datetime('now'), datetime('now')),
('ui-admin-m-015', 'admin.master.btn_trans_auto', 'admin', '번역 자동 완성', 'Auto Translate', '自動翻訳', '自动翻译', '自動翻譯', 'Traducción automática', 'Traduction automatique', 'Automatische Übersetzung', 'Tradução automática', 'Dịch tự động', 'แปลอัตโนมัติ', 'Terjemahan Otomatis', 'ترجمة تلقائية', 1, datetime('now'), datetime('now')),
('ui-admin-m-016', 'admin.master.loading_trans', 'admin', '번역 중...', 'Translating...', '翻訳中...', '翻译中...', '翻譯中...', 'Traduciendo...', 'Traduction...', 'Übersetzen...', 'Traduzindo...', 'Đang dịch...', 'กำลังแปล...', 'Menerjemahkan...', 'جاري الترجمة...', 1, datetime('now'), datetime('now')),
-- (Labels & Placeholders)
('ui-admin-m-020', 'admin.master.cat_list', 'admin', '카테고리 목록', 'Category List', 'カテゴリ一覧', '类别列表', '類別列表', 'Lista de categorías', 'Liste des catégories', 'Kategorieliste', 'Lista de categorias', 'Danh sách danh mục', 'รายการหมวดหมู่', 'Daftar Kategori', 'قائمة الفئات', 1, datetime('now'), datetime('now')),
('ui-admin-m-021', 'admin.master.field_key', 'admin', '키 (Key)', 'Key', 'キー', '键', '鍵', 'Clave', 'Clé', 'Schlüssel', 'Chave', 'Khóa', 'คีย์', 'Kunci', 'مفتاح', 1, datetime('now'), datetime('now')),
('ui-admin-m-022', 'admin.master.ph_key', 'admin', '예: pet_type', 'e.g. pet_type', '例: pet_type', '例如: pet_type', '例如: pet_type', 'ej. pet_type', 'ex. pet_type', 'z.B. pet_type', 'ex. pet_type', 'ví dụ: pet_type', 'เช่น pet_type', 'contoh: pet_type', 'مثال: pet_type', 1, datetime('now'), datetime('now')),
('ui-admin-m-023', 'admin.master.field_sort', 'admin', '정렬 순서', 'Sort Order', '並び順', '排序顺序', '排序順序', 'Orden de clasificación', 'Ordre de tri', 'Sortierreihenfolge', 'Ordem de classificação', 'Thứ tự sắp xếp', 'ลำดับการเรียง', 'Urutan Sortir', 'ترتيب الفرز', 1, datetime('now'), datetime('now')),
('ui-admin-m-024', 'admin.master.field_parent', 'admin', '상위 항목', 'Parent Item', '親項目', '父项', '父項', 'Elemento padre', 'Élément parent', 'Übergeordnetes Element', 'Item pai', 'Mục cha', 'รายการหลัก', 'Item Induk', 'العنصر الأصلي', 1, datetime('now'), datetime('now')),
('ui-admin-m-025', 'admin.master.field_category', 'admin', '카테고리', 'Category', 'カテゴリ', '类别', '類別', 'Categoría', 'Catégorie', 'Kategorie', 'Categoria', 'Danh mục', 'หมวดหมู่', 'Kategori', 'فئة', 1, datetime('now'), datetime('now')),
('ui-admin-m-026', 'admin.master.opt_none', 'admin', '없음 (최상위)', 'None (Top Level)', 'なし（最上位）', '无（顶级）', '無（頂級）', 'Ninguno (Nivel superior)', 'Aucun (Niveau supérieur)', 'Keine (Oberste Ebene)', 'Nenhum (Nível superior)', 'Không (Cấp cao nhất)', 'ไม่มี (ระดับบนสุด)', 'Tidak Ada (Tingkat Atas)', 'لا شيء (المستوى الأعلى)', 1, datetime('now'), datetime('now')),
('ui-admin-m-027', 'admin.master.active', 'admin', '사용 중', 'Active', '使用中', '使用中', '使用中', 'Activo', 'Actif', 'Aktiv', 'Ativo', 'Đang hoạt động', 'ใช้งานอยู่', 'Aktif', 'نشط', 1, datetime('now'), datetime('now')),
('ui-admin-m-028', 'admin.master.inactive', 'admin', '미사용', 'Inactive', '未使用', '未使用', '未使用', 'Inactivo', 'Inactif', 'Inaktiv', 'Inativo', 'Không hoạt động', 'ไม่ได้ใช้งาน', 'Tidak Aktif', 'غير نشط', 1, datetime('now'), datetime('now')),
-- (Messages)
('ui-admin-m-030', 'admin.master.empty_cat', 'admin', '등록된 카테고리가 없습니다.', 'No categories found.', '登録されたカテゴリがありません。', '未找到类别。', '未找到類別。', 'No se encontraron categorías.', 'Aucune catégorie trouvée.', 'Keine Kategorien gefunden.', 'Nenhuma categoria encontrada.', 'Không tìm thấy danh mục.', 'ไม่พบหมวดหมู่', 'Kategori tidak ditemukan.', 'لم يتم العثور على فئات.', 1, datetime('now'), datetime('now')),
('ui-admin-m-031', 'admin.master.empty_item', 'admin', '항목이 없습니다.', 'No items found.', '項目がありません。', '未找到项目。', '未找到項目。', 'No se encontraron elementos.', 'Aucun élément trouvé.', 'Keine Elemente gefunden.', 'Nenhum item encontrado.', 'Không tìm thấy mục.', 'ไม่พบรายการ', 'Item tidak ditemukan.', 'لم يتم العثور على عناصر.', 1, datetime('now'), datetime('now')),
('ui-admin-m-032', 'admin.master.select_parent_req', 'admin', '상위 단계를 먼저 선택해주세요.', 'Please select a parent level first.', '上位レベルを先に選択してください。', '请先选择父级。', '請先選擇父級。', 'Seleccione primero un nivel principal.', 'Veuillez d''abord sélectionner un niveau parent.', 'Bitte wählen Sie zuerst eine übergeordnete Ebene aus.', 'Selecione um nível pai primeiro.', 'Vui lòng chọn cấp cha trước.', 'โปรดเลือกระดับหลักก่อน', 'Silakan pilih level induk terlebih dahulu.', 'الرجاء تحديد المستوى الأصلي أولاً.', 1, datetime('now'), datetime('now')),
('ui-admin-m-033', 'admin.master.msg_confirm_delete', 'admin', '정말 삭제하시겠습니까?', 'Are you sure you want to delete this?', '本当に削除しますか？', '您确定要删除吗？', '您確定要刪除嗎？', '¿Está seguro de que desea eliminar esto?', 'Êtes-vous sûr de vouloir supprimer ceci ?', 'Sind Sie sicher, dass Sie dies löschen möchten?', 'Tem certeza de que deseja excluir isso?', 'Bạn có chắc chắn muốn xóa không?', 'คุณแน่ใจหรือไม่ว่าต้องการลบสิ่งนี้', 'Apakah Anda yakin ingin menghapus ini?', 'هل أنت متأكد أنك تريد حذف هذا؟', 1, datetime('now'), datetime('now')),
('ui-admin-m-034', 'admin.master.msg_success', 'admin', '성공적으로 처리되었습니다.', 'Processed successfully.', '正常に処理されました。', '处理成功。', '處理成功。', 'Procesado con éxito.', 'Traité avec succès.', 'Erfolgreich verarbeitet.', 'Processado com sucesso.', 'Xử lý thành công.', 'ประมวลผลสำเร็จ', 'Berhasil diproses.', 'تمت المعالجة بنجاح.', 1, datetime('now'), datetime('now')),
('ui-admin-m-035', 'admin.master.err_required', 'admin', '필수 입력 항목입니다.', 'This field is required.', '必須項目です。', '此字段为必填项。', '此欄位為必填項。', 'Este campo es obligatorio.', 'Ce champ est obligatoire.', 'Dieses Feld ist erforderlich.', 'Este campo é obrigatório.', 'Trường này là bắt buộc.', 'จำเป็นต้องกรอกข้อมูลในช่องนี้', 'Bidang ini wajib diisi.', 'هذا الحقل مطلوب.', 1, datetime('now'), datetime('now')),
('ui-admin-m-036', 'admin.master.err_key_fmt', 'admin', '키는 영문 소문자, 숫자, 언더바(_)만 가능합니다.', 'Key must contain only lowercase letters, numbers, and underscores.', 'キーは英小文字、数字、アンダースコア（_）のみ使用可能です。', '键只能包含小写字母、数字和下划线。', '鍵只能包含小寫字母、數字和下劃線。', 'La clave solo debe contener letras minúsculas, números y guiones bajos.', 'La clé ne doit contenir que des lettres minuscules, des chiffres et des traits de soulignement.', 'Der Schlüssel darf nur Kleinbuchstaben, Zahlen und Unterstriche enthalten.', 'A chave deve conter apenas letras minúsculas, números e sublinhados.', 'Khóa chỉ được chứa chữ cái thường, số và dấu gạch dưới.', 'คีย์ต้องประกอบด้วยตัวอักษรพิมพ์เล็ก ตัวเลข และขีดล่างเท่านั้น', 'Kunci harus berisi huruf kecil, angka, dan garis bawah saja.', 'يجب أن يحتوي المفتاح على أحرف صغيرة وأرقام وشرطة سفلية فقط.', 1, datetime('now'), datetime('now')),
('ui-admin-m-037', 'admin.master.err_trans_missing', 'admin', '모든 언어의 번역을 입력해주세요: {langs}', 'Please enter translations for all languages: {langs}', 'すべての言語の翻訳を入力してください: {langs}', '请输入所有语言的翻译: {langs}', '請輸入所有語言的翻譯: {langs}', 'Introduzca traducciones para todos los idiomas: {langs}', 'Veuillez saisir les traductions pour toutes les langues: {langs}', 'Bitte geben Sie Übersetzungen für alle Sprachen ein: {langs}', 'Insira traduções para todos os idiomas: {langs}', 'Vui lòng nhập bản dịch cho tất cả các ngôn ngữ: {langs}', 'โปรดป้อนคำแปลสำหรับทุกภาษา: {langs}', 'Silakan masukkan terjemahan untuk semua bahasa: {langs}', 'الرجاء إدخال الترجمات لجميع اللغات: {langs}', 1, datetime('now'), datetime('now')),
('ui-admin-m-038', 'admin.master.level_title', 'admin', '{level}단계 항목', 'Level {level} Items', 'レベル{level}項目', '{level}级项目', '{level}級項目', 'Elementos de nivel {level}', 'Éléments de niveau {level}', 'Elemente der Ebene {level}', 'Itens de nível {level}', 'Mục cấp {level}', 'รายการระดับ {level}', 'Item Level {level}', 'عناصر المستوى {level}', 1, datetime('now'), datetime('now')),
('ui-admin-m-039', 'admin.master.level_title_named', 'admin', '{level}단계: {name}', 'Level {level}: {name}', 'レベル{level}: {name}', '{level}级: {name}', '{level}級: {name}', 'Nivel {level}: {name}', 'Niveau {level}: {name}', 'Ebene {level}: {name}', 'Nível {level}: {name}', 'Cấp {level}: {name}', 'ระดับ {level}: {name}', 'Level {level}: {name}', 'المستوى {level}: {name}', 1, datetime('now'), datetime('now')),
('ui-admin-m-040', 'admin.master.item_detail', 'admin', '항목 상세', 'Item Details', '項目詳細', '项目详情', '項目詳情', 'Detalles del elemento', 'Détails de l''élément', 'Elementdetails', 'Detalhes do item', 'Chi tiết mục', 'รายละเอียดรายการ', 'Detail Item', 'تفاصيل العنصر', 1, datetime('now'), datetime('now')),
('ui-admin-m-041', 'admin.master.cat_create', 'admin', '카테고리 생성', 'Create Category', 'カテゴリ作成', '创建类别', '創建類別', 'Crear categoría', 'Créer une catégorie', 'Kategorie erstellen', 'Criar categoria', 'Tạo danh mục', 'สร้างหมวดหมู่', 'Buat Kategori', 'إنشاء فئة', 1, datetime('now'), datetime('now')),
('ui-admin-m-042', 'admin.master.cat_edit', 'admin', '카테고리 수정', 'Edit Category', 'カテゴリ編集', '编辑类别', '編輯類別', 'Editar categoría', 'Modifier la catégorie', 'Kategorie bearbeiten', 'Editar categoria', 'Sửa danh mục', 'แก้ไขหมวดหมู่', 'Edit Kategori', 'تعديل الفئة', 1, datetime('now'), datetime('now')),
('ui-admin-m-043', 'admin.master.item_create', 'admin', '항목 생성', 'Create Item', '項目作成', '创建项目', '創建項目', 'Crear elemento', 'Créer un élément', 'Element erstellen', 'Criar item', 'Tạo mục', 'สร้างรายการ', 'Buat Item', 'إنشاء عنصر', 1, datetime('now'), datetime('now')),
('ui-admin-m-044', 'admin.master.item_edit', 'admin', '항목 수정', 'Edit Item', '項目編集', '编辑项目', '編輯項目', 'Editar elemento', 'Modifier l''élément', 'Element bearbeiten', 'Editar item', 'Sửa mục', 'แก้ไขรายการ', 'Edit Item', 'تعديل العنصر', 1, datetime('now'), datetime('now')),
('ui-admin-m-045', 'admin.master.missing_translation', 'admin', '번역 필요', 'Translation Missing', '翻訳が必要', '缺少翻译', '缺少翻譯', 'Falta traducción', 'Traduction manquante', 'Übersetzung fehlt', 'Tradução ausente', 'Thiếu bản dịch', 'ขาดคำแปล', 'Terjemahan Hilang', 'الترجمة مفقودة', 1, datetime('now'), datetime('now')),
('ui-admin-m-046', 'admin.master.error_target_cat_not_found', 'admin', '대상 카테고리를 찾을 수 없습니다.', 'Target category not found.', '対象カテゴリが見つかりません。', '未找到目标类别。', '未找到目標類別。', 'Categoría de destino no encontrada.', 'Catégorie cible introuvable.', 'Zielkategorie nicht gefunden.', 'Categoria de destino não encontrada.', 'Không tìm thấy danh mục đích.', 'ไม่พบหมวดหมู่เป้าหมาย', 'Kategori target tidak ditemukan.', 'لم يتم العثور على الفئة المستهدفة.', 1, datetime('now'), datetime('now')),
('ui-admin-m-047', 'admin.master.level_select_required', 'admin', '{level}단계 선택 필요', 'Level {level} Selection Required', 'レベル{level}の選択が必要です', '需要选择{level}级', '需要選擇{level}級', 'Se requiere selección de nivel {level}', 'Sélection de niveau {level} requise', 'Auswahl der Ebene {level} erforderlich', 'Seleção de nível {level} necessária', 'Cần chọn cấp {level}', 'จำเป็นต้องเลือกระดับ {level}', 'Pemilihan Level {level} Diperlukan', 'مطلوب تحديد المستوى {level}', 1, datetime('now'), datetime('now'));
