-- 0045_device_mgmt_i18n.sql
-- i18n keys for Device Management admin page + nav

INSERT OR IGNORE INTO i18n_translations
  (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at)
VALUES
  (lower(hex(randomblob(16))), 'admin.nav.devices',           'admin', '장치 관리',     'Device Management',   '機器管理',           '设备管理',         '設備管理',         'Gestión de dispositivos', 'Gestion des appareils',  'Geräteverwaltung',      'Gestão de dispositivos',  'Quản lý thiết bị',       'การจัดการอุปกรณ์',    'Manajemen Perangkat',      'إدارة الأجهزة',       1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.title',          'admin', '장치 관리',     'Device Management',   '機器管理',           '设备管理',         '設備管理',         'Gestión de dispositivos', 'Gestion des appareils',  'Geräteverwaltung',      'Gestão de dispositivos',  'Quản lý thiết bị',       'การจัดการอุปกรณ์',    'Manajemen Perangkat',      'إدارة الأجهزة',       1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.types',          'admin', '장치 유형',     'Device Types',        '機器タイプ',         '设备类型',         '設備類型',         'Tipos de dispositivo',    'Types d''appareil',      'Gerätetypen',           'Tipos de dispositivo',    'Loại thiết bị',          'ประเภทอุปกรณ์',       'Jenis Perangkat',          'أنواع الأجهزة',       1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.manufacturers',  'admin', '제조사',        'Manufacturers',       'メーカー',           '制造商',           '製造商',           'Fabricantes',             'Fabricants',             'Hersteller',            'Fabricantes',             'Nhà sản xuất',           'ผู้ผลิต',             'Produsen',                 'المصنعون',            1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.brands',         'admin', '브랜드',        'Brands',              'ブランド',           '品牌',             '品牌',             'Marcas',                  'Marques',                'Marken',                'Marcas',                  'Thương hiệu',            'แบรนด์',              'Merek',                    'العلامات التجارية',   1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.models',         'admin', '모델',          'Models',              'モデル',             '型号',             '型號',             'Modelos',                 'Modèles',                'Modelle',               'Modelos',                 'Mẫu',                    'รุ่น',                'Model',                    'الموديلات',           1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.units',          'admin', '측정 단위',     'Measurement Units',   '測定単位',           '测量单位',         '測量單位',         'Unidades de medida',      'Unités de mesure',       'Messeinheiten',         'Unidades de medida',      'Đơn vị đo',              'หน่วยวัด',            'Satuan Pengukuran',        'وحدات القياس',        1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.add_type',       'admin', '유형 추가',     'Add Type',            'タイプ追加',         '添加类型',         '新增類型',         'Agregar tipo',            'Ajouter un type',        'Typ hinzufügen',        'Adicionar tipo',          'Thêm loại',              'เพิ่มประเภท',         'Tambah Jenis',             'إضافة نوع',           1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.add_manufacturer','admin','제조사 추가',   'Add Manufacturer',    'メーカー追加',       '添加制造商',       '新增製造商',       'Agregar fabricante',      'Ajouter un fabricant',   'Hersteller hinzufügen', 'Adicionar fabricante',    'Thêm nhà sản xuất',      'เพิ่มผู้ผลิต',        'Tambah Produsen',          'إضافة مصنّع',         1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.add_brand',      'admin', '브랜드 추가',   'Add Brand',           'ブランド追加',       '添加品牌',         '新增品牌',         'Agregar marca',           'Ajouter une marque',     'Marke hinzufügen',      'Adicionar marca',         'Thêm thương hiệu',       'เพิ่มแบรนด์',         'Tambah Merek',             'إضافة علامة تجارية',  1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.add_model',      'admin', '모델 추가',     'Add Model',           'モデル追加',         '添加型号',         '新增型號',         'Agregar modelo',          'Ajouter un modèle',      'Modell hinzufügen',     'Adicionar modelo',        'Thêm mẫu',               'เพิ่มรุ่น',           'Tambah Model',             'إضافة موديل',         1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.model_name',     'admin', '모델명',        'Model Name',          'モデル名',           '型号名称',         '型號名稱',         'Nombre del modelo',       'Nom du modèle',          'Modellname',            'Nome do modelo',          'Tên mẫu',                'ชื่อรุ่น',            'Nama Model',               'اسم الموديل',         1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.model_code',     'admin', '모델코드',      'Model Code',          'モデルコード',       '型号代码',         '型號代碼',         'Código del modelo',       'Code du modèle',         'Modellcode',            'Código do modelo',        'Mã mẫu',                 'รหัสรุ่น',            'Kode Model',               'كود الموديل',         1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.country',        'admin', '국가',          'Country',             '国',                 '国家',             '國家',             'País',                    'Pays',                   'Land',                  'País',                    'Quốc gia',               'ประเทศ',              'Negara',                   'البلد',               1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.nickname',       'admin', '별칭',          'Nickname',            'ニックネーム',       '别名',             '別名',             'Apodo',                   'Surnom',                 'Spitzname',             'Apelido',                 'Tên gọi',                'ชื่อเล่น',            'Nama Panggilan',           'اللقب',               1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.serial',         'admin', '시리얼번호',    'Serial Number',       'シリアル番号',       '序列号',           '序號',             'Número de serie',         'Numéro de série',        'Seriennummer',          'Número de série',         'Số serial',              'หมายเลขซีเรียล',      'Nomor Seri',               'الرقم التسلسلي',      1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.start_date',     'admin', '사용시작일',    'Start Date',          '使用開始日',         '开始使用日期',     '開始使用日期',     'Fecha de inicio',         'Date de début',          'Startdatum',            'Data de início',          'Ngày bắt đầu',           'วันที่เริ่มต้น',      'Tanggal Mulai',            'تاريخ البدء',         1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.description',    'admin', '설명',          'Description',         '説明',               '描述',             '描述',             'Descripción',             'Description',            'Beschreibung',          'Descrição',               'Mô tả',                  'คำอธิบาย',            'Deskripsi',                'الوصف',               1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.key',            'admin', '키',            'Key',                 'キー',               '键',               '鍵',               'Clave',                   'Clé',                    'Schlüssel',             'Chave',                   'Khóa',                   'คีย์',                'Kunci',                    'المفتاح',             1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.name_ko',        'admin', '한국어 이름',   'Korean Name',         '韓国語名',           '韩文名称',         '韓文名稱',         'Nombre en coreano',       'Nom en coréen',          'Koreanischer Name',     'Nome em coreano',         'Tên tiếng Hàn',          'ชื่อภาษาเกาหลี',      'Nama Korea',               'الاسم بالكورية',      1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.name_en',        'admin', '영어 이름',     'English Name',        '英語名',             '英文名称',         '英文名稱',         'Nombre en inglés',        'Nom en anglais',         'Englischer Name',       'Nome em inglês',          'Tên tiếng Anh',          'ชื่อภาษาอังกฤษ',      'Nama Inggris',             'الاسم بالإنجليزية',   1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.symbol',         'admin', '기호',          'Symbol',              'シンボル',           '符号',             '符號',             'Símbolo',                 'Symbole',                'Symbol',                'Símbolo',                 'Ký hiệu',                'สัญลักษณ์',           'Simbol',                   'الرمز',               1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.empty',          'admin', '항목 없음',     'No items',            '項目なし',           '无项目',           '無項目',           'Sin elementos',           'Aucun élément',          'Keine Einträge',        'Sem itens',               'Không có mục nào',       'ไม่มีรายการ',         'Tidak ada item',           'لا توجد عناصر',       1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.select_type',    'admin', '유형을 선택하세요', 'Select a type',    'タイプを選択',       '选择类型',         '選擇類型',         'Seleccionar tipo',        'Sélectionner un type',   'Typ auswählen',         'Selecionar tipo',         'Chọn loại',              'เลือกประเภท',         'Pilih Jenis',              'اختر النوع',          1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.select_manufacturer','admin','제조사를 선택하세요','Select a manufacturer','メーカーを選択',  '选择制造商',       '選擇製造商',       'Seleccionar fabricante',  'Sélectionner un fabricant','Hersteller auswählen', 'Selecionar fabricante',   'Chọn nhà sản xuất',      'เลือกผู้ผลิต',        'Pilih Produsen',           'اختر المصنّع',        1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.select_brand',   'admin', '브랜드를 선택하세요','Select a brand',  'ブランドを選択',     '选择品牌',         '選擇品牌',         'Seleccionar marca',       'Sélectionner une marque','Marke auswählen',       'Selecionar marca',        'Chọn thương hiệu',       'เลือกแบรนด์',         'Pilih Merek',              'اختر العلامة التجارية',1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.guide',          'admin', '장치 유형 → 제조사 → 브랜드 → 모델 순서로 관리합니다.', 'Manage in order: Device Type → Manufacturer → Brand → Model.', '機器タイプ → メーカー → ブランド → モデルの順に管理します。', '按设备类型→制造商→品牌→型号顺序管理。', '按設備類型→製造商→品牌→型號順序管理。', 'Administrar en orden: Tipo → Fabricante → Marca → Modelo.', 'Gérer dans l''ordre : Type → Fabricant → Marque → Modèle.', 'Verwalten in Reihenfolge: Typ → Hersteller → Marke → Modell.', 'Gerenciar na ordem: Tipo → Fabricante → Marca → Modelo.', 'Quản lý theo thứ tự: Loại → Nhà SX → Thương hiệu → Mẫu.', 'จัดการตามลำดับ: ประเภท → ผู้ผลิต → แบรนด์ → รุ่น', 'Kelola sesuai urutan: Jenis → Produsen → Merek → Model.', 'الإدارة بالترتيب: النوع ← المصنّع ← العلامة ← الموديل.', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.device_type',    'admin', '장치 유형',     'Device Type',         '機器タイプ',         '设备类型',         '設備類型',         'Tipo de dispositivo',     'Type d''appareil',       'Gerätetyp',             'Tipo de dispositivo',     'Loại thiết bị',          'ประเภทอุปกรณ์',       'Jenis Perangkat',          'نوع الجهاز',          1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.manufacturer',   'admin', '제조사',        'Manufacturer',        'メーカー',           '制造商',           '製造商',           'Fabricante',              'Fabricant',              'Hersteller',            'Fabricante',              'Nhà sản xuất',           'ผู้ผลิต',             'Produsen',                 'المصنّع',             1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.device.brand',          'admin', '브랜드',        'Brand',               'ブランド',           '品牌',             '品牌',             'Marca',                   'Marque',                 'Marke',                 'Marca',                   'Thương hiệu',            'แบรนด์',              'Merek',                    'العلامة التجارية',    1, datetime('now'), datetime('now'));
