-- 0047_logs_i18n.sql
-- S7: 건강 기록 UI i18n 키 (Guardian + 공통 alert 키)

INSERT OR IGNORE INTO i18n_translations
  (id, key, namespace, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_verified, created_at, updated_at)
VALUES
  -- ─── Guardian 로그 UI ─────────────────────────────────────────────────────
  ('i47-001', 'guardian.log.title',     'guardian', '건강 기록',          'Health Log',           '健康記録',             '健康记录',         '健康記錄',         'Historial de salud',        'Journal de santé',         'Gesundheitsprotokoll',  'Histórico de saúde',    'Nhật ký sức khỏe',      'บันทึกสุขภาพ',           'Log kesehatan',         'سجل الصحة',              1, datetime('now'), datetime('now')),
  ('i47-002', 'guardian.log.add',       'guardian', '기록 추가',          'Add Record',           '記録追加',             '添加记录',         '添加記錄',         'Agregar registro',          'Ajouter un enregistrement', 'Aufzeichnung hinzufügen','Adicionar registro',    'Thêm bản ghi',          'เพิ่มบันทึก',             'Tambah catatan',        'إضافة سجل',              1, datetime('now'), datetime('now')),
  ('i47-003', 'guardian.log.logtype',   'guardian', '기록 유형',          'Record Type',          '記録種別',             '记录类型',         '記錄類型',         'Tipo de registro',          'Type de registrement',     'Aufzeichnungstyp',      'Tipo de registro',      'Loại bản ghi',          'ประเภทบันทึก',            'Jenis catatan',         'نوع السجل',              1, datetime('now'), datetime('now')),
  ('i47-004', 'guardian.log.event_date','guardian', '기록 날짜',          'Date',                 '記録日',               '记录日期',         '記錄日期',         'Fecha de registro',         'Date de registrement',     'Aufzeichnungsdatum',    'Data do registro',      'Ngày ghi',              'วันที่บันทึก',             'Tanggal catatan',       'تاريخ السجل',            1, datetime('now'), datetime('now')),
  ('i47-005', 'guardian.log.event_time','guardian', '기록 시간',          'Time',                 '記録時刻',             '记录时间',         '記錄時間',         'Hora de registro',          'Heure de registrement',    'Aufzeichnungszeit',     'Hora do registro',      'Giờ ghi',               'เวลาบันทึก',               'Waktu catatan',         'وقت السجل',              1, datetime('now'), datetime('now')),
  ('i47-006', 'guardian.log.title_field','guardian','제목',               'Title',                'タイトル',             '标题',             '標題',             'Título',                    'Titre',                    'Titel',                 'Título',                'Tiêu đề',               'หัวเรื่อง',                'Judul',                 'العنوان',                1, datetime('now'), datetime('now')),
  ('i47-007', 'guardian.log.notes',     'guardian', '메모',              'Notes',                 'メモ',                 '备注',             '備註',             'Notas',                     'Notes',                    'Notizen',               'Notas',                 'Ghi chú',               'บันทึก',                  'Catatan',               'ملاحظات',                1, datetime('now'), datetime('now')),
  ('i47-008', 'guardian.log.values',    'guardian', '측정값',             'Measurements',         '測定値',               '测量值',           '測量值',           'Mediciones',                'Mesures',                  'Messwerte',             'Medições',              'Giá trị đo',            'ค่าการวัด',               'Nilai pengukuran',      'قيم القياس',             1, datetime('now'), datetime('now')),
  ('i47-009', 'guardian.log.metric',    'guardian', '항목',              'Metric',                '項目',                 '指标',             '指標',             'Métrica',                   'Métrique',                 'Metrik',                'Métrica',               'Chỉ số',                'ตัวชี้วัด',               'Metrik',                'المقياس',                1, datetime('now'), datetime('now')),
  ('i47-010', 'guardian.log.value',     'guardian', '수치',              'Value',                 '数値',                 '数值',             '數值',             'Valor',                     'Valeur',                   'Wert',                  'Valor',                 'Giá trị',               'ค่า',                     'Nilai',                 'القيمة',                 1, datetime('now'), datetime('now')),
  ('i47-011', 'guardian.log.unit',      'guardian', '단위',              'Unit',                  '単位',                 '单位',             '單位',             'Unidad',                    'Unité',                    'Einheit',               'Unidade',               'Đơn vị',                'หน่วย',                   'Satuan',                'الوحدة',                 1, datetime('now'), datetime('now')),
  ('i47-012', 'guardian.log.save',      'guardian', '저장',              'Save',                  '保存',                 '保存',             '保存',             'Guardar',                   'Enregistrer',              'Speichern',             'Salvar',                'Lưu',                   'บันทึก',                  'Simpan',                'حفظ',                    1, datetime('now'), datetime('now')),
  ('i47-013', 'guardian.log.cancel',    'guardian', '취소',              'Cancel',                'キャンセル',           '取消',             '取消',             'Cancelar',                  'Annuler',                  'Abbrechen',             'Cancelar',              'Hủy',                   'ยกเลิก',                  'Batal',                 'إلغاء',                  1, datetime('now'), datetime('now')),
  ('i47-014', 'guardian.log.timeline',  'guardian', '타임라인',           'Timeline',             'タイムライン',          '时间线',           '時間線',           'Línea de tiempo',           'Chronologie',              'Zeitachse',             'Linha do tempo',        'Dòng thời gian',        'ไทม์ไลน์',                'Linimasa',              'الجدول الزمني',          1, datetime('now'), datetime('now')),
  ('i47-015', 'guardian.log.no_records','guardian', '기록이 없습니다',    'No records yet',       '記録がありません',      '暂无记录',         '暫無記錄',         'Sin registros',             'Aucun enregistrement',     'Keine Aufzeichnungen',  'Sem registros',         'Chưa có bản ghi',       'ยังไม่มีบันทึก',           'Belum ada catatan',     'لا توجد سجلات',          1, datetime('now'), datetime('now')),
  ('i47-016', 'guardian.log.edit',      'guardian', '수정',              'Edit',                  '編集',                 '编辑',             '編輯',             'Editar',                    'Modifier',                 'Bearbeiten',            'Editar',                'Sửa',                   'แก้ไข',                   'Edit',                  'تعديل',                  1, datetime('now'), datetime('now')),
  ('i47-017', 'guardian.log.delete',    'guardian', '삭제',              'Delete',                '削除',                 '删除',             '刪除',             'Eliminar',                  'Supprimer',                'Löschen',               'Excluir',               'Xóa',                   'ลบ',                      'Hapus',                 'حذف',                    1, datetime('now'), datetime('now')),
  ('i47-018', 'guardian.log.sync_offline','guardian','오프라인 동기화',   'Sync Offline',         'オフライン同期',        '离线同步',         '離線同步',         'Sincronizar offline',       'Synchroniser hors ligne',  'Offline synchronisieren','Sincronizar offline',  'Đồng bộ ngoại tuyến',   'ซิงค์แบบออฟไลน์',         'Sinkron offline',       'المزامنة دون اتصال',     1, datetime('now'), datetime('now')),
  ('i47-019', 'guardian.log.syncing',   'guardian', '동기화 중...',       'Syncing...',           '同期中...',            '同步中...',        '同步中...',        'Sincronizando...',          'Synchronisation...',       'Synchronisieren...',    'Sincronizando...',      'Đang đồng bộ...',       'กำลังซิงค์...',            'Menyinkronkan...',      'جارٍ المزامنة...',        1, datetime('now'), datetime('now')),

  -- ─── 혈당 경고 alert 키 ───────────────────────────────────────────────────
  ('i47-020', 'alert.low_glucose_critical', 'guardian', '긴급 저혈당 경고',   'Critical Low Glucose',   '緊急低血糖警告',    '紧急低血糖警告',   '緊急低血糖警告',   'Alerta crítica de hipoglucemia', 'Alerte hypoglycémie critique', 'Kritische Hypoglykämie', 'Alerta crítica de hipoglicemia', 'Cảnh báo hạ đường huyết khẩn cấp', 'แจ้งเตือนน้ำตาลต่ำวิกฤต',   'Peringatan hipoglikemia kritis', 'تحذير نقص السكر الحرج',  1, datetime('now'), datetime('now')),
  ('i47-021', 'alert.low_glucose_warning',  'guardian', '저혈당 주의',         'Low Glucose Warning',    '低血糖注意',        '低血糖注意',       '低血糖注意',       'Advertencia de hipoglucemia', 'Avertissement hypoglycémie',   'Hypoglykämie-Warnung',   'Aviso de hipoglicemia',          'Cảnh báo hạ đường huyết',          'เตือนน้ำตาลในเลือดต่ำ',     'Peringatan hipoglikemia',        'تحذير انخفاض السكر',     1, datetime('now'), datetime('now')),
  ('i47-022', 'alert.high_glucose_warning', 'guardian', '고혈당 주의',         'High Glucose Warning',   '高血糖注意',        '高血糖注意',       '高血糖注意',       'Advertencia de hiperglucemia', 'Avertissement hyperglycémie',  'Hyperglykämie-Warnung',  'Aviso de hiperglicemia',         'Cảnh báo tăng đường huyết',        'เตือนน้ำตาลในเลือดสูง',     'Peringatan hiperglikemia',       'تحذير ارتفاع السكر',     1, datetime('now'), datetime('now')),
  ('i47-023', 'alert.rapid_drop',           'guardian', '혈당 급락 경고',      'Rapid Glucose Drop',     '血糖急落警告',      '血糖急降警告',     '血糖急降警告',     'Caída rápida de glucosa',     'Chute rapide de glycémie',     'Schneller Glukoseabfall','Queda rápida de glicemia',       'Đường huyết giảm nhanh',           'เตือนน้ำตาลตกเร็ว',          'Penurunan glukosa cepat',        'انخفاض سريع في السكر',   1, datetime('now'), datetime('now')),

  -- ─── 로그 유형별 라벨 (guardian-web 드롭다운용) ──────────────────────────
  ('i47-024', 'guardian.log.blood_glucose', 'guardian', '혈당',        'Blood Glucose', '血糖',     '血糖',     '血糖',     'Glucosa en sangre', 'Glycémie',         'Blutzucker',      'Glicemia',          'Đường huyết',       'น้ำตาลในเลือด',  'Glukosa darah', 'سكر الدم',      1, datetime('now'), datetime('now')),
  ('i47-025', 'guardian.log.insulin',       'guardian', '인슐린',      'Insulin',       'インスリン', '胰岛素',   '胰島素',   'Insulina',          "Insuline",         'Insulin',         'Insulina',          'Insulin',           'อินซูลิน',        'Insulin',       'الأنسولين',     1, datetime('now'), datetime('now')),
  ('i47-026', 'guardian.log.meal',          'guardian', '식사',        'Meal',          '食事',      '饮食',     '飲食',     'Comida',            'Repas',            'Mahlzeit',        'Refeição',          'Bữa ăn',            'มื้ออาหาร',       'Makan',         'الوجبة',        1, datetime('now'), datetime('now')),
  ('i47-027', 'guardian.log.weight',        'guardian', '체중',        'Weight',        '体重',      '体重',     '體重',     'Peso',              'Poids',            'Gewicht',         'Peso',              'Cân nặng',          'น้ำหนัก',         'Berat badan',   'الوزن',         1, datetime('now'), datetime('now'));
