-- 0053_admin_feed_mgmt_i18n.sql
-- Admin feed catalog i18n keys

INSERT OR IGNORE INTO i18n_translations (
  id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at
) VALUES
  (lower(hex(randomblob(16))), 'admin.nav.feeds', 'admin', '사료 관리', 'Feed Management', '飼料管理', '饲料管理', '飼料管理', 'Gestión de Alimento', 'Gestion des aliments', 'Futterverwaltung', 'Gestão de Ração', 'Quản lý thức ăn', 'จัดการอาหารสัตว์', 'Manajemen Pakan', 'إدارة العلف', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.title', 'admin', '사료 관리', 'Feed Management', '飼料管理', '饲料管理', '飼料管理', 'Gestión de Alimento', 'Gestion des aliments', 'Futterverwaltung', 'Gestão de Ração', 'Quản lý thức ăn', 'จัดการอาหารสัตว์', 'Manajemen Pakan', 'إدارة العلف', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.guide', 'admin', '사료유형은 식단유형 L3(diet_feed_type) 마스터를 참조합니다.', 'Feed types reference Master Category L3 (diet_feed_type).', '飼料タイプはマスターカテゴリL3(diet_feed_type)を参照します。', '饲料类型引用主分类L3(diet_feed_type)。', '飼料類型引用主分類L3(diet_feed_type)。', 'El tipo de alimento referencia la categoría maestra L3 (diet_feed_type).', 'Le type d’aliment référence la catégorie maître L3 (diet_feed_type).', 'Der Futtertyp referenziert Master-Kategorie L3 (diet_feed_type).', 'O tipo de ração referencia a categoria mestre L3 (diet_feed_type).', 'Loại thức ăn tham chiếu danh mục master L3 (diet_feed_type).', 'ประเภทอาหารอ้างอิง Master Category L3 (diet_feed_type)', 'Tipe pakan mereferensikan Master Category L3 (diet_feed_type).', 'نوع العلف يرتبط بفئة الماستر L3 ‏(diet_feed_type).', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.types', 'admin', '사료유형 (L3)', 'Feed Type (L3)', '飼料タイプ (L3)', '饲料类型 (L3)', '飼料類型 (L3)', 'Tipo de Alimento (L3)', 'Type d’aliment (L3)', 'Futtertyp (L3)', 'Tipo de Ração (L3)', 'Loại thức ăn (L3)', 'ประเภทอาหาร (L3)', 'Jenis Pakan (L3)', 'نوع العلف (L3)', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.manufacturers', 'admin', '제조사', 'Manufacturers', 'メーカー', '制造商', '製造商', 'Fabricantes', 'Fabricants', 'Hersteller', 'Fabricantes', 'Nhà sản xuất', 'ผู้ผลิต', 'Produsen', 'المصنّعون', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.brands', 'admin', '브랜드', 'Brands', 'ブランド', '品牌', '品牌', 'Marcas', 'Marques', 'Marken', 'Marcas', 'Thương hiệu', 'แบรนด์', 'Merek', 'العلامات التجارية', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.models', 'admin', '사료모델', 'Feed Models', '飼料モデル', '饲料型号', '飼料型號', 'Modelos de Alimento', 'Modèles d’aliment', 'Futtermodelle', 'Modelos de Ração', 'Mẫu thức ăn', 'รุ่นอาหารสัตว์', 'Model Pakan', 'موديلات العلف', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.empty', 'admin', '데이터가 없습니다.', 'No data', 'データがありません', '暂无数据', '暫無資料', 'Sin datos', 'Aucune donnée', 'Keine Daten', 'Sem dados', 'Không có dữ liệu', 'ไม่มีข้อมูล', 'Tidak ada data', 'لا توجد بيانات', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.select_manufacturer', 'admin', '제조사를 먼저 선택하세요.', 'Select a manufacturer first.', '先にメーカーを選択してください。', '请先选择制造商。', '請先選擇製造商。', 'Seleccione primero un fabricante.', 'Sélectionnez d’abord un fabricant.', 'Wählen Sie zuerst einen Hersteller aus.', 'Selecione primeiro um fabricante.', 'Vui lòng chọn nhà sản xuất trước.', 'กรุณาเลือกผู้ผลิตก่อน', 'Pilih produsen terlebih dahulu.', 'اختر الشركة المصنعة أولاً.', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.select_type', 'admin', '사료유형을 먼저 선택하세요.', 'Select a feed type first.', '先に飼料タイプを選択してください。', '请先选择饲料类型。', '請先選擇飼料類型。', 'Seleccione primero un tipo de alimento.', 'Sélectionnez d’abord un type d’aliment.', 'Wählen Sie zuerst einen Futtertyp aus.', 'Selecione primeiro um tipo de ração.', 'Vui lòng chọn loại thức ăn trước.', 'กรุณาเลือกประเภทอาหารก่อน', 'Pilih tipe pakan terlebih dahulu.', 'اختر نوع العلف أولاً.', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.type', 'admin', '사료유형', 'Feed Type', '飼料タイプ', '饲料类型', '飼料類型', 'Tipo de Alimento', 'Type d’aliment', 'Futtertyp', 'Tipo de Ração', 'Loại thức ăn', 'ประเภทอาหาร', 'Jenis Pakan', 'نوع العلف', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.manufacturer', 'admin', '제조사', 'Manufacturer', 'メーカー', '制造商', '製造商', 'Fabricante', 'Fabricant', 'Hersteller', 'Fabricante', 'Nhà sản xuất', 'ผู้ผลิต', 'Produsen', 'المصنّع', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.brand', 'admin', '브랜드', 'Brand', 'ブランド', '品牌', '品牌', 'Marca', 'Marque', 'Marke', 'Marca', 'Thương hiệu', 'แบรนด์', 'Merek', 'العلامة التجارية', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.model_code', 'admin', '모델코드', 'Model Code', 'モデルコード', '型号代码', '型號代碼', 'Código del modelo', 'Code du modèle', 'Modellcode', 'Código do modelo', 'Mã mẫu', 'รหัสรุ่น', 'Kode Model', 'رمز الموديل', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.description', 'admin', '설명', 'Description', '説明', '说明', '說明', 'Descripción', 'Description', 'Beschreibung', 'Descrição', 'Mô tả', 'คำอธิบาย', 'Deskripsi', 'الوصف', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.name_ko', 'admin', '한국어 이름', 'Korean Name', '韓国語名', '韩文名称', '韓文名稱', 'Nombre en coreano', 'Nom coréen', 'Koreanischer Name', 'Nome em coreano', 'Tên tiếng Hàn', 'ชื่อภาษาเกาหลี', 'Nama Korea', 'الاسم الكوري', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.name_en', 'admin', '영어 이름', 'English Name', '英語名', '英文名称', '英文名稱', 'Nombre en inglés', 'Nom anglais', 'Englischer Name', 'Nome em inglês', 'Tên tiếng Anh', 'ชื่อภาษาอังกฤษ', 'Nama Inggris', 'الاسم الإنجليزي', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.feed.country', 'admin', '국가', 'Country', '国', '国家', '國家', 'País', 'Pays', 'Land', 'País', 'Quốc gia', 'ประเทศ', 'Negara', 'الدولة', 1, datetime('now'), datetime('now'));
