-- 0066: i18n keys for pet feed management UI + nutrition labels + correlation chart

-- Guardian feed management
INSERT OR IGNORE INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at)
VALUES
  ('i18n_feed_mgmt_title',    'guardian.feed.manage_title',    'guardian', '사료 관리',        'Feed Management',     '飼料管理',         '饲料管理',        '飼料管理',        'Gestión de alimento', 'Gestion de l''alimentation', 'Futterverwaltung', 'Gestão de ração', 'Quản lý thức ăn', 'จัดการอาหาร', 'Manajemen Pakan', 'إدارة العلف', 1, datetime('now'), datetime('now')),
  ('i18n_feed_mgmt_add',      'guardian.feed.add',             'guardian', '사료 추가',        'Add Feed',            '飼料追加',         '添加饲料',        '新增飼料',        'Agregar alimento',    'Ajouter un aliment',         'Futter hinzufügen', 'Adicionar ração', 'Thêm thức ăn',    'เพิ่มอาหาร',  'Tambah Pakan',    'إضافة علف',   1, datetime('now'), datetime('now')),
  ('i18n_feed_mgmt_edit',     'guardian.feed.edit',            'guardian', '사료 수정',        'Edit Feed',           '飼料編集',         '编辑饲料',        '編輯飼料',        'Editar alimento',     'Modifier l''aliment',        'Futter bearbeiten', 'Editar ração',   'Sửa thức ăn',     'แก้ไขอาหาร',  'Edit Pakan',      'تعديل العلف', 1, datetime('now'), datetime('now')),
  ('i18n_feed_mgmt_no',       'guardian.feed.no_feeds',        'guardian', '등록된 사료가 없습니다', 'No feeds registered', '登録された飼料がありません', '暂无注册饲料', '尚無註冊飼料', 'No hay alimentos registrados', 'Aucun aliment enregistré', 'Kein Futter registriert', 'Nenhuma ração registrada', 'Chưa có thức ăn nào', 'ยังไม่มีอาหารที่ลงทะเบียน', 'Belum ada pakan terdaftar', 'لا يوجد علف مسجل', 1, datetime('now'), datetime('now')),
  ('i18n_feed_mgmt_primary',  'guardian.feed.is_primary',      'guardian', '기본 사료',        'Primary Feed',        'メインフード',     '主食',            '主食',            'Alimento principal',  'Aliment principal',          'Hauptfutter',       'Ração principal', 'Thức ăn chính',   'อาหารหลัก',    'Pakan Utama',     'العلف الرئيسي', 1, datetime('now'), datetime('now')),
  ('i18n_feed_mgmt_set_pri',  'guardian.feed.set_primary',     'guardian', '기본 설정',        'Set Primary',         '基本設定',         '设为主食',        '設為主食',        'Establecer como principal', 'Définir comme principal', 'Als Hauptfutter festlegen', 'Definir como principal', 'Đặt làm chính', 'ตั้งเป็นหลัก', 'Jadikan Utama',   'تعيين كرئيسي', 1, datetime('now'), datetime('now')),
  ('i18n_feed_mgmt_del',      'guardian.feed.delete_confirm',  'guardian', '이 사료를 삭제하시겠습니까?', 'Delete this feed?', 'この飼料を削除しますか？', '确定删除此饲料？', '確定刪除此飼料？', '¿Eliminar este alimento?', 'Supprimer cet aliment ?', 'Dieses Futter löschen?', 'Excluir esta ração?', 'Xóa thức ăn này?', 'ลบอาหารนี้?', 'Hapus pakan ini?', 'حذف هذا العلف؟', 1, datetime('now'), datetime('now')),
  ('i18n_feed_mgmt_daily',    'guardian.feed.daily_amount',    'guardian', '일일 급여량',      'Daily Amount',        '1日の給餌量',      '每日喂食量',      '每日餵食量',      'Cantidad diaria',     'Quantité quotidienne',       'Tägliche Menge',    'Quantidade diária', 'Lượng hàng ngày', 'ปริมาณต่อวัน', 'Jumlah Harian',   'الكمية اليومية', 1, datetime('now'), datetime('now')),
  ('i18n_feed_mgmt_freq',     'guardian.feed.feeding_frequency','guardian', '급여 횟수/일',    'Feedings/Day',        '給餌回数/日',      '每日喂食次数',    '每日餵食次數',    'Veces/día',           'Repas/jour',                 'Fütterungen/Tag',   'Refeições/dia', 'Bữa/ngày',        'มื้อ/วัน',     'Kali/hari',       'مرات/يوم', 1, datetime('now'), datetime('now')),
  ('i18n_feed_mgmt_start',    'guardian.feed.start_date',      'guardian', '시작일',           'Start Date',          '開始日',           '开始日期',        '開始日期',        'Fecha de inicio',     'Date de début',              'Startdatum',        'Data de início', 'Ngày bắt đầu',    'วันเริ่มต้น',  'Tanggal Mulai',   'تاريخ البدء', 1, datetime('now'), datetime('now')),
  ('i18n_feed_mgmt_end',      'guardian.feed.end_date',        'guardian', '종료일',           'End Date',            '終了日',           '结束日期',        '結束日期',        'Fecha de fin',        'Date de fin',                'Enddatum',          'Data de término', 'Ngày kết thúc',   'วันสิ้นสุด',   'Tanggal Selesai', 'تاريخ الانتهاء', 1, datetime('now'), datetime('now')),
  ('i18n_feed_mgmt_nick',     'guardian.feed.nickname',        'guardian', '별명',             'Nickname',            'ニックネーム',     '昵称',            '暱稱',            'Apodo',               'Surnom',                     'Spitzname',         'Apelido',        'Biệt danh',       'ชื่อเล่น',     'Nama Panggilan',  'الاسم المستعار', 1, datetime('now'), datetime('now')),
  ('i18n_feed_mgmt_nick_ph',  'guardian.feed.nickname_placeholder', 'guardian', '예: 방울이 처방식', 'e.g. Bella''s Prescription', '例: ベラの処方食', '例：贝拉处方粮', '例：貝拉處方糧', 'ej. Dieta de Bella', 'ex. Régime de Bella', 'z.B. Bellas Diätfutter', 'ex. Dieta da Bella', 'VD: Thức ăn Bella', 'เช่น อาหารเบลล่า', 'cth. Diet Bella', 'مثال: طعام بيلا', 1, datetime('now'), datetime('now')),
  ('i18n_feed_mgmt_model_req','guardian.feed.model_required',  'guardian', '사료 제품을 선택해주세요', 'Please select a feed product', '飼料製品を選択してください', '请选择饲料产品', '請選擇飼料產品', 'Seleccione un producto', 'Veuillez sélectionner un produit', 'Bitte wählen Sie ein Produkt', 'Selecione um produto', 'Vui lòng chọn sản phẩm', 'กรุณาเลือกผลิตภัณฑ์', 'Silakan pilih produk', 'يرجى اختيار المنتج', 1, datetime('now'), datetime('now'));

-- Nutrition labels
INSERT OR IGNORE INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at)
VALUES
  ('i18n_nutr_title',     'nutrition.title',           'feed', '영양 정보',      'Nutrition Info',     '栄養情報',       '营养信息',      '營養資訊',      'Info nutricional',  'Info nutritionnelle',  'Nährwertinfo',      'Info nutricional', 'Thông tin dinh dưỡng', 'ข้อมูลโภชนาการ', 'Info Nutrisi',     'معلومات غذائية', 1, datetime('now'), datetime('now')),
  ('i18n_nutr_cal',       'nutrition.calories',        'feed', '칼로리 (100g당)', 'Calories/100g',     'カロリー(100g当)', '热量(每100g)',  '熱量(每100g)',  'Calorías/100g',     'Calories/100g',        'Kalorien/100g',     'Calorias/100g',   'Calo/100g',            'แคลอรี่/100ก.',  'Kalori/100g',      'سعرات/100غ',     1, datetime('now'), datetime('now')),
  ('i18n_nutr_protein',   'nutrition.protein',         'feed', '단백질 (%)',      'Protein (%)',       'タンパク質(%)',   '蛋白质(%)',     '蛋白質(%)',     'Proteína (%)',      'Protéines (%)',        'Protein (%)',       'Proteína (%)',    'Protein (%)',          'โปรตีน (%)',     'Protein (%)',      'بروتين (%)',     1, datetime('now'), datetime('now')),
  ('i18n_nutr_fat',       'nutrition.fat',             'feed', '지방 (%)',        'Fat (%)',           '脂肪(%)',        '脂肪(%)',       '脂肪(%)',       'Grasa (%)',         'Matières grasses (%)', 'Fett (%)',          'Gordura (%)',     'Chất béo (%)',         'ไขมัน (%)',      'Lemak (%)',        'دهون (%)',       1, datetime('now'), datetime('now')),
  ('i18n_nutr_fiber',     'nutrition.fiber',           'feed', '식이섬유 (%)',    'Fiber (%)',         '食物繊維(%)',     '纤维(%)',       '纖維(%)',       'Fibra (%)',         'Fibres (%)',           'Ballaststoffe (%)', 'Fibra (%)',       'Chất xơ (%)',          'เส้นใย (%)',     'Serat (%)',        'ألياف (%)',      1, datetime('now'), datetime('now')),
  ('i18n_nutr_moisture',  'nutrition.moisture',        'feed', '수분 (%)',        'Moisture (%)',      '水分(%)',        '水分(%)',       '水分(%)',       'Humedad (%)',       'Humidité (%)',         'Feuchtigkeit (%)', 'Umidade (%)',     'Độ ẩm (%)',            'ความชื้น (%)',   'Kelembapan (%)',   'رطوبة (%)',      1, datetime('now'), datetime('now')),
  ('i18n_nutr_ash',       'nutrition.ash',             'feed', '조회분 (%)',      'Ash (%)',           '灰分(%)',        '灰分(%)',       '灰分(%)',       'Ceniza (%)',        'Cendres (%)',          'Asche (%)',         'Cinzas (%)',      'Tro (%)',              'เถ้า (%)',       'Abu (%)',          'رماد (%)',       1, datetime('now'), datetime('now')),
  ('i18n_nutr_calcium',   'nutrition.calcium',         'feed', '칼슘 (%)',        'Calcium (%)',       'カルシウム(%)',   '钙(%)',         '鈣(%)',         'Calcio (%)',        'Calcium (%)',          'Kalzium (%)',       'Cálcio (%)',      'Canxi (%)',            'แคลเซียม (%)',   'Kalsium (%)',      'كالسيوم (%)',    1, datetime('now'), datetime('now')),
  ('i18n_nutr_phosphorus','nutrition.phosphorus',      'feed', '인 (%)',          'Phosphorus (%)',    'リン(%)',        '磷(%)',         '磷(%)',         'Fósforo (%)',       'Phosphore (%)',        'Phosphor (%)',      'Fósforo (%)',     'Phốt-pho (%)',         'ฟอสฟอรัส (%)',   'Fosfor (%)',       'فوسفور (%)',     1, datetime('now'), datetime('now')),
  ('i18n_nutr_omega3',    'nutrition.omega3',          'feed', '오메가3 (%)',     'Omega-3 (%)',       'オメガ3(%)',     'Omega-3(%)',    'Omega-3(%)',    'Omega-3 (%)',       'Oméga-3 (%)',          'Omega-3 (%)',       'Ômega-3 (%)',     'Omega-3 (%)',          'โอเมก้า-3 (%)',  'Omega-3 (%)',      'أوميغا-3 (%)',   1, datetime('now'), datetime('now')),
  ('i18n_nutr_omega6',    'nutrition.omega6',          'feed', '오메가6 (%)',     'Omega-6 (%)',       'オメガ6(%)',     'Omega-6(%)',    'Omega-6(%)',    'Omega-6 (%)',       'Oméga-6 (%)',          'Omega-6 (%)',       'Ômega-6 (%)',     'Omega-6 (%)',          'โอเมก้า-6 (%)',  'Omega-6 (%)',      'أوميغا-6 (%)',   1, datetime('now'), datetime('now')),
  ('i18n_nutr_carb',      'nutrition.carbohydrate',    'feed', '탄수화물 (%)',    'Carbohydrate (%)',  '炭水化物(%)',    '碳水化合物(%)', '碳水化合物(%)', 'Carbohidrato (%)',  'Glucides (%)',         'Kohlenhydrate (%)', 'Carboidrato (%)', 'Carbohydrate (%)',     'คาร์บ (%)',      'Karbohidrat (%)',  'كربوهيدرات (%)', 1, datetime('now'), datetime('now')),
  ('i18n_nutr_serving',   'nutrition.serving_size',    'feed', '1회 급여량 (g)',  'Serving Size (g)',  '1回の給餌量(g)', '每次喂食量(g)', '每次餵食量(g)', 'Porción (g)',       'Portion (g)',          'Portionsgröße (g)','Porção (g)',      'Khẩu phần (g)',        'ขนาด (ก.)',      'Porsi (g)',        'الحصة (غ)',      1, datetime('now'), datetime('now')),
  ('i18n_nutr_ingredients','nutrition.ingredients',    'feed', '성분',            'Ingredients',       '成分',           '成分',          '成分',          'Ingredientes',      'Ingrédients',          'Zutaten',           'Ingredientes',    'Thành phần',           'ส่วนผสม',        'Bahan',            'المكونات',       1, datetime('now'), datetime('now')),
  ('i18n_nutr_save',      'nutrition.save_success',    'feed', '영양 정보가 저장되었습니다', 'Nutrition info saved', '栄養情報を保存しました', '营养信息已保存', '營養資訊已儲存', 'Info nutricional guardada', 'Info nutritionnelle enregistrée', 'Nährwertinfo gespeichert', 'Info nutricional salva', 'Đã lưu thông tin dinh dưỡng', 'บันทึกข้อมูลโภชนาการแล้ว', 'Info nutrisi disimpan', 'تم حفظ المعلومات الغذائية', 1, datetime('now'), datetime('now'));

-- Chart feed timeline
INSERT OR IGNORE INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at)
VALUES
  ('i18n_chart_feed_legend', 'guardian.health.chart_feed_legend', 'guardian', '사료',    'Feed',   '飼料',   '饲料',  '飼料',  'Alimento', 'Aliment', 'Futter', 'Ração', 'Thức ăn', 'อาหาร', 'Pakan', 'علف', 1, datetime('now'), datetime('now')),
  ('i18n_chart_weight_legend','guardian.health.chart_weight_legend','guardian','체중',    'Weight', '体重',   '体重',  '體重',  'Peso',     'Poids',   'Gewicht','Peso',  'Cân nặng','น้ำหนัก','Berat', 'الوزن', 1, datetime('now'), datetime('now')),
  ('i18n_chart_measure_legend','guardian.health.chart_measure_legend','guardian','측정값', 'Measurement','測定値','测量值','測量值','Medición','Mesure','Messwert','Medição','Đo lường','ค่าวัด','Pengukuran','قياس', 1, datetime('now'), datetime('now'));
