-- 0069: i18n keys for pet feeding log UI

INSERT OR IGNORE INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at)
VALUES
  ('i18n_flog_title',     'guardian.feeding.log_title',          'guardian', '급여 기록',              'Feeding Log',              '給餌記録',             '喂食记录',          '餵食記錄',          'Registro de alimentación', 'Journal d''alimentation',     'Fütterungsprotokoll',    'Registro de alimentação', 'Nhật ký cho ăn',         'บันทึกการให้อาหาร',   'Log Pemberian Makan',  'سجل التغذية',           1, datetime('now'), datetime('now')),
  ('i18n_flog_add',       'guardian.feeding.add',                'guardian', '급여 기록 추가',         'Add Feeding Log',          '給餌記録追加',          '添加喂食记录',       '新增餵食記錄',       'Agregar registro',          'Ajouter un enregistrement',   'Eintrag hinzufügen',     'Adicionar registro',      'Thêm nhật ký',           'เพิ่มบันทึก',          'Tambah Log',           'إضافة سجل',             1, datetime('now'), datetime('now')),
  ('i18n_flog_select',    'guardian.feeding.select_feed',        'guardian', '사료 선택',              'Select Feed',              '飼料を選択',           '选择饲料',          '選擇飼料',          'Seleccionar alimento',      'Sélectionner l''aliment',     'Futter auswählen',       'Selecionar ração',        'Chọn thức ăn',           'เลือกอาหาร',           'Pilih Pakan',          'اختر العلف',            1, datetime('now'), datetime('now')),
  ('i18n_flog_amount',    'guardian.feeding.amount',             'guardian', '급여량 (g)',             'Amount (g)',               '給餌量 (g)',            '喂食量 (g)',         '餵食量 (g)',         'Cantidad (g)',              'Quantité (g)',                'Menge (g)',              'Quantidade (g)',          'Lượng (g)',              'ปริมาณ (ก.)',           'Jumlah (g)',           'الكمية (غ)',            1, datetime('now'), datetime('now')),
  ('i18n_flog_freq',      'guardian.feeding.frequency',          'guardian', '급여 횟수/일',           'Feedings/Day',             '給餌回数/日',          '每日喂食次数',       '每日餵食次數',       'Veces/día',                 'Repas/jour',                  'Fütterungen/Tag',        'Refeições/dia',           'Bữa/ngày',              'มื้อ/วัน',              'Kali/hari',            'مرات/يوم',              1, datetime('now'), datetime('now')),
  ('i18n_flog_time',      'guardian.feeding.time',               'guardian', '급여 시간',              'Feeding Time',             '給餌時間',             '喂食时间',          '餵食時間',          'Hora de alimentación',      'Heure du repas',              'Fütterungszeit',         'Hora da refeição',        'Giờ cho ăn',             'เวลาให้อาหาร',          'Waktu Makan',          'وقت التغذية',           1, datetime('now'), datetime('now')),
  ('i18n_flog_memo',      'guardian.feeding.memo',               'guardian', '메모',                  'Memo',                     'メモ',                '备注',              '備註',              'Nota',                      'Note',                        'Notiz',                  'Nota',                    'Ghi chú',                'บันทึก',                'Catatan',              'ملاحظة',                1, datetime('now'), datetime('now')),
  ('i18n_flog_no_feeds',  'guardian.feeding.no_feeds_registered','guardian', '등록된 사료가 없습니다', 'No feeds registered',      '登録された飼料がありません', '暂无注册饲料', '尚無註冊飼料', 'No hay alimentos registrados', 'Aucun aliment enregistré', 'Kein Futter registriert', 'Nenhuma ração registrada', 'Chưa có thức ăn nào', 'ยังไม่มีอาหารที่ลงทะเบียน', 'Belum ada pakan terdaftar', 'لا يوجد علف مسجل', 1, datetime('now'), datetime('now')),
  ('i18n_flog_save',      'guardian.feeding.save',               'guardian', '저장',                  'Save',                     '保存',                '保存',              '儲存',              'Guardar',                   'Enregistrer',                 'Speichern',              'Salvar',                  'Lưu',                    'บันทึก',                'Simpan',               'حفظ',                   1, datetime('now'), datetime('now')),
  ('i18n_flog_edit',      'guardian.feeding.edit',               'guardian', '수정',                  'Edit',                     '編集',                '编辑',              '編輯',              'Editar',                    'Modifier',                    'Bearbeiten',             'Editar',                  'Sửa',                    'แก้ไข',                 'Edit',                 'تعديل',                 1, datetime('now'), datetime('now')),
  ('i18n_flog_del',       'guardian.feeding.delete_confirm',     'guardian', '삭제하시겠습니까?',     'Delete this record?',      'この記録を削除しますか？', '确定删除此记录？', '確定刪除此記錄？', '¿Eliminar este registro?', 'Supprimer cet enregistrement ?', 'Diesen Eintrag löschen?', 'Excluir este registro?', 'Xóa bản ghi này?',   'ลบบันทึกนี้?',          'Hapus catatan ini?',   'حذف هذا السجل؟',       1, datetime('now'), datetime('now')),
  ('i18n_flog_no_logs',   'guardian.feeding.no_logs',            'guardian', '급여 기록이 없습니다',   'No feeding logs yet',      'まだ給餌記録がありません', '暂无喂食记录', '尚無餵食記錄', 'Aún no hay registros', 'Aucun enregistrement pour le moment', 'Noch keine Einträge', 'Nenhum registro ainda', 'Chưa có nhật ký nào', 'ยังไม่มีบันทึก',       'Belum ada log',        'لا توجد سجلات بعد',    1, datetime('now'), datetime('now'));
