INSERT OR IGNORE INTO i18n_translations (
  id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at
) VALUES
  (lower(hex(randomblob(16))), 'public.signup.provider_pet_l1', 'public', '펫종류 L1', 'Pet Type L1', 'ペット種別 L1', '宠物类型 L1', '寵物類型 L1', 'Tipo de mascota L1', 'Type d animal L1', 'Haustierart L1', 'Tipo de pet L1', 'Loại thú cưng L1', 'ประเภทสัตว์เลี้ยง L1', 'Jenis hewan L1', 'نوع الحيوان الأليف L1', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'public.signup.provider_pet_l2', 'public', '펫종류 L2', 'Pet Type L2', 'ペット種別 L2', '宠物类型 L2', '寵物類型 L2', 'Tipo de mascota L2', 'Type d animal L2', 'Haustierart L2', 'Tipo de pet L2', 'Loại thú cưng L2', 'ประเภทสัตว์เลี้ยง L2', 'Jenis hewan L2', 'نوع الحيوان الأليف L2', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'public.signup.provider_l3', 'public', '작업 스타일', 'Work Style', '作業スタイル', '工作风格', '工作風格', 'Estilo de trabajo', 'Style de travail', 'Arbeitsstil', 'Estilo de trabalho', 'Phong cach dich vu', 'รูปแบบการให้บริการ', 'Gaya layanan', 'نمط الخدمة', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.members.col.pet_l1', 'admin', '펫종류 L1', 'Pet Type L1', 'ペット種別 L1', '宠物类型 L1', '寵物類型 L1', 'Tipo de mascota L1', 'Type d animal L1', 'Haustierart L1', 'Tipo de pet L1', 'Loại thú cưng L1', 'ประเภทสัตว์เลี้ยง L1', 'Jenis hewan L1', 'نوع الحيوان الأليف L1', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.members.col.pet_l2', 'admin', '펫종류 L2', 'Pet Type L2', 'ペット種別 L2', '宠物类型 L2', '寵物類型 L2', 'Tipo de mascota L2', 'Type d animal L2', 'Haustierart L2', 'Tipo de pet L2', 'Loại thú cưng L2', 'ประเภทสัตว์เลี้ยง L2', 'Jenis hewan L2', 'نوع الحيوان الأليف L2', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.members.col.category_l3', 'admin', '작업 스타일', 'Work Style', '作業スタイル', '工作风格', '工作風格', 'Estilo de trabajo', 'Style de travail', 'Arbeitsstil', 'Estilo de trabalho', 'Phong cach dich vu', 'รูปแบบการให้บริการ', 'Gaya layanan', 'نمط الخدمة', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.members.field.pet_l1', 'admin', '펫종류 L1', 'Pet Type L1', 'ペット種別 L1', '宠物类型 L1', '寵物類型 L1', 'Tipo de mascota L1', 'Type d animal L1', 'Haustierart L1', 'Tipo de pet L1', 'Loại thú cưng L1', 'ประเภทสัตว์เลี้ยง L1', 'Jenis hewan L1', 'نوع الحيوان الأليف L1', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.members.field.pet_l2', 'admin', '펫종류 L2', 'Pet Type L2', 'ペット種別 L2', '宠物类型 L2', '寵物類型 L2', 'Tipo de mascota L2', 'Type d animal L2', 'Haustierart L2', 'Tipo de pet L2', 'Loại thú cưng L2', 'ประเภทสัตว์เลี้ยง L2', 'Jenis hewan L2', 'نوع الحيوان الأليف L2', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'admin.members.field.business_l3', 'admin', '작업 스타일', 'Work Style', '作業スタイル', '工作风格', '工作風格', 'Estilo de trabajo', 'Style de travail', 'Arbeitsstil', 'Estilo de trabalho', 'Phong cach dich vu', 'รูปแบบการให้บริการ', 'Gaya layanan', 'نمط الخدمة', 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO schema_migrations (version) VALUES ('0081_business_style_i18n');
