-- Pet modal immutable field + microchip UX i18n
INSERT OR IGNORE INTO i18n_translations (
  id, key, page,
  ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar,
  is_active, created_at, updated_at
) VALUES
  (lower(hex(randomblob(16))), 'guardian.pet_form.name_locked_help', 'guardian', '이름은 등록 후 변경할 수 없습니다.', 'Name cannot be changed after registration.', '名前は登録後に変更できません。', '名称在注册后无法更改。', '名稱在註冊後無法變更。', 'El nombre no se puede cambiar despues del registro.', 'Le nom ne peut pas etre modifie apres l inscription.', 'Der Name kann nach der Registrierung nicht mehr geaendert werden.', 'O nome nao pode ser alterado apos o cadastro.', 'Ten khong the thay doi sau khi dang ky.', 'ไม่สามารถเปลี่ยนชื่อได้หลังจากลงทะเบียนแล้ว', 'Nama tidak dapat diubah setelah pendaftaran.', 'لا يمكن تغيير الاسم بعد التسجيل.', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'guardian.pet_form.pet_type_locked_help', 'guardian', '펫종류는 등록 후 변경할 수 없습니다.', 'Pet type cannot be changed after registration.', 'ペット種類は登録後に変更できません。', '宠物类型在注册后无法更改。', '寵物類型在註冊後無法變更。', 'El tipo de mascota no se puede cambiar despues del registro.', 'Le type d animal ne peut pas etre modifie apres l inscription.', 'Die Tierart kann nach der Registrierung nicht mehr geaendert werden.', 'O tipo de pet nao pode ser alterado apos o cadastro.', 'Loai thu cung khong the thay doi sau khi dang ky.', 'ไม่สามารถเปลี่ยนประเภทสัตว์เลี้ยงได้หลังจากลงทะเบียนแล้ว', 'Jenis hewan tidak dapat diubah setelah pendaftaran.', 'لا يمكن تغيير نوع الحيوان الأليف بعد التسجيل.', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'guardian.pet_form.breed_locked_help', 'guardian', '품종은 등록 후 변경할 수 없습니다.', 'Breed cannot be changed after registration.', '品種は登録後に変更できません。', '品种在注册后无法更改。', '品種在註冊後無法變更。', 'La raza no se puede cambiar despues del registro.', 'La race ne peut pas etre modifiee apres l inscription.', 'Die Rasse kann nach der Registrierung nicht mehr geaendert werden.', 'A raca nao pode ser alterada apos o cadastro.', 'Giong loai khong the thay doi sau khi dang ky.', 'ไม่สามารถเปลี่ยนสายพันธุ์ได้หลังจากลงทะเบียนแล้ว', 'Ras tidak dapat diubah setelah pendaftaran.', 'لا يمكن تغيير السلالة بعد التسجيل.', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'guardian.pet_form.gender_locked_help', 'guardian', '성별은 등록 후 변경할 수 없습니다.', 'Gender cannot be changed after registration.', '性別は登録後に変更できません。', '性别在注册后无法更改。', '性別在註冊後無法變更。', 'El genero no se puede cambiar despues del registro.', 'Le sexe ne peut pas etre modifie apres l inscription.', 'Das Geschlecht kann nach der Registrierung nicht mehr geaendert werden.', 'O genero nao pode ser alterado apos o cadastro.', 'Gioi tinh khong the thay doi sau khi dang ky.', 'ไม่สามารถเปลี่ยนเพศได้หลังจากลงทะเบียนแล้ว', 'Jenis kelamin tidak dapat diubah setelah pendaftaran.', 'لا يمكن تغيير الجنس بعد التسجيل.', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'guardian.pet_form.microchip_check', 'guardian', '중복 확인', 'Check', '重複確認', '检查', '檢查', 'Verificar', 'Verifier', 'Prufen', 'Verificar', 'Kiem tra', 'ตรวจสอบ', 'Periksa', 'تحقق', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'guardian.pet_form.microchip_checking', 'guardian', '확인 중...', 'Checking...', '確認中...', '检查中...', '檢查中...', 'Verificando...', 'Verification...', 'Wird gepruft...', 'Verificando...', 'Dang kiem tra...', 'กําลังตรวจสอบ...', 'Memeriksa...', 'جارٍ التحقق...', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'guardian.pet_form.microchip_available', 'guardian', '등록 가능한 번호입니다.', 'This number is available for registration.', '登録可能な番号です。', '这是可注册的号码。', '這是可註冊的號碼。', 'Este numero esta disponible para registro.', 'Ce numero est disponible pour l inscription.', 'Diese Nummer ist zur Registrierung verfugbar.', 'Este numero esta disponivel para cadastro.', 'So nay co the dang ky.', 'หมายเลขนี้สามารถลงทะเบียนได้', 'Nomor ini tersedia untuk pendaftaran.', 'هذا الرقم متاح للتسجيل.', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'guardian.pet_form.microchip_unknown', 'guardian', '모름', 'I do not know', 'わかりません', '不知道', '不知道', 'No lo se', 'Je ne sais pas', 'Ich weiss es nicht', 'Nao sei', 'Toi khong biet', 'ไม่ทราบ', 'Saya tidak tahu', 'لا أعرف', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'guardian.pet_form.microchip_placeholder', 'guardian', '마이크로칩 번호를 입력하세요', 'Enter microchip number', 'マイクロチップ番号を入力してください', '请输入芯片号码', '請輸入晶片號碼', 'Introduce el numero de microchip', 'Saisissez le numero de micropuce', 'Geben Sie die Mikrochip-Nummer ein', 'Digite o numero do microchip', 'Nhap so microchip', 'กรอกหมายเลขไมโครชิป', 'Masukkan nomor microchip', 'أدخل رقم الشريحة', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'guardian.pet_form.microchip_country_code', 'guardian', '국가 코드', 'Country code', '国コード', '国家代码', '國家代碼', 'Codigo de pais', 'Code pays', 'Landercode', 'Codigo do pais', 'Ma quoc gia', 'รหัสประเทศ', 'Kode negara', 'رمز الدولة', 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(16))), 'guardian.alert.current_weight_invalid', 'guardian', '현재 체중은 올바른 숫자여야 합니다.', 'Current weight must be a valid number.', '現在の体重は有効な数値である必要があります。', '当前体重必须是有效数字。', '目前體重必須是有效數字。', 'El peso actual debe ser un numero valido.', 'Le poids actuel doit etre un nombre valide.', 'Das aktuelle Gewicht muss eine gueltige Zahl sein.', 'O peso atual deve ser um numero valido.', 'Can nang hien tai phai la mot so hop le.', 'น้ำหนักปัจจุบันต้องเป็นตัวเลขที่ถูกต้อง', 'Berat saat ini harus berupa angka yang valid.', 'يجب أن يكون الوزن الحالي رقماً صالحاً.', 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO schema_migrations (version) VALUES ('0086_pet_microchip_guardian_i18n');
