-- =============================================================================
-- 008_booking_i18n.sql — i18n keys for booking system v2
-- =============================================================================
-- ~130 keys × 13 languages
-- Covers: appointment status, booking steps, grooming completion, review system,
--         supplier settings, business-type specific fields
-- All statements idempotent (ON CONFLICT DO NOTHING)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Appointment status & actions
-- ---------------------------------------------------------------------------
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'appointment.status.pending', 'booking', '대기 중', 'Pending', '保留中', '待处理', '待處理', 'Pendiente', 'En attente', 'Ausstehend', 'Pendente', 'Đang chờ', 'รอดำเนินการ', 'Menunggu', 'قيد الانتظار') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'appointment.status.confirmed', 'booking', '확정', 'Confirmed', '確定', '已确认', '已確認', 'Confirmado', 'Confirmé', 'Bestätigt', 'Confirmado', 'Đã xác nhận', 'ยืนยันแล้ว', 'Dikonfirmasi', 'مؤكد') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'appointment.status.rejected', 'booking', '거절됨', 'Rejected', '拒否', '已拒绝', '已拒絕', 'Rechazado', 'Refusé', 'Abgelehnt', 'Rejeitado', 'Đã từ chối', 'ถูกปฏิเสธ', 'Ditolak', 'مرفوض') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'appointment.status.completed', 'booking', '완료', 'Completed', '完了', '已完成', '已完成', 'Completado', 'Terminé', 'Abgeschlossen', 'Concluído', 'Đã hoàn thành', 'เสร็จสิ้น', 'Selesai', 'مكتمل') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'appointment.status.cancelled', 'booking', '취소됨', 'Cancelled', 'キャンセル', '已取消', '已取消', 'Cancelado', 'Annulé', 'Storniert', 'Cancelado', 'Đã hủy', 'ถูกยกเลิก', 'Dibatalkan', 'ملغي') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'appointment.action.confirm', 'booking', '수락', 'Accept', '承認', '接受', '接受', 'Aceptar', 'Accepter', 'Akzeptieren', 'Aceitar', 'Chấp nhận', 'ยอมรับ', 'Terima', 'قبول') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'appointment.action.reject', 'booking', '거절', 'Reject', '拒否', '拒绝', '拒絕', 'Rechazar', 'Refuser', 'Ablehnen', 'Rejeitar', 'Từ chối', 'ปฏิเสธ', 'Tolak', 'رفض') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'appointment.action.cancel', 'booking', '예약 취소', 'Cancel Booking', '予約キャンセル', '取消预约', '取消預約', 'Cancelar reserva', 'Annuler la réservation', 'Buchung stornieren', 'Cancelar reserva', 'Hủy đặt lịch', 'ยกเลิกการจอง', 'Batalkan Pemesanan', 'إلغاء الحجز') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'appointment.action.complete', 'booking', '완료 처리', 'Mark Complete', '完了にする', '标记完成', '標記完成', 'Marcar como completado', 'Marquer comme terminé', 'Als abgeschlossen markieren', 'Marcar como concluído', 'Đánh dấu hoàn thành', 'ทำเครื่องหมายเสร็จสิ้น', 'Tandai Selesai', 'وضع علامة مكتمل') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'appointment.cancel.reason_label', 'booking', '취소 사유', 'Cancellation Reason', 'キャンセル理由', '取消原因', '取消原因', 'Motivo de cancelación', 'Motif d''annulation', 'Stornierungsgrund', 'Motivo do cancelamento', 'Lý do hủy', 'เหตุผลในการยกเลิก', 'Alasan Pembatalan', 'سبب الإلغاء') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'appointment.cancel.reason_placeholder', 'booking', '취소 사유를 입력해주세요 (선택)', 'Enter cancellation reason (optional)', 'キャンセル理由を入力してください（任意）', '请输入取消原因（可选）', '請輸入取消原因（選填）', 'Introduzca el motivo (opcional)', 'Saisissez le motif (facultatif)', 'Geben Sie den Grund ein (optional)', 'Digite o motivo (opcional)', 'Nhập lý do (tùy chọn)', 'กรอกเหตุผล (ไม่บังคับ)', 'Masukkan alasan (opsional)', 'أدخل السبب (اختياري)') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'appointment.cancel.success', 'booking', '예약이 취소되었습니다', 'Booking has been cancelled', '予約がキャンセルされました', '预约已取消', '預約已取消', 'La reserva ha sido cancelada', 'La réservation a été annulée', 'Die Buchung wurde storniert', 'A reserva foi cancelada', 'Đã hủy đặt lịch', 'การจองถูกยกเลิกแล้ว', 'Pemesanan telah dibatalkan', 'تم إلغاء الحجز') ON CONFLICT (key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. Booking steps & labels
-- ---------------------------------------------------------------------------
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.step.service', 'booking', '서비스 선택', 'Select Service', 'サービス選択', '选择服务', '選擇服務', 'Seleccionar servicio', 'Sélectionner le service', 'Service auswählen', 'Selecionar serviço', 'Chọn dịch vụ', 'เลือกบริการ', 'Pilih Layanan', 'اختيار الخدمة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.step.pet', 'booking', '반려동물 선택', 'Select Pet', 'ペット選択', '选择宠物', '選擇寵物', 'Seleccionar mascota', 'Sélectionner l''animal', 'Haustier auswählen', 'Selecionar pet', 'Chọn thú cưng', 'เลือกสัตว์เลี้ยง', 'Pilih Hewan', 'اختيار الحيوان') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.step.confirm', 'booking', '예약 확인', 'Confirm Booking', '予約確認', '确认预约', '確認預約', 'Confirmar reserva', 'Confirmer la réservation', 'Buchung bestätigen', 'Confirmar reserva', 'Xác nhận đặt lịch', 'ยืนยันการจอง', 'Konfirmasi Pemesanan', 'تأكيد الحجز') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.step.date', 'booking', '날짜 선택', 'Select Date', '日付選択', '选择日期', '選擇日期', 'Seleccionar fecha', 'Sélectionner la date', 'Datum auswählen', 'Selecionar data', 'Chọn ngày', 'เลือกวันที่', 'Pilih Tanggal', 'اختيار التاريخ') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.step.time', 'booking', '시간 선택', 'Select Time', '時間選択', '选择时间', '選擇時間', 'Seleccionar hora', 'Sélectionner l''heure', 'Uhrzeit auswählen', 'Selecionar horário', 'Chọn giờ', 'เลือกเวลา', 'Pilih Waktu', 'اختيار الوقت') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.slot.normal', 'booking', '영업시간', 'Business Hours', '営業時間', '营业时间', '營業時間', 'Horario de atención', 'Heures d''ouverture', 'Öffnungszeiten', 'Horário comercial', 'Giờ làm việc', 'เวลาทำการ', 'Jam Operasional', 'ساعات العمل') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.slot.overtime', 'booking', '영업시간 외', 'After Hours', '営業時間外', '营业时间外', '營業時間外', 'Fuera de horario', 'Hors heures', 'Außerhalb der Öffnungszeiten', 'Fora do horário', 'Ngoài giờ', 'นอกเวลาทำการ', 'Di Luar Jam', 'خارج الدوام') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.slot.closed', 'booking', '정기 휴무', 'Closed', '定休日', '休息', '休息', 'Cerrado', 'Fermé', 'Geschlossen', 'Fechado', 'Nghỉ', 'ปิด', 'Tutup', 'مغلق') ON CONFLICT (key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3. Booking fields — business-type specific
-- ---------------------------------------------------------------------------
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.grooming_style', 'booking', '희망 스타일', 'Preferred Style', 'ご希望のスタイル', '期望造型', '期望造型', 'Estilo preferido', 'Style préféré', 'Bevorzugter Stil', 'Estilo preferido', 'Kiểu tạo dáng mong muốn', 'สไตล์ที่ต้องการ', 'Gaya yang diinginkan', 'النمط المفضل') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.symptom', 'booking', '증상 / 내원 이유', 'Symptoms / Reason for Visit', '症状 / 来院理由', '症状 / 就诊原因', '症狀 / 就診原因', 'Síntomas / Motivo de visita', 'Symptômes / Motif de visite', 'Symptome / Besuchsgrund', 'Sintomas / Motivo da visita', 'Triệu chứng / Lý do khám', 'อาการ / เหตุผลในการเข้าพบ', 'Gejala / Alasan kunjungan', 'الأعراض / سبب الزيارة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.first_visit', 'booking', '첫 방문 여부', 'First Visit', '初回来院', '是否首次就诊', '是否首次就診', '¿Primera visita?', 'Première visite', 'Erstbesuch', 'Primeira visita', 'Lần khám đầu tiên', 'การเข้าพบครั้งแรก', 'Kunjungan pertama', 'الزيارة الأولى') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.training_goal', 'booking', '훈련 목표 / 교정이 필요한 행동', 'Training Goal / Behavior to Correct', 'トレーニング目標 / 矯正が必要な行動', '训练目标 / 需要纠正的行为', '訓練目標 / 需要矯正的行為', 'Objetivo de entrenamiento / Conducta a corregir', 'Objectif d''entraînement / Comportement à corriger', 'Trainingsziel / Zu korrigierendes Verhalten', 'Objetivo de treino / Comportamento a corrigir', 'Mục tiêu huấn luyện / Hành vi cần chỉnh sửa', 'เป้าหมายการฝึก / พฤติกรรมที่ต้องแก้ไข', 'Tujuan pelatihan / Perilaku yang perlu diperbaiki', 'هدف التدريب / السلوك المطلوب تصحيحه') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.experience_level', 'booking', '훈련 경험', 'Training Experience', 'トレーニング経験', '训练经验', '訓練經驗', 'Experiencia de entrenamiento', 'Expérience d''entraînement', 'Trainingserfahrung', 'Experiência de treino', 'Kinh nghiệm huấn luyện', 'ประสบการณ์การฝึก', 'Pengalaman pelatihan', 'خبرة التدريب') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.experience_none', 'booking', '없음', 'None', 'なし', '无', '無', 'Ninguna', 'Aucune', 'Keine', 'Nenhuma', 'Không có', 'ไม่มี', 'Tidak ada', 'لا يوجد') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.experience_basic', 'booking', '기초 완료', 'Basic Completed', '基礎修了', '基础完成', '基礎完成', 'Básico completado', 'Base terminée', 'Grundlagen abgeschlossen', 'Básico concluído', 'Đã hoàn thành cơ bản', 'จบพื้นฐานแล้ว', 'Dasar selesai', 'الأساسيات مكتملة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.experience_mid', 'booking', '중급 이상', 'Intermediate+', '中級以上', '中级以上', '中級以上', 'Intermedio o superior', 'Intermédiaire ou plus', 'Mittelstufe oder höher', 'Intermediário ou superior', 'Trung cấp trở lên', 'ระดับกลางขึ้นไป', 'Menengah ke atas', 'متوسط فأعلى') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.visit_purpose', 'booking', '방문 목적', 'Purpose of Visit', 'ご来店目的', '来访目的', '來訪目的', 'Propósito de la visita', 'Motif de la visite', 'Besuchszweck', 'Finalidade da visita', 'Mục đích ghé thăm', 'วัตถุประสงค์การเยี่ยมชม', 'Tujuan kunjungan', 'الغرض من الزيارة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.visit_food', 'booking', '사료 구매', 'Buy Food', 'フード購入', '购买粮食', '購買飼料', 'Comprar alimento', 'Acheter de la nourriture', 'Futter kaufen', 'Comprar ração', 'Mua thức ăn', 'ซื้ออาหาร', 'Beli makanan', 'شراء طعام') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.visit_goods', 'booking', '용품 구매', 'Buy Supplies', '用品購入', '购买用品', '購買用品', 'Comprar suministros', 'Acheter des fournitures', 'Zubehör kaufen', 'Comprar acessórios', 'Mua vật dụng', 'ซื้อสินค้า', 'Beli perlengkapan', 'شراء مستلزمات') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.visit_consult', 'booking', '상담', 'Consultation', 'ご相談', '咨询', '諮詢', 'Consulta', 'Consultation', 'Beratung', 'Consulta', 'Tư vấn', 'ปรึกษา', 'Konsultasi', 'استشارة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.visit_etc', 'booking', '기타', 'Other', 'その他', '其他', '其他', 'Otro', 'Autre', 'Sonstiges', 'Outro', 'Khác', 'อื่นๆ', 'Lainnya', 'أخرى') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.checkout_date', 'booking', '체크아웃 날짜', 'Checkout Date', 'チェックアウト日', '退房日期', '退房日期', 'Fecha de salida', 'Date de départ', 'Abreisedatum', 'Data de saída', 'Ngày trả phòng', 'วันที่เช็คเอาท์', 'Tanggal checkout', 'تاريخ المغادرة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.feeding_info', 'booking', '사료 / 급여 정보', 'Food / Feeding Info', 'フード / 給餌情報', '饲料 / 喂食信息', '飼料 / 餵食資訊', 'Alimento / Información de alimentación', 'Nourriture / Informations d''alimentation', 'Futter / Fütterungsinformationen', 'Ração / Informações de alimentação', 'Thức ăn / Thông tin cho ăn', 'อาหาร / ข้อมูลการให้อาหาร', 'Makanan / Info pemberian makan', 'الطعام / معلومات التغذية') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.special_care', 'booking', '특이사항 / 주의사항', 'Special Notes / Precautions', '特記事項 / 注意事項', '特殊事项 / 注意事项', '特殊事項 / 注意事項', 'Notas especiales / Precauciones', 'Notes spéciales / Précautions', 'Besondere Hinweise / Vorsichtsmaßnahmen', 'Observações especiais / Precauções', 'Lưu ý đặc biệt / Thận trọng', 'หมายเหตุพิเศษ / ข้อควรระวัง', 'Catatan khusus / Tindakan pencegahan', 'ملاحظات خاصة / احتياطات') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.guest_count', 'booking', '방문 인원', 'Number of Guests', 'ご来店人数', '来访人数', '來訪人數', 'Número de visitantes', 'Nombre de visiteurs', 'Anzahl der Gäste', 'Número de visitantes', 'Số lượng khách', 'จำนวนผู้เข้าชม', 'Jumlah tamu', 'عدد الزوار') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.has_pet', 'booking', '반려동물 동반 여부', 'Bringing a Pet', 'ペット同伴の有無', '是否携带宠物', '是否攜帶寵物', '¿Trae mascota?', 'Accompagné d''un animal', 'Haustier mitbringen', 'Traz animal de estimação', 'Có mang theo thú cưng', 'นำสัตว์เลี้ยงมาด้วย', 'Membawa hewan peliharaan', 'هل تصطحب حيوانًا أليفًا') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.shooting_theme', 'booking', '촬영 테마', 'Shooting Theme', '撮影テーマ', '拍摄主题', '拍攝主題', 'Tema de la sesión', 'Thème de la séance', 'Fotothema', 'Tema da sessão', 'Chủ đề chụp ảnh', 'ธีมการถ่ายภาพ', 'Tema pemotretan', 'موضوع التصوير') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.field.request_note', 'booking', '요청사항', 'Special Requests', 'ご要望', '备注要求', '備註要求', 'Solicitudes especiales', 'Demandes spéciales', 'Besondere Wünsche', 'Pedidos especiais', 'Yêu cầu đặc biệt', 'คำขอพิเศษ', 'Permintaan khusus', 'طلبات خاصة') ON CONFLICT (key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 4. Booking pet selection & health report
-- ---------------------------------------------------------------------------
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.pet_select', 'booking', '반려동물을 선택해주세요', 'Please select your pet', 'ペットを選択してください', '请选择您的宠物', '請選擇您的寵物', 'Por favor, seleccione su mascota', 'Veuillez sélectionner votre animal', 'Bitte wählen Sie Ihr Haustier', 'Por favor, selecione seu animal', 'Vui lòng chọn thú cưng của bạn', 'กรุณาเลือกสัตว์เลี้ยงของคุณ', 'Silakan pilih hewan peliharaan Anda', 'يرجى اختيار حيوانك الأليف') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.no_pet', 'booking', '반려동물 없이 방문', 'Visit without pet', 'ペットなしで来店', '无宠物来访', '無寵物來訪', 'Visita sin mascota', 'Visite sans animal', 'Besuch ohne Haustier', 'Visita sem animal', 'Ghé thăm không mang thú cưng', 'เยี่ยมชมโดยไม่มีสัตว์เลี้ยง', 'Kunjungan tanpa hewan peliharaan', 'زيارة بدون حيوان أليف') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.report_title', 'booking', '건강 리포트 전송 (선택)', 'Send Health Report (Optional)', '健康レポート送信（任意）', '发送健康报告（可选）', '傳送健康報告（選填）', 'Enviar informe de salud (Opcional)', 'Envoyer le rapport de santé (Facultatif)', 'Gesundheitsbericht senden (Optional)', 'Enviar relatório de saúde (Opcional)', 'Gửi báo cáo sức khỏe (Tùy chọn)', 'ส่งรายงานสุขภาพ (ไม่บังคับ)', 'Kirim laporan kesehatan (Opsional)', 'إرسال التقرير الصحي (اختياري)') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.report_none', 'booking', '전송 안 함', 'Don''t Send', '送信しない', '不发送', '不傳送', 'No enviar', 'Ne pas envoyer', 'Nicht senden', 'Não enviar', 'Không gửi', 'ไม่ส่ง', 'Jangan kirim', 'عدم الإرسال') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.report_1d', 'booking', '최근 1일', 'Last 1 Day', '直近1日', '最近1天', '最近1天', 'Último día', 'Dernier jour', 'Letzter Tag', 'Último dia', 'Trong 1 ngày qua', 'ล่าสุด 1 วัน', 'Terakhir 1 hari', 'آخر يوم') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.report_7d', 'booking', '최근 7일', 'Last 7 Days', '直近7日間', '最近7天', '最近7天', 'Últimos 7 días', 'Derniers 7 jours', 'Letzte 7 Tage', 'Últimos 7 dias', 'Trong 7 ngày qua', 'ล่าสุด 7 วัน', 'Terakhir 7 hari', 'آخر 7 أيام') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.report_15d', 'booking', '최근 15일', 'Last 15 Days', '直近15日間', '最近15天', '最近15天', 'Últimos 15 días', 'Derniers 15 jours', 'Letzte 15 Tage', 'Últimos 15 dias', 'Trong 15 ngày qua', 'ล่าสุด 15 วัน', 'Terakhir 15 hari', 'آخر 15 يومًا') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.report_1m', 'booking', '최근 1개월', 'Last 1 Month', '直近1ヶ月', '最近1个月', '最近1個月', 'Último mes', 'Dernier mois', 'Letzter Monat', 'Último mês', 'Trong 1 tháng qua', 'ล่าสุด 1 เดือน', 'Terakhir 1 bulan', 'آخر شهر') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.report_desc', 'booking', '리포트 전송 시 더 나은 서비스를 받을 수 있어요', 'Sharing a report helps provide better service', 'レポートを送信すると、より良いサービスを受けられます', '发送报告可以获得更好的服务', '傳送報告可以獲得更好的服務', 'Compartir un informe ayuda a ofrecer un mejor servicio', 'Partager un rapport permet d''offrir un meilleur service', 'Das Teilen eines Berichts hilft, besseren Service zu bieten', 'Compartilhar um relatório ajuda a oferecer um serviço melhor', 'Chia sẻ báo cáo giúp cung cấp dịch vụ tốt hơn', 'การแชร์รายงานช่วยให้บริการได้ดียิ่งขึ้น', 'Membagikan laporan membantu memberikan layanan yang lebih baik', 'مشاركة التقرير تساعد في تقديم خدمة أفضل') ON CONFLICT (key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 5. Booking summary, notices, & submit
-- ---------------------------------------------------------------------------
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.summary_title', 'booking', '예약 요약', 'Booking Summary', '予約概要', '预约摘要', '預約摘要', 'Resumen de reserva', 'Résumé de la réservation', 'Buchungsübersicht', 'Resumo da reserva', 'Tóm tắt đặt lịch', 'สรุปการจอง', 'Ringkasan Pemesanan', 'ملخص الحجز') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.service_fee', 'booking', '서비스 요금', 'Service Fee', 'サービス料金', '服务费用', '服務費用', 'Tarifa del servicio', 'Frais de service', 'Servicegebühr', 'Taxa de serviço', 'Phí dịch vụ', 'ค่าบริการ', 'Biaya Layanan', 'رسوم الخدمة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.overtime_fee', 'booking', '연장 추가 요금', 'Overtime Fee', '延長追加料金', '超时附加费', '超時附加費', 'Cargo por tiempo extra', 'Frais de dépassement horaire', 'Überstundengebühr', 'Taxa de hora extra', 'Phí ngoài giờ', 'ค่าธรรมเนียมล่วงเวลา', 'Biaya Lembur', 'رسوم الوقت الإضافي') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.total_fee', 'booking', '총 예상 금액', 'Estimated Total', '合計見積額', '预估总额', '預估總額', 'Total estimado', 'Total estimé', 'Geschätzter Gesamtbetrag', 'Total estimado', 'Tổng ước tính', 'ยอดรวมโดยประมาณ', 'Estimasi Total', 'الإجمالي المقدر') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.overtime_warning', 'booking', '영업시간 초과 예약', 'Overtime Booking', '営業時間外予約', '超时预约', '超時預約', 'Reserva fuera de horario', 'Réservation hors horaires', 'Buchung außerhalb der Öffnungszeiten', 'Reserva fora do horário', 'Đặt lịch ngoài giờ', 'การจองนอกเวลา', 'Pemesanan di Luar Jam Operasional', 'حجز خارج ساعات العمل') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.overtime_confirm_notice', 'booking', '공급자 수락 시 예약이 확정됩니다', 'Booking will be confirmed when provider accepts', 'プロバイダーが承認すると予約が確定します', '供应商接受后预约将被确认', '供應商接受後預約將被確認', 'La reserva se confirmará cuando el proveedor acepte', 'La réservation sera confirmée lorsque le prestataire acceptera', 'Die Buchung wird bestätigt, wenn der Anbieter zustimmt', 'A reserva será confirmada quando o fornecedor aceitar', 'Đặt lịch sẽ được xác nhận khi nhà cung cấp chấp nhận', 'การจองจะได้รับการยืนยันเมื่อผู้ให้บริการตอบรับ', 'Pemesanan akan dikonfirmasi saat penyedia menerima', 'سيتم تأكيد الحجز عند قبول مقدم الخدمة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.submit_btn', 'booking', '예약 신청하기', 'Submit Booking', '予約を申し込む', '提交预约', '提交預約', 'Enviar reserva', 'Soumettre la réservation', 'Buchung absenden', 'Enviar reserva', 'Gửi đặt lịch', 'ส่งคำขอจอง', 'Kirim Pemesanan', 'إرسال الحجز') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.success_toast', 'booking', '예약이 신청되었습니다', 'Booking submitted successfully', '予約が申し込まれました', '预约已提交', '預約已提交', 'Reserva enviada con éxito', 'Réservation soumise avec succès', 'Buchung erfolgreich gesendet', 'Reserva enviada com sucesso', 'Đã gửi đặt lịch thành công', 'ส่งคำขอจองเรียบร้อยแล้ว', 'Pemesanan berhasil dikirim', 'تم إرسال الحجز بنجاح') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.notice.grooming', 'booking', '예약 확정 후 당일 취소 시 노쇼 처리될 수 있습니다', 'Same-day cancellation after confirmation may be treated as a no-show', '確定後の当日キャンセルはノーショー扱いとなる場合があります', '确认后当日取消可能被视为未到场', '確認後當日取消可能被視為未到場', 'La cancelación el mismo día después de la confirmación puede considerarse como ausencia', 'Une annulation le jour même après confirmation peut être considérée comme une absence', 'Eine Stornierung am selben Tag nach Bestätigung kann als Nichterscheinen gewertet werden', 'O cancelamento no mesmo dia após a confirmação pode ser tratado como não comparecimento', 'Hủy trong ngày sau khi xác nhận có thể bị coi là vắng mặt', 'การยกเลิกในวันเดียวกันหลังยืนยันอาจถูกถือว่าไม่มาตามนัด', 'Pembatalan di hari yang sama setelah konfirmasi dapat dianggap tidak hadir', 'قد يُعتبر الإلغاء في نفس اليوم بعد التأكيد عدم حضور') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.notice.vet', 'booking', '진료 내용에 따라 추가 비용이 발생할 수 있습니다', 'Additional charges may apply depending on treatment', '診療内容により追加料金が発生する場合があります', '根据诊疗内容可能会产生额外费用', '根據診療內容可能會產生額外費用', 'Pueden aplicarse cargos adicionales según el tratamiento', 'Des frais supplémentaires peuvent s''appliquer selon le traitement', 'Je nach Behandlung können zusätzliche Kosten anfallen', 'Taxas adicionais podem ser aplicadas dependendo do tratamento', 'Có thể phát sinh phí bổ sung tùy theo nội dung khám chữa', 'อาจมีค่าใช้จ่ายเพิ่มเติมขึ้นอยู่กับการรักษา', 'Biaya tambahan mungkin berlaku tergantung pada perawatan', 'قد يتم تطبيق رسوم إضافية حسب العلاج') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.notice.training', 'booking', '첫 방문 시 기초 평가 후 프로그램이 조정될 수 있습니다', 'Program may be adjusted after initial assessment', '初回訪問時の基礎評価後にプログラムが調整される場合があります', '首次到访基础评估后课程可能会调整', '首次到訪基礎評估後課程可能會調整', 'El programa puede ajustarse después de la evaluación inicial', 'Le programme peut être ajusté après l''évaluation initiale', 'Das Programm kann nach der Erstbewertung angepasst werden', 'O programa pode ser ajustado após a avaliação inicial', 'Chương trình có thể được điều chỉnh sau đánh giá ban đầu', 'โปรแกรมอาจปรับเปลี่ยนหลังการประเมินเบื้องต้น', 'Program dapat disesuaikan setelah penilaian awal', 'قد يتم تعديل البرنامج بعد التقييم الأولي') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.notice.petshop', 'booking', '방문 전 재고 확인을 원하시면 요청사항에 적어주세요', 'Please note stock inquiries in special requests', '在庫確認をご希望の場合はリクエスト欄にご記入ください', '如需确认库存请在备注中说明', '如需確認庫存請在備註中說明', 'Para consultas de stock, indíquelo en solicitudes especiales', 'Pour vérifier le stock, veuillez l''indiquer dans les demandes spéciales', 'Für Bestandsanfragen vermerken Sie dies bitte bei den Sonderwünschen', 'Para consultas de estoque, indique nas solicitações especiais', 'Nếu muốn kiểm tra hàng tồn kho, vui lòng ghi trong yêu cầu đặc biệt', 'หากต้องการตรวจสอบสินค้าคงคลัง กรุณาระบุในคำขอพิเศษ', 'Untuk pengecekan stok, silakan tulis di permintaan khusus', 'للاستفسار عن المخزون، يرجى ذكر ذلك في الطلبات الخاصة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.notice.hotel', 'booking', '체크인 시 예방접종 증명서 지참이 필요할 수 있습니다', 'Vaccination certificate may be required at check-in', 'チェックイン時にワクチン接種証明書が必要になる場合があります', '办理入住时可能需要出示疫苗接种证明', '辦理入住時可能需要出示疫苗接種證明', 'Es posible que se requiera certificado de vacunación al registrarse', 'Un certificat de vaccination peut être requis à l''enregistrement', 'Bei der Anmeldung kann ein Impfnachweis erforderlich sein', 'O certificado de vacinação pode ser exigido no check-in', 'Có thể cần xuất trình giấy chứng nhận tiêm phòng khi nhận phòng', 'อาจต้องแสดงใบรับรองการฉีดวัคซีนเมื่อเช็คอิน', 'Sertifikat vaksinasi mungkin diperlukan saat check-in', 'قد يُطلب شهادة التطعيم عند تسجيل الوصول') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.notice.petcafe', 'booking', '반려동물 동반 시 기본 예절 교육이 된 동물만 입장 가능합니다', 'Only well-trained pets are allowed entry', '基本的なマナーが身についたペットのみ入場可能です', '仅允许经过基本礼仪训练的宠物入场', '僅允許經過基本禮儀訓練的寵物入場', 'Solo se permite la entrada de mascotas con entrenamiento básico', 'Seuls les animaux ayant reçu une éducation de base sont admis', 'Nur Haustiere mit Grundgehorsamkeit sind zugelassen', 'Somente animais com treinamento básico de comportamento são permitidos', 'Chỉ cho phép thú cưng đã được huấn luyện cơ bản', 'อนุญาตเฉพาะสัตว์เลี้ยงที่ได้รับการฝึกมารยาทพื้นฐานเท่านั้น', 'Hanya hewan peliharaan yang sudah terlatih dasar yang diizinkan masuk', 'يُسمح فقط بدخول الحيوانات الأليفة المدربة على الآداب الأساسية') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.notice.photo', 'booking', '촬영 결과물은 영업일 기준 3~5일 내 전달됩니다', 'Photos will be delivered within 3-5 business days', '撮影データは営業日3〜5日以内にお届けします', '拍摄成果将在3至5个工作日内交付', '拍攝成果將在3至5個工作日內交付', 'Las fotos se entregarán en 3 a 5 días hábiles', 'Les photos seront livrées sous 3 à 5 jours ouvrables', 'Die Fotos werden innerhalb von 3–5 Werktagen geliefert', 'As fotos serão entregues em 3 a 5 dias úteis', 'Ảnh sẽ được giao trong 3-5 ngày làm việc', 'ภาพถ่ายจะจัดส่งภายใน 3-5 วันทำการ', 'Foto akan dikirimkan dalam 3-5 hari kerja', 'سيتم تسليم الصور خلال 3-5 أيام عمل') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'booking.notice.common', 'booking', '예약 신청 후 공급자 확인이 완료되면 앱 알림으로 안내드립니다', 'You will be notified when the provider confirms', '予約申し込み後、プロバイダーの確認が完了するとアプリ通知でお知らせします', '提交预约后供应商确认完成时将通过应用通知您', '提交預約後供應商確認完成時將透過應用程式通知您', 'Se le notificará cuando el proveedor confirme', 'Vous serez notifié lorsque le prestataire confirmera', 'Sie werden benachrichtigt, wenn der Anbieter bestätigt', 'Você será notificado quando o fornecedor confirmar', 'Bạn sẽ được thông báo khi nhà cung cấp xác nhận', 'คุณจะได้รับการแจ้งเตือนเมื่อผู้ให้บริการยืนยัน', 'Anda akan diberi tahu saat penyedia mengonfirmasi', 'سيتم إعلامك عند تأكيد مقدم الخدمة') ON CONFLICT (key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 6. Supplier settings (overtime + review)
-- ---------------------------------------------------------------------------
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.setting.overtime_title', 'supplier', '영업시간 초과 예약 신청', 'Overtime Booking Requests', '営業時間外予約リクエスト', '超时预约申请', '超時預約申請', 'Solicitudes de reserva fuera de horario', 'Demandes de réservation hors horaires', 'Buchungsanfragen außerhalb der Öffnungszeiten', 'Solicitações de reserva fora do horário', 'Yêu cầu đặt lịch ngoài giờ', 'คำขอจองนอกเวลา', 'Permintaan Pemesanan di Luar Jam Operasional', 'طلبات الحجز خارج ساعات العمل') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.setting.overtime_allow', 'supplier', '허용 (공급자가 수락 여부 결정)', 'Allow (provider decides)', '許可（プロバイダーが承認を決定）', '允许（由供应商决定是否接受）', '允許（由供應商決定是否接受）', 'Permitir (el proveedor decide)', 'Autoriser (le prestataire décide)', 'Erlauben (Anbieter entscheidet)', 'Permitir (fornecedor decide)', 'Cho phép (nhà cung cấp quyết định)', 'อนุญาต (ผู้ให้บริการตัดสินใจ)', 'Izinkan (penyedia yang memutuskan)', 'السماح (مقدم الخدمة يقرر)') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.setting.overtime_deny', 'supplier', '허용 안 함', 'Do Not Allow', '許可しない', '不允许', '不允許', 'No permitir', 'Ne pas autoriser', 'Nicht erlauben', 'Não permitir', 'Không cho phép', 'ไม่อนุญาต', 'Tidak Mengizinkan', 'عدم السماح') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.setting.overtime_fee', 'supplier', '연장 추가 요금', 'Overtime Fee', '延長追加料金', '超时附加费', '超時附加費', 'Cargo por tiempo extra', 'Frais de dépassement horaire', 'Überstundengebühr', 'Taxa de hora extra', 'Phí ngoài giờ', 'ค่าธรรมเนียมล่วงเวลา', 'Biaya Lembur', 'رسوم الوقت الإضافي') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.setting.overtime_fee_free', 'supplier', '없음 (무료)', 'None (Free)', 'なし（無料）', '无（免费）', '無（免費）', 'Ninguno (Gratis)', 'Aucun (Gratuit)', 'Keine (Kostenlos)', 'Nenhuma (Grátis)', 'Không (Miễn phí)', 'ไม่มี (ฟรี)', 'Tidak Ada (Gratis)', 'لا يوجد (مجاني)') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.setting.overtime_fee_fixed', 'supplier', '고정 금액', 'Fixed Amount', '固定金額', '固定金额', '固定金額', 'Monto fijo', 'Montant fixe', 'Festbetrag', 'Valor fixo', 'Số tiền cố định', 'จำนวนเงินคงที่', 'Jumlah Tetap', 'مبلغ ثابت') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.setting.overtime_fee_per30', 'supplier', '30분당', 'Per 30 Minutes', '30分ごと', '每30分钟', '每30分鐘', 'Por cada 30 minutos', 'Par tranche de 30 minutes', 'Pro 30 Minuten', 'A cada 30 minutos', 'Mỗi 30 phút', 'ทุก 30 นาที', 'Per 30 Menit', 'لكل 30 دقيقة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.appointment.overtime_badge', 'supplier', '영업시간 초과 예약', 'Overtime Booking', '営業時間外予約', '超时预约', '超時預約', 'Reserva fuera de horario', 'Réservation hors horaires', 'Buchung außerhalb der Öffnungszeiten', 'Reserva fora do horário', 'Đặt lịch ngoài giờ', 'การจองนอกเวลา', 'Pemesanan di Luar Jam Operasional', 'حجز خارج ساعات العمل') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.setting.review_title', 'supplier', '후기 공개 설정', 'Review Visibility Setting', 'レビュー公開設定', '评价公开设置', '評價公開設定', 'Configuración de visibilidad de reseñas', 'Paramètre de visibilité des avis', 'Bewertungssichtbarkeit einstellen', 'Configuração de visibilidade de avaliações', 'Cài đặt hiển thị đánh giá', 'ตั้งค่าการแสดงรีวิว', 'Pengaturan Visibilitas Ulasan', 'إعداد ظهور التقييمات') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.setting.review_public_on', 'supplier', '전체 공개 (모든 후기 노출)', 'Public (all reviews visible)', '全体公開（すべてのレビューを表示）', '全部公开（所有评价可见）', '全部公開（所有評價可見）', 'Público (todas las reseñas visibles)', 'Public (tous les avis visibles)', 'Öffentlich (alle Bewertungen sichtbar)', 'Público (todas as avaliações visíveis)', 'Công khai (tất cả đánh giá hiển thị)', 'สาธารณะ (รีวิวทั้งหมดแสดง)', 'Publik (semua ulasan terlihat)', 'عام (جميع التقييمات مرئية)') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.setting.review_public_off', 'supplier', '비공개 (가디언↔공급자만 열람)', 'Private (guardian ↔ provider only)', '非公開（ガーディアン↔プロバイダーのみ閲覧可）', '私密（仅保护者↔供应商可查看）', '私密（僅保護者↔供應商可查看）', 'Privado (solo guardián ↔ proveedor)', 'Privé (tuteur ↔ prestataire uniquement)', 'Privat (nur Betreuer ↔ Anbieter)', 'Privado (apenas guardião ↔ fornecedor)', 'Riêng tư (chỉ người giám hộ ↔ nhà cung cấp)', 'ส่วนตัว (เฉพาะผู้ดูแล ↔ ผู้ให้บริการ)', 'Pribadi (hanya wali ↔ penyedia)', 'خاص (الوصي ↔ مقدم الخدمة فقط)') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.setting.review_public_desc', 'supplier', 'ON 설정 시 매장 프로필에 후기가 공개됩니다', 'When ON, reviews are shown on store profile', 'ONにすると店舗プロフィールにレビューが公開されます', '开启后评价将显示在店铺主页上', '開啟後評價將顯示在店鋪主頁上', 'Cuando está activado, las reseñas se muestran en el perfil de la tienda', 'Lorsqu''activé, les avis sont affichés sur le profil du magasin', 'Wenn aktiviert, werden Bewertungen im Geschäftsprofil angezeigt', 'Quando ativado, as avaliações são exibidas no perfil da loja', 'Khi bật, đánh giá sẽ hiển thị trên hồ sơ cửa hàng', 'เมื่อเปิด รีวิวจะแสดงบนโปรไฟล์ร้านค้า', 'Saat diaktifkan, ulasan ditampilkan di profil toko', 'عند التفعيل، تُعرض التقييمات على صفحة المتجر') ON CONFLICT (key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 7. Grooming completion & report
-- ---------------------------------------------------------------------------
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'grooming.complete.title', 'grooming', '미용 완료 입력', 'Grooming Completion', 'グルーミング完了入力', '美容完成输入', '美容完成輸入', 'Finalización de peluquería', 'Toilettage terminé', 'Pflege abgeschlossen', 'Conclusão da tosa', 'Nhập hoàn thành làm đẹp', 'บันทึกการทำสำเร็จ', 'Input Selesai Grooming', 'إتمام العناية') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'grooming.complete.cut_label', 'grooming', '미용 컷 선택', 'Select Cut Style', 'カットスタイルを選択', '选择剪毛样式', '選擇剪毛樣式', 'Seleccionar estilo de corte', 'Sélectionner le style de coupe', 'Schnittstil auswählen', 'Selecionar estilo de corte', 'Chọn kiểu cắt', 'เลือกสไตล์การตัด', 'Pilih Gaya Potongan', 'اختيار نمط القص') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'grooming.complete.cut_other', 'grooming', '기타 (직접 입력)', 'Other (Custom)', 'その他（直接入力）', '其他（自定义）', '其他（自訂）', 'Otro (personalizado)', 'Autre (personnalisé)', 'Sonstiges (benutzerdefiniert)', 'Outro (personalizado)', 'Khác (tùy chỉnh)', 'อื่นๆ (กำหนดเอง)', 'Lainnya (Kustom)', 'أخرى (مخصص)') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'grooming.complete.cut_placeholder', 'grooming', '컷 이름을 입력해주세요', 'Enter cut name', 'カット名を入力してください', '请输入剪毛名称', '請輸入剪毛名稱', 'Introduzca el nombre del corte', 'Saisissez le nom de la coupe', 'Schnittname eingeben', 'Digite o nome do corte', 'Nhập tên kiểu cắt', 'กรอกชื่อทรงตัด', 'Masukkan nama potongan', 'أدخل اسم القصة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'grooming.complete.photo_label', 'grooming', '시술 사진 업로드', 'Upload Service Photos', '施術写真をアップロード', '上传服务照片', '上傳服務照片', 'Subir fotos del servicio', 'Télécharger les photos du service', 'Servicefotos hochladen', 'Enviar fotos do serviço', 'Tải lên ảnh dịch vụ', 'อัปโหลดรูปบริการ', 'Unggah Foto Layanan', 'رفع صور الخدمة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'grooming.complete.memo', 'grooming', '메모 (가디언에게 전달됩니다)', 'Memo (will be sent to guardian)', 'メモ（飼い主に送信されます）', '备注（将发送给监护人）', '備註（將傳送給飼主）', 'Nota (se enviará al tutor)', 'Mémo (sera envoyé au tuteur)', 'Notiz (wird an den Halter gesendet)', 'Observação (será enviada ao tutor)', 'Ghi chú (sẽ được gửi cho người giám hộ)', 'บันทึก (จะส่งถึงผู้ดูแล)', 'Memo (akan dikirim ke pemilik)', 'ملاحظة (سيتم إرسالها إلى ولي الأمر)') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'grooming.complete.submit', 'grooming', '완료 보고 전송', 'Submit Completion Report', '完了報告を送信', '提交完成报告', '提交完成報告', 'Enviar informe de finalización', 'Soumettre le rapport de fin', 'Abschlussbericht senden', 'Enviar relatório de conclusão', 'Gửi báo cáo hoàn thành', 'ส่งรายงานเสร็จสิ้น', 'Kirim Laporan Selesai', 'إرسال تقرير الإتمام') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'grooming.complete.success', 'grooming', '완료 보고가 전송되었습니다', 'Completion report sent', '完了報告が送信されました', '完成报告已发送', '完成報告已傳送', 'Informe de finalización enviado', 'Rapport de fin envoyé', 'Abschlussbericht gesendet', 'Relatório de conclusão enviado', 'Đã gửi báo cáo hoàn thành', 'ส่งรายงานเสร็จสิ้นแล้ว', 'Laporan selesai terkirim', 'تم إرسال تقرير الإتمام') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'grooming.report.title', 'grooming', '미용 완료 보고', 'Grooming Completion Report', 'グルーミング完了報告', '美容完成报告', '美容完成報告', 'Informe de finalización de peluquería', 'Rapport de toilettage terminé', 'Pflegeabschlussbericht', 'Relatório de conclusão da tosa', 'Báo cáo hoàn thành làm đẹp', 'รายงานการทำสำเร็จ', 'Laporan Selesai Grooming', 'تقرير إتمام العناية') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'grooming.report.approve_only', 'grooming', '승인', 'Approve', '承認', '批准', '批准', 'Aprobar', 'Approuver', 'Genehmigen', 'Aprovar', 'Phê duyệt', 'อนุมัติ', 'Setujui', 'الموافقة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'grooming.report.approve_feed', 'grooming', '승인 + 피드 게시', 'Approve + Post to Feed', '承認 + フィードに投稿', '批准 + 发布到动态', '批准 + 發佈到動態', 'Aprobar + Publicar en el feed', 'Approuver + Publier dans le fil', 'Genehmigen + Im Feed posten', 'Aprovar + Publicar no feed', 'Phê duyệt + Đăng lên bảng tin', 'อนุมัติ + โพสต์ลงฟีด', 'Setujui + Posting ke Feed', 'الموافقة + النشر في الخلاصة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'grooming.report.approved_toast', 'grooming', '완료 확인되었습니다', 'Completion confirmed', '完了が確認されました', '已确认完成', '已確認完成', 'Finalización confirmada', 'Fin confirmée', 'Abschluss bestätigt', 'Conclusão confirmada', 'Đã xác nhận hoàn thành', 'ยืนยันเสร็จสิ้นแล้ว', 'Penyelesaian dikonfirmasi', 'تم تأكيد الإتمام') ON CONFLICT (key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 8. Review system
-- ---------------------------------------------------------------------------
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'review.title.guardian', 'review', '서비스 후기 작성', 'Write Service Review', 'サービスレビューを書く', '撰写服务评价', '撰寫服務評價', 'Escribir reseña del servicio', 'Écrire un avis sur le service', 'Servicebewertung schreiben', 'Escrever avaliação do serviço', 'Viết đánh giá dịch vụ', 'เขียนรีวิวบริการ', 'Tulis Ulasan Layanan', 'كتابة تقييم الخدمة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'review.title.supplier', 'review', '고객 후기 작성', 'Write Customer Review', '顧客レビューを書く', '撰写客户评价', '撰寫客戶評價', 'Escribir reseña del cliente', 'Écrire un avis sur le client', 'Kundenbewertung schreiben', 'Escrever avaliação do cliente', 'Viết đánh giá khách hàng', 'เขียนรีวิวลูกค้า', 'Tulis Ulasan Pelanggan', 'كتابة تقييم العميل') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'review.rating_label', 'review', '별점', 'Rating', '評価', '评分', '評分', 'Puntuación', 'Note', 'Bewertung', 'Avaliação', 'Đánh giá', 'คะแนน', 'Penilaian', 'التقييم') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'review.content_label', 'review', '후기', 'Review', 'レビュー', '评价', '評價', 'Reseña', 'Avis', 'Bewertung', 'Avaliação', 'Đánh giá', 'รีวิว', 'Ulasan', 'المراجعة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'review.content_placeholder.guardian', 'review', '서비스는 어떠셨나요? (선택)', 'How was the service? (Optional)', 'サービスはいかがでしたか？（任意）', '服务怎么样？（可选）', '服務如何？（選填）', '¿Cómo fue el servicio? (Opcional)', 'Comment était le service ? (Facultatif)', 'Wie war der Service? (Optional)', 'Como foi o serviço? (Opcional)', 'Dịch vụ thế nào? (Tùy chọn)', 'บริการเป็นอย่างไร? (ไม่บังคับ)', 'Bagaimana layanannya? (Opsional)', 'كيف كانت الخدمة؟ (اختياري)') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'review.content_placeholder.supplier', 'review', '고객/반려동물에 대한 후기를 남겨주세요 (선택)', 'Leave a review for the customer/pet (Optional)', '顧客/ペットについてのレビューを残してください（任意）', '请留下对客户/宠物的评价（可选）', '請留下對客戶/寵物的評價（選填）', 'Deje una reseña del cliente/mascota (Opcional)', 'Laissez un avis sur le client/animal (Facultatif)', 'Hinterlassen Sie eine Bewertung für den Kunden/das Tier (Optional)', 'Deixe uma avaliação do cliente/pet (Opcional)', 'Để lại đánh giá cho khách hàng/thú cưng (Tùy chọn)', 'เขียนรีวิวลูกค้า/สัตว์เลี้ยง (ไม่บังคับ)', 'Tinggalkan ulasan untuk pelanggan/hewan (Opsional)', 'اترك تقييمًا للعميل/الحيوان الأليف (اختياري)') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'review.submit_btn', 'review', '후기 등록', 'Submit Review', 'レビューを投稿', '提交评价', '提交評價', 'Enviar reseña', 'Soumettre l''avis', 'Bewertung absenden', 'Enviar avaliação', 'Gửi đánh giá', 'ส่งรีวิว', 'Kirim Ulasan', 'إرسال التقييم') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'review.success_toast', 'review', '후기가 등록되었습니다', 'Review submitted', 'レビューが投稿されました', '评价已提交', '評價已提交', 'Reseña enviada', 'Avis soumis', 'Bewertung gesendet', 'Avaliação enviada', 'Đã gửi đánh giá', 'ส่งรีวิวแล้ว', 'Ulasan terkirim', 'تم إرسال التقييم') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'review.mutual_visible', 'review', '양측 후기 작성 완료 시 서로 열람 가능합니다', 'Both reviews become visible when both parties have written', '双方がレビューを書いた後に相互閲覧が可能になります', '双方都撰写评价后可互相查看', '雙方都撰寫評價後可互相查看', 'Ambas reseñas serán visibles cuando ambas partes hayan escrito', 'Les deux avis deviennent visibles lorsque les deux parties ont écrit', 'Beide Bewertungen werden sichtbar, wenn beide Parteien geschrieben haben', 'Ambas avaliações ficam visíveis quando ambas as partes escreveram', 'Cả hai đánh giá sẽ hiển thị khi cả hai bên đã viết', 'รีวิวทั้งสองจะมองเห็นได้เมื่อทั้งสองฝ่ายเขียนแล้ว', 'Kedua ulasan akan terlihat setelah kedua pihak menulis', 'ستظهر كلتا المراجعتين عندما يكتب كلا الطرفين') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'review.waiting_supplier', 'review', '공급자 후기 작성 후 열람 가능합니다', 'Visible after provider writes their review', '事業者がレビューを書いた後に閲覧可能になります', '供应商撰写评价后可查看', '供應商撰寫評價後可查看', 'Visible después de que el proveedor escriba su reseña', 'Visible après que le fournisseur ait écrit son avis', 'Sichtbar nachdem der Anbieter seine Bewertung geschrieben hat', 'Visível após o fornecedor escrever sua avaliação', 'Hiển thị sau khi nhà cung cấp viết đánh giá', 'จะมองเห็นได้หลังจากผู้ให้บริการเขียนรีวิว', 'Terlihat setelah penyedia menulis ulasan mereka', 'مرئي بعد كتابة مزود الخدمة لتقييمه') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'review.waiting_guardian', 'review', '고객 후기 작성 후 열람 가능합니다', 'Visible after customer writes their review', '顧客がレビューを書いた後に閲覧可能になります', '客户撰写评价后可查看', '客戶撰寫評價後可查看', 'Visible después de que el cliente escriba su reseña', 'Visible après que le client ait écrit son avis', 'Sichtbar nachdem der Kunde seine Bewertung geschrieben hat', 'Visível após o cliente escrever sua avaliação', 'Hiển thị sau khi khách hàng viết đánh giá', 'จะมองเห็นได้หลังจากลูกค้าเขียนรีวิว', 'Terlihat setelah pelanggan menulis ulasan mereka', 'مرئي بعد كتابة العميل لتقييمه') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'review.avg_rating', 'review', '평균 평점', 'Average Rating', '平均評価', '平均评分', '平均評分', 'Puntuación promedio', 'Note moyenne', 'Durchschnittsbewertung', 'Avaliação média', 'Đánh giá trung bình', 'คะแนนเฉลี่ย', 'Penilaian Rata-rata', 'متوسط التقييم') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'review.from_guardian', 'review', '고객 후기', 'Customer Review', '顧客レビュー', '客户评价', '客戶評價', 'Reseña del cliente', 'Avis du client', 'Kundenbewertung', 'Avaliação do cliente', 'Đánh giá của khách hàng', 'รีวิวจากลูกค้า', 'Ulasan Pelanggan', 'تقييم العميل') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'review.from_supplier', 'review', '공급자 후기', 'Provider Review', '事業者レビュー', '供应商评价', '供應商評價', 'Reseña del proveedor', 'Avis du fournisseur', 'Anbieterbewertung', 'Avaliação do fornecedor', 'Đánh giá của nhà cung cấp', 'รีวิวจากผู้ให้บริการ', 'Ulasan Penyedia', 'تقييم مزود الخدمة') ON CONFLICT (key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Record migration
-- ---------------------------------------------------------------------------
INSERT INTO schema_migrations (version)
VALUES ('008_booking_i18n')
ON CONFLICT (version) DO NOTHING;
