-- 012: i18n keys for supplier service registration + guardian service display
-- supplier service form
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.add_title', 'supplier', '서비스 등록', 'Add Service', 'サービス登録', '添加服务', '新增服務', 'Agregar servicio', 'Ajouter un service', 'Service hinzufügen', 'Adicionar serviço', 'Thêm dịch vụ', 'เพิ่มบริการ', 'Tambah layanan', 'إضافة خدمة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.edit_title', 'supplier', '서비스 수정', 'Edit Service', 'サービス編集', '编辑服务', '編輯服務', 'Editar servicio', 'Modifier le service', 'Service bearbeiten', 'Editar serviço', 'Sửa dịch vụ', 'แก้ไขบริการ', 'Edit layanan', 'تعديل الخدمة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.name_label', 'supplier', '서비스명', 'Service Name', 'サービス名', '服务名称', '服務名稱', 'Nombre del servicio', 'Nom du service', 'Servicename', 'Nome do serviço', 'Tên dịch vụ', 'ชื่อบริการ', 'Nama layanan', 'اسم الخدمة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.name_placeholder', 'supplier', '서비스명을 입력해주세요', 'Enter service name', 'サービス名を入力してください', '请输入服务名称', '請輸入服務名稱', 'Ingrese el nombre del servicio', 'Entrez le nom du service', 'Servicename eingeben', 'Insira o nome do serviço', 'Nhập tên dịch vụ', 'กรอกชื่อบริการ', 'Masukkan nama layanan', 'أدخل اسم الخدمة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.cut_label', 'supplier', '연결 컷 종류', 'Cut Style', 'カットスタイル', '剪裁类型', '剪裁類型', 'Estilo de corte', 'Style de coupe', 'Schnittstil', 'Estilo de corte', 'Kiểu cắt', 'สไตล์การตัด', 'Gaya potong', 'نمط القص') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.cut_placeholder', 'supplier', '컷 종류를 선택해주세요', 'Select cut style', 'カットスタイルを選択', '请选择剪裁类型', '請選擇剪裁類型', 'Seleccione estilo de corte', 'Sélectionnez le style de coupe', 'Schnittstil auswählen', 'Selecione o estilo de corte', 'Chọn kiểu cắt', 'เลือกสไตล์การตัด', 'Pilih gaya potong', 'اختر نمط القص') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.cut_none', 'supplier', '컷 미지정 (일반 서비스)', 'No cut (general service)', 'カットなし（一般サービス）', '无剪裁（一般服务）', '無剪裁（一般服務）', 'Sin corte (servicio general)', 'Pas de coupe (service général)', 'Kein Schnitt (allgemeiner Service)', 'Sem corte (serviço geral)', 'Không cắt (dịch vụ chung)', 'ไม่มีการตัด (บริการทั่วไป)', 'Tanpa potongan (layanan umum)', 'بدون قص (خدمة عامة)') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.pet_label', 'supplier', '대상 펫 종류', 'Target Pet Type', '対象ペット種類', '目标宠物类型', '目標寵物類型', 'Tipo de mascota', 'Type d''animal cible', 'Ziel-Haustierart', 'Tipo de pet alvo', 'Loại thú cưng mục tiêu', 'ประเภทสัตว์เลี้ยงเป้าหมาย', 'Jenis hewan target', 'نوع الحيوان المستهدف') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.price_label', 'supplier', '가격', 'Price', '価格', '价格', '價格', 'Precio', 'Prix', 'Preis', 'Preço', 'Giá', 'ราคา', 'Harga', 'السعر') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.price_placeholder', 'supplier', '가격을 입력해주세요', 'Enter price', '価格を入力してください', '请输入价格', '請輸入價格', 'Ingrese el precio', 'Entrez le prix', 'Preis eingeben', 'Insira o preço', 'Nhập giá', 'กรอกราคา', 'Masukkan harga', 'أدخل السعر') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.price_unit', 'supplier', '원', 'KRW', '円', '元', '元', 'KRW', 'KRW', 'KRW', 'KRW', 'KRW', 'KRW', 'KRW', 'KRW') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.duration_label', 'supplier', '소요시간', 'Duration', '所要時間', '所需时间', '所需時間', 'Duración', 'Durée', 'Dauer', 'Duração', 'Thời gian', 'ระยะเวลา', 'Durasi', 'المدة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.duration_unit', 'supplier', '분', 'min', '分', '分钟', '分鐘', 'min', 'min', 'Min', 'min', 'phút', 'นาที', 'menit', 'دقيقة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.duration_select', 'supplier', '소요시간 선택', 'Select duration', '所要時間を選択', '选择所需时间', '選擇所需時間', 'Seleccionar duración', 'Sélectionner la durée', 'Dauer auswählen', 'Selecionar duração', 'Chọn thời gian', 'เลือกระยะเวลา', 'Pilih durasi', 'اختر المدة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.active_label', 'supplier', '판매중', 'Active', '販売中', '销售中', '銷售中', 'Activo', 'Actif', 'Aktiv', 'Ativo', 'Đang bán', 'เปิดใช้งาน', 'Aktif', 'نشط') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.add_btn', 'supplier', '서비스 추가', 'Add Service', 'サービス追加', '添加服务', '新增服務', 'Agregar servicio', 'Ajouter un service', 'Service hinzufügen', 'Adicionar serviço', 'Thêm dịch vụ', 'เพิ่มบริการ', 'Tambah layanan', 'إضافة خدمة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.save_btn', 'supplier', '저장', 'Save', '保存', '保存', '儲存', 'Guardar', 'Enregistrer', 'Speichern', 'Salvar', 'Lưu', 'บันทึก', 'Simpan', 'حفظ') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.delete_btn', 'supplier', '삭제', 'Delete', '削除', '删除', '刪除', 'Eliminar', 'Supprimer', 'Löschen', 'Excluir', 'Xóa', 'ลบ', 'Hapus', 'حذف') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.delete_confirm', 'supplier', '이 서비스를 삭제하시겠습니까?', 'Delete this service?', 'このサービスを削除しますか？', '确定删除此服务吗？', '確定刪除此服務嗎？', '¿Eliminar este servicio?', 'Supprimer ce service ?', 'Diesen Service löschen?', 'Excluir este serviço?', 'Xóa dịch vụ này?', 'ลบบริการนี้?', 'Hapus layanan ini?', 'حذف هذه الخدمة؟') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.save_success', 'supplier', '서비스가 저장되었습니다', 'Service saved', 'サービスが保存されました', '服务已保存', '服務已儲存', 'Servicio guardado', 'Service enregistré', 'Service gespeichert', 'Serviço salvo', 'Dịch vụ đã lưu', 'บันทึกบริการแล้ว', 'Layanan disimpan', 'تم حفظ الخدمة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.delete_success', 'supplier', '서비스가 삭제되었습니다', 'Service deleted', 'サービスが削除されました', '服务已删除', '服務已刪除', 'Servicio eliminado', 'Service supprimé', 'Service gelöscht', 'Serviço excluído', 'Dịch vụ đã xóa', 'ลบบริการแล้ว', 'Layanan dihapus', 'تم حذف الخدمة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'supplier.service.pet_select_first', 'supplier', '펫 종류를 먼저 선택해주세요', 'Select pet type first', 'まずペット種類を選択してください', '请先选择宠物类型', '請先選擇寵物類型', 'Seleccione primero el tipo de mascota', 'Sélectionnez d''abord le type d''animal', 'Wählen Sie zuerst die Haustierart', 'Selecione primeiro o tipo de pet', 'Chọn loại thú cưng trước', 'เลือกประเภทสัตว์เลี้ยงก่อน', 'Pilih jenis hewan terlebih dahulu', 'اختر نوع الحيوان أولاً') ON CONFLICT (key) DO NOTHING;
-- guardian service display
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'guardian.service.no_services', 'guardian', '등록된 서비스가 없습니다', 'No services available', '登録されたサービスはありません', '没有注册的服务', '沒有註冊的服務', 'No hay servicios disponibles', 'Aucun service disponible', 'Keine Services verfügbar', 'Nenhum serviço disponível', 'Không có dịch vụ', 'ไม่มีบริการ', 'Tidak ada layanan', 'لا توجد خدمات متاحة') ON CONFLICT (key) DO NOTHING;
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar) VALUES (gen_random_uuid()::text, 'guardian.service.all_pets', 'guardian', '전체 보기', 'View All', 'すべて表示', '查看全部', '查看全部', 'Ver todo', 'Voir tout', 'Alle anzeigen', 'Ver tudo', 'Xem tất cả', 'ดูทั้งหมด', 'Lihat semua', 'عرض الكل') ON CONFLICT (key) DO NOTHING;
