-- 067_stores_services_i18n.sql — S9: 매장/서비스/할인 i18n 키 등록
-- ~60 keys for admin store management, services, discounts, guardian store browsing

-- ─── Admin Nav ────────────────────────────────────────────────────────────────
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at)
VALUES
(gen_random_uuid(), 'admin.nav.stores', 'admin', '매장 관리', 'Store Management', '店舗管理', '店铺管理', '店鋪管理', 'Gestión de tiendas', 'Gestion des magasins', 'Filialverwaltung', 'Gestão de lojas', 'Quản lý cửa hàng', 'จัดการร้านค้า', 'Manajemen Toko', 'إدارة المتاجر', true, NOW(), NOW())
ON CONFLICT (key) DO NOTHING;

-- ─── Admin Store Page ─────────────────────────────────────────────────────────
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at)
VALUES
(gen_random_uuid(), 'admin.store.page_title', 'admin', '매장 관리', 'Store Management', '店舗管理', '店铺管理', '店鋪管理', 'Gestión de tiendas', 'Gestion des magasins', 'Filialverwaltung', 'Gestão de lojas', 'Quản lý cửa hàng', 'จัดการร้านค้า', 'Manajemen Toko', 'إدارة المتاجر', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.list.title', 'admin', '매장 목록', 'Store List', '店舗一覧', '店铺列表', '店鋪列表', 'Lista de tiendas', 'Liste des magasins', 'Filialliste', 'Lista de lojas', 'Danh sách cửa hàng', 'รายการร้านค้า', 'Daftar Toko', 'قائمة المتاجر', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.list.empty', 'admin', '등록된 매장이 없습니다', 'No stores registered', '登録された店舗がありません', '没有已注册的店铺', '沒有已註冊的店鋪', 'No hay tiendas registradas', 'Aucun magasin enregistré', 'Keine Filialen registriert', 'Nenhuma loja registrada', 'Chưa có cửa hàng nào', 'ยังไม่มีร้านค้า', 'Belum ada toko terdaftar', 'لا توجد متاجر مسجلة', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.list.search', 'admin', '매장 검색...', 'Search stores...', '店舗を検索...', '搜索店铺...', '搜尋店鋪...', 'Buscar tiendas...', 'Rechercher des magasins...', 'Filialen suchen...', 'Pesquisar lojas...', 'Tìm cửa hàng...', 'ค้นหาร้านค้า...', 'Cari toko...', 'البحث عن متاجر...', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.form.name', 'admin', '매장 이름', 'Store Name', '店舗名', '店铺名称', '店鋪名稱', 'Nombre de tienda', 'Nom du magasin', 'Filialname', 'Nome da loja', 'Tên cửa hàng', 'ชื่อร้านค้า', 'Nama Toko', 'اسم المتجر', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.form.description', 'admin', '설명', 'Description', '説明', '描述', '描述', 'Descripción', 'Description', 'Beschreibung', 'Descrição', 'Mô tả', 'คำอธิบาย', 'Deskripsi', 'الوصف', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.form.address', 'admin', '주소', 'Address', '住所', '地址', '地址', 'Dirección', 'Adresse', 'Adresse', 'Endereço', 'Địa chỉ', 'ที่อยู่', 'Alamat', 'العنوان', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.form.phone', 'admin', '전화번호', 'Phone', '電話番号', '电话号码', '電話號碼', 'Teléfono', 'Téléphone', 'Telefon', 'Telefone', 'Số điện thoại', 'โทรศัพท์', 'Telepon', 'الهاتف', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.form.country', 'admin', '국가', 'Country', '国', '国家', '國家', 'País', 'Pays', 'Land', 'País', 'Quốc gia', 'ประเทศ', 'Negara', 'الدولة', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.form.currency', 'admin', '통화', 'Currency', '通貨', '货币', '貨幣', 'Moneda', 'Devise', 'Währung', 'Moeda', 'Tiền tệ', 'สกุลเงิน', 'Mata Uang', 'العملة', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.form.industries', 'admin', '업종', 'Industries', '業種', '行业', '行業', 'Industrias', 'Industries', 'Branchen', 'Indústrias', 'Ngành nghề', 'ประเภทธุรกิจ', 'Industri', 'الصناعات', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.form.avatar', 'admin', '매장 이미지', 'Store Image', '店舗画像', '店铺图片', '店鋪圖片', 'Imagen de tienda', 'Image du magasin', 'Filialbild', 'Imagem da loja', 'Hình cửa hàng', 'รูปร้านค้า', 'Gambar Toko', 'صورة المتجر', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.form.latitude', 'admin', '위도', 'Latitude', '緯度', '纬度', '緯度', 'Latitud', 'Latitude', 'Breitengrad', 'Latitude', 'Vĩ độ', 'ละติจูด', 'Lintang', 'خط العرض', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.form.longitude', 'admin', '경도', 'Longitude', '経度', '经度', '經度', 'Longitud', 'Longitude', 'Längengrad', 'Longitude', 'Kinh độ', 'ลองจิจูด', 'Bujur', 'خط الطول', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.action.create', 'admin', '매장 등록', 'Create Store', '店舗登録', '创建店铺', '建立店鋪', 'Crear tienda', 'Créer un magasin', 'Filiale erstellen', 'Criar loja', 'Tạo cửa hàng', 'สร้างร้านค้า', 'Buat Toko', 'إنشاء متجر', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.action.edit', 'admin', '매장 수정', 'Edit Store', '店舗編集', '编辑店铺', '編輯店鋪', 'Editar tienda', 'Modifier le magasin', 'Filiale bearbeiten', 'Editar loja', 'Sửa cửa hàng', 'แก้ไขร้านค้า', 'Edit Toko', 'تعديل المتجر', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.action.delete', 'admin', '매장 비활성화', 'Deactivate Store', '店舗無効化', '停用店铺', '停用店鋪', 'Desactivar tienda', 'Désactiver le magasin', 'Filiale deaktivieren', 'Desativar loja', 'Vô hiệu hóa cửa hàng', 'ปิดใช้งานร้านค้า', 'Nonaktifkan Toko', 'تعطيل المتجر', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.action.save', 'admin', '저장', 'Save', '保存', '保存', '儲存', 'Guardar', 'Enregistrer', 'Speichern', 'Salvar', 'Lưu', 'บันทึก', 'Simpan', 'حفظ', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.action.cancel', 'admin', '취소', 'Cancel', 'キャンセル', '取消', '取消', 'Cancelar', 'Annuler', 'Abbrechen', 'Cancelar', 'Hủy', 'ยกเลิก', 'Batal', 'إلغاء', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.alert.created', 'admin', '매장이 등록되었습니다', 'Store created successfully', '店舗が登録されました', '店铺创建成功', '店鋪建立成功', 'Tienda creada exitosamente', 'Magasin créé avec succès', 'Filiale erfolgreich erstellt', 'Loja criada com sucesso', 'Tạo cửa hàng thành công', 'สร้างร้านค้าสำเร็จ', 'Toko berhasil dibuat', 'تم إنشاء المتجر بنجاح', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.alert.updated', 'admin', '매장 정보가 수정되었습니다', 'Store updated successfully', '店舗情報が更新されました', '店铺更新成功', '店鋪更新成功', 'Tienda actualizada exitosamente', 'Magasin mis à jour avec succès', 'Filiale erfolgreich aktualisiert', 'Loja atualizada com sucesso', 'Cập nhật cửa hàng thành công', 'อัปเดตร้านค้าสำเร็จ', 'Toko berhasil diperbarui', 'تم تحديث المتجر بنجاح', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.alert.deleted', 'admin', '매장이 비활성화되었습니다', 'Store deactivated', '店舗が無効化されました', '店铺已停用', '店鋪已停用', 'Tienda desactivada', 'Magasin désactivé', 'Filiale deaktiviert', 'Loja desativada', 'Đã vô hiệu hóa cửa hàng', 'ปิดใช้งานร้านค้าแล้ว', 'Toko dinonaktifkan', 'تم تعطيل المتجر', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.alert.failed', 'admin', '작업에 실패했습니다', 'Operation failed', '操作に失敗しました', '操作失败', '操作失敗', 'Operación fallida', 'Opération échouée', 'Vorgang fehlgeschlagen', 'Operação falhou', 'Thao tác thất bại', 'ดำเนินการไม่สำเร็จ', 'Operasi gagal', 'فشلت العملية', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.status.active', 'admin', '활성', 'Active', 'アクティブ', '活跃', '活躍', 'Activo', 'Actif', 'Aktiv', 'Ativo', 'Hoạt động', 'ใช้งาน', 'Aktif', 'نشط', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.store.status.inactive', 'admin', '비활성', 'Inactive', '非アクティブ', '非活跃', '非活躍', 'Inactivo', 'Inactif', 'Inaktiv', 'Inativo', 'Không hoạt động', 'ไม่ใช้งาน', 'Tidak Aktif', 'غير نشط', true, NOW(), NOW())
ON CONFLICT (key) DO NOTHING;

-- ─── Admin Service ────────────────────────────────────────────────────────────
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at)
VALUES
(gen_random_uuid(), 'admin.service.list.title', 'admin', '서비스 목록', 'Service List', 'サービス一覧', '服务列表', '服務列表', 'Lista de servicios', 'Liste des services', 'Serviceliste', 'Lista de serviços', 'Danh sách dịch vụ', 'รายการบริการ', 'Daftar Layanan', 'قائمة الخدمات', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.service.list.empty', 'admin', '등록된 서비스가 없습니다', 'No services registered', '登録されたサービスがありません', '没有已注册的服务', '沒有已註冊的服務', 'No hay servicios registrados', 'Aucun service enregistré', 'Keine Services registriert', 'Nenhum serviço registrado', 'Chưa có dịch vụ nào', 'ยังไม่มีบริการ', 'Belum ada layanan terdaftar', 'لا توجد خدمات مسجلة', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.service.form.name', 'admin', '서비스 이름', 'Service Name', 'サービス名', '服务名称', '服務名稱', 'Nombre del servicio', 'Nom du service', 'Servicename', 'Nome do serviço', 'Tên dịch vụ', 'ชื่อบริการ', 'Nama Layanan', 'اسم الخدمة', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.service.form.description', 'admin', '서비스 설명', 'Service Description', 'サービス説明', '服务描述', '服務描述', 'Descripción del servicio', 'Description du service', 'Servicebeschreibung', 'Descrição do serviço', 'Mô tả dịch vụ', 'คำอธิบายบริการ', 'Deskripsi Layanan', 'وصف الخدمة', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.service.form.price', 'admin', '가격', 'Price', '価格', '价格', '價格', 'Precio', 'Prix', 'Preis', 'Preço', 'Giá', 'ราคา', 'Harga', 'السعر', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.service.form.photos', 'admin', '사진', 'Photos', '写真', '照片', '照片', 'Fotos', 'Photos', 'Fotos', 'Fotos', 'Ảnh', 'รูปภาพ', 'Foto', 'الصور', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.service.form.sort_order', 'admin', '정렬 순서', 'Sort Order', '表示順', '排序', '排序', 'Orden', 'Ordre', 'Reihenfolge', 'Ordem', 'Thứ tự', 'ลำดับ', 'Urutan', 'الترتيب', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.service.action.create', 'admin', '서비스 등록', 'Add Service', 'サービス登録', '添加服务', '新增服務', 'Agregar servicio', 'Ajouter un service', 'Service hinzufügen', 'Adicionar serviço', 'Thêm dịch vụ', 'เพิ่มบริการ', 'Tambah Layanan', 'إضافة خدمة', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.service.action.edit', 'admin', '서비스 수정', 'Edit Service', 'サービス編集', '编辑服务', '編輯服務', 'Editar servicio', 'Modifier le service', 'Service bearbeiten', 'Editar serviço', 'Sửa dịch vụ', 'แก้ไขบริการ', 'Edit Layanan', 'تعديل الخدمة', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.service.action.delete', 'admin', '서비스 삭제', 'Delete Service', 'サービス削除', '删除服务', '刪除服務', 'Eliminar servicio', 'Supprimer le service', 'Service löschen', 'Excluir serviço', 'Xóa dịch vụ', 'ลบบริการ', 'Hapus Layanan', 'حذف الخدمة', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.service.alert.created', 'admin', '서비스가 등록되었습니다', 'Service created successfully', 'サービスが登録されました', '服务创建成功', '服務建立成功', 'Servicio creado exitosamente', 'Service créé avec succès', 'Service erfolgreich erstellt', 'Serviço criado com sucesso', 'Tạo dịch vụ thành công', 'สร้างบริการสำเร็จ', 'Layanan berhasil dibuat', 'تم إنشاء الخدمة بنجاح', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.service.alert.updated', 'admin', '서비스가 수정되었습니다', 'Service updated successfully', 'サービスが更新されました', '服务更新成功', '服務更新成功', 'Servicio actualizado exitosamente', 'Service mis à jour avec succès', 'Service erfolgreich aktualisiert', 'Serviço atualizado com sucesso', 'Cập nhật dịch vụ thành công', 'อัปเดตบริการสำเร็จ', 'Layanan berhasil diperbarui', 'تم تحديث الخدمة بنجاح', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.service.alert.deleted', 'admin', '서비스가 삭제되었습니다', 'Service deleted', 'サービスが削除されました', '服务已删除', '服務已刪除', 'Servicio eliminado', 'Service supprimé', 'Service gelöscht', 'Serviço excluído', 'Đã xóa dịch vụ', 'ลบบริการแล้ว', 'Layanan dihapus', 'تم حذف الخدمة', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.service.alert.failed', 'admin', '서비스 작업에 실패했습니다', 'Service operation failed', 'サービス操作に失敗しました', '服务操作失败', '服務操作失敗', 'Operación de servicio fallida', 'Opération de service échouée', 'Servicevorgang fehlgeschlagen', 'Operação de serviço falhou', 'Thao tác dịch vụ thất bại', 'ดำเนินการบริการไม่สำเร็จ', 'Operasi layanan gagal', 'فشلت عملية الخدمة', true, NOW(), NOW())
ON CONFLICT (key) DO NOTHING;

-- ─── Admin Discount ───────────────────────────────────────────────────────────
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at)
VALUES
(gen_random_uuid(), 'admin.discount.list.title', 'admin', '할인 목록', 'Discount List', '割引一覧', '折扣列表', '折扣列表', 'Lista de descuentos', 'Liste des réductions', 'Rabattliste', 'Lista de descontos', 'Danh sách giảm giá', 'รายการส่วนลด', 'Daftar Diskon', 'قائمة الخصومات', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.discount.list.empty', 'admin', '등록된 할인이 없습니다', 'No discounts registered', '登録された割引がありません', '没有已注册的折扣', '沒有已註冊的折扣', 'No hay descuentos registrados', 'Aucune réduction enregistrée', 'Keine Rabatte registriert', 'Nenhum desconto registrado', 'Chưa có giảm giá nào', 'ยังไม่มีส่วนลด', 'Belum ada diskon terdaftar', 'لا توجد خصومات مسجلة', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.discount.form.rate', 'admin', '할인율 (%)', 'Discount Rate (%)', '割引率 (%)', '折扣率 (%)', '折扣率 (%)', 'Tasa de descuento (%)', 'Taux de réduction (%)', 'Rabatt (%)', 'Taxa de desconto (%)', 'Tỷ lệ giảm giá (%)', 'อัตราส่วนลด (%)', 'Tingkat Diskon (%)', 'نسبة الخصم (%)', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.discount.form.start_date', 'admin', '시작일', 'Start Date', '開始日', '开始日期', '開始日期', 'Fecha de inicio', 'Date de début', 'Startdatum', 'Data de início', 'Ngày bắt đầu', 'วันที่เริ่มต้น', 'Tanggal Mulai', 'تاريخ البداية', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.discount.form.end_date', 'admin', '종료일', 'End Date', '終了日', '结束日期', '結束日期', 'Fecha de fin', 'Date de fin', 'Enddatum', 'Data de término', 'Ngày kết thúc', 'วันที่สิ้นสุด', 'Tanggal Berakhir', 'تاريخ النهاية', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.discount.action.create', 'admin', '할인 등록', 'Add Discount', '割引登録', '添加折扣', '新增折扣', 'Agregar descuento', 'Ajouter une réduction', 'Rabatt hinzufügen', 'Adicionar desconto', 'Thêm giảm giá', 'เพิ่มส่วนลด', 'Tambah Diskon', 'إضافة خصم', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.discount.action.delete', 'admin', '할인 삭제', 'Delete Discount', '割引削除', '删除折扣', '刪除折扣', 'Eliminar descuento', 'Supprimer la réduction', 'Rabatt löschen', 'Excluir desconto', 'Xóa giảm giá', 'ลบส่วนลด', 'Hapus Diskon', 'حذف الخصم', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.discount.alert.created', 'admin', '할인이 등록되었습니다', 'Discount created successfully', '割引が登録されました', '折扣创建成功', '折扣建立成功', 'Descuento creado exitosamente', 'Réduction créée avec succès', 'Rabatt erfolgreich erstellt', 'Desconto criado com sucesso', 'Tạo giảm giá thành công', 'สร้างส่วนลดสำเร็จ', 'Diskon berhasil dibuat', 'تم إنشاء الخصم بنجاح', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.discount.alert.deleted', 'admin', '할인이 삭제되었습니다', 'Discount deleted', '割引が削除されました', '折扣已删除', '折扣已刪除', 'Descuento eliminado', 'Réduction supprimée', 'Rabatt gelöscht', 'Desconto excluído', 'Đã xóa giảm giá', 'ลบส่วนลดแล้ว', 'Diskon dihapus', 'تم حذف الخصم', true, NOW(), NOW()),
(gen_random_uuid(), 'admin.discount.alert.failed', 'admin', '할인 작업에 실패했습니다', 'Discount operation failed', '割引操作に失敗しました', '折扣操作失败', '折扣操作失敗', 'Operación de descuento fallida', 'Opération de réduction échouée', 'Rabattvorgang fehlgeschlagen', 'Operação de desconto falhou', 'Thao tác giảm giá thất bại', 'ดำเนินการส่วนลดไม่สำเร็จ', 'Operasi diskon gagal', 'فشلت عملية الخصم', true, NOW(), NOW())
ON CONFLICT (key) DO NOTHING;

-- ─── Guardian Store Browsing ──────────────────────────────────────────────────
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at)
VALUES
(gen_random_uuid(), 'guardian.store.browse', 'guardian', '매장 탐색', 'Browse Stores', '店舗を探す', '浏览店铺', '瀏覽店鋪', 'Explorar tiendas', 'Parcourir les magasins', 'Filialen durchsuchen', 'Explorar lojas', 'Duyệt cửa hàng', 'เรียกดูร้านค้า', 'Jelajahi Toko', 'تصفح المتاجر', true, NOW(), NOW()),
(gen_random_uuid(), 'guardian.store.search', 'guardian', '매장 검색...', 'Search stores...', '店舗を検索...', '搜索店铺...', '搜尋店鋪...', 'Buscar tiendas...', 'Rechercher des magasins...', 'Filialen suchen...', 'Pesquisar lojas...', 'Tìm cửa hàng...', 'ค้นหาร้านค้า...', 'Cari toko...', 'البحث عن متاجر...', true, NOW(), NOW()),
(gen_random_uuid(), 'guardian.store.detail', 'guardian', '매장 상세', 'Store Details', '店舗詳細', '店铺详情', '店鋪詳情', 'Detalles de la tienda', 'Détails du magasin', 'Filialdetails', 'Detalhes da loja', 'Chi tiết cửa hàng', 'รายละเอียดร้านค้า', 'Detail Toko', 'تفاصيل المتجر', true, NOW(), NOW()),
(gen_random_uuid(), 'guardian.store.services', 'guardian', '서비스', 'Services', 'サービス', '服务', '服務', 'Servicios', 'Services', 'Services', 'Serviços', 'Dịch vụ', 'บริการ', 'Layanan', 'الخدمات', true, NOW(), NOW()),
(gen_random_uuid(), 'guardian.store.book', 'guardian', '예약하기', 'Book Now', '予約する', '立即预约', '立即預約', 'Reservar ahora', 'Réserver', 'Jetzt buchen', 'Reservar agora', 'Đặt lịch', 'จองตอนนี้', 'Pesan Sekarang', 'احجز الآن', true, NOW(), NOW()),
(gen_random_uuid(), 'guardian.store.no_services', 'guardian', '등록된 서비스가 없습니다', 'No services available', '利用可能なサービスがありません', '暂无可用服务', '暫無可用服務', 'No hay servicios disponibles', 'Aucun service disponible', 'Keine Services verfügbar', 'Nenhum serviço disponível', 'Không có dịch vụ', 'ไม่มีบริการ', 'Tidak ada layanan', 'لا توجد خدمات متاحة', true, NOW(), NOW()),
(gen_random_uuid(), 'guardian.store.discount_badge', 'guardian', '할인 중', 'On Sale', 'セール中', '打折中', '折扣中', 'En oferta', 'En promotion', 'Im Angebot', 'Em promoção', 'Đang giảm giá', 'ลดราคา', 'Diskon', 'تخفيض', true, NOW(), NOW())
ON CONFLICT (key) DO NOTHING;

-- ─── Provider Store Management ────────────────────────────────────────────────
INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at)
VALUES
(gen_random_uuid(), 'provider.store.my_stores', 'provider', '내 매장', 'My Stores', 'マイ店舗', '我的店铺', '我的店鋪', 'Mis tiendas', 'Mes magasins', 'Meine Filialen', 'Minhas lojas', 'Cửa hàng của tôi', 'ร้านค้าของฉัน', 'Toko Saya', 'متاجري', true, NOW(), NOW()),
(gen_random_uuid(), 'provider.store.create', 'provider', '매장 등록', 'Register Store', '店舗登録', '注册店铺', '註冊店鋪', 'Registrar tienda', 'Enregistrer un magasin', 'Filiale registrieren', 'Registrar loja', 'Đăng ký cửa hàng', 'ลงทะเบียนร้านค้า', 'Daftarkan Toko', 'تسجيل متجر', true, NOW(), NOW()),
(gen_random_uuid(), 'provider.store.services_count', 'provider', '서비스 {count}개', '{count} services', 'サービス {count}件', '{count}个服务', '{count}個服務', '{count} servicios', '{count} services', '{count} Services', '{count} serviços', '{count} dịch vụ', '{count} บริการ', '{count} layanan', '{count} خدمات', true, NOW(), NOW()),
(gen_random_uuid(), 'provider.store.no_stores', 'provider', '등록된 매장이 없습니다. 매장을 등록해보세요!', 'No stores yet. Register your first store!', 'まだ店舗がありません。最初の店舗を登録しましょう！', '还没有店铺，注册您的第一家店铺吧！', '還沒有店鋪，註冊您的第一家店鋪吧！', '¡Aún no hay tiendas. Registra tu primera tienda!', 'Aucun magasin encore. Enregistrez votre premier magasin !', 'Noch keine Filialen. Registrieren Sie Ihre erste Filiale!', 'Nenhuma loja ainda. Registre sua primeira loja!', 'Chưa có cửa hàng. Hãy đăng ký cửa hàng đầu tiên!', 'ยังไม่มีร้านค้า ลงทะเบียนร้านค้าแรกของคุณ!', 'Belum ada toko. Daftarkan toko pertama Anda!', 'لا توجد متاجر بعد. سجّل متجرك الأول!', true, NOW(), NOW())
ON CONFLICT (key) DO NOTHING;
