-- 076: i18n keys for provider signup Step 3 — enhanced business registration form
-- Language toggle, business info popovers, address, operating hours, certifications

INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at)
VALUES

-- ── Language toggle ────────────────────────────────────────────────────────────
(md5('i18n_ps_lang_toggle'), 'public.signup.provider_lang_toggle', 'public', '한국어 / English', 'Korean / English', '韓国語 / English', '韩语 / English', '韓語 / English', 'Coreano / English', 'Coréen / English', 'Koreanisch / English', 'Coreano / English', 'Hàn / English', 'เกาหลี / English', 'Korea / English', 'كورية / English', true, NOW(), NOW()),

-- ── Business info popovers (5 categories) ──────────────────────────────────────
(md5('i18n_ps_info_hospital'), 'public.signup.provider_info_hospital', 'public', '동물병원: 수의사 면허가 필요하며, 진료·수술·예방접종 등 의료 서비스를 제공합니다.', 'Veterinary Hospital: Requires a veterinary license. Provides medical services including treatment, surgery, and vaccinations.', '動物病院：獣医師免許が必要です。診療・手術・予防接種などの医療サービスを提供します。', '动物医院：需要兽医执照，提供诊疗、手术、疫苗等医疗服务。', '動物醫院：需要獸醫執照，提供診療、手術、疫苗等醫療服務。', 'Hospital Veterinario: Requiere licencia veterinaria. Ofrece servicios médicos como tratamiento, cirugía y vacunación.', 'Hôpital Vétérinaire : Nécessite une licence vétérinaire. Fournit des services médicaux.', 'Tierklinik: Erfordert eine Tierarztlizenz. Bietet medizinische Dienstleistungen an.', 'Hospital Veterinário: Requer licença veterinária. Oferece serviços médicos.', 'Bệnh viện thú y: Cần có giấy phép thú y. Cung cấp dịch vụ y tế.', 'โรงพยาบาลสัตว์: ต้องมีใบอนุญาตสัตวแพทย์ ให้บริการทางการแพทย์', 'Rumah Sakit Hewan: Memerlukan izin dokter hewan. Menyediakan layanan medis.', 'مستشفى بيطري: يتطلب ترخيص بيطري. يقدم خدمات طبية.', true, NOW(), NOW()),

(md5('i18n_ps_info_grooming'), 'public.signup.provider_info_grooming', 'public', '미용실: 반려동물 미용·목욕·스파 서비스를 제공합니다. 미용사 자격증이 필요할 수 있습니다.', 'Grooming Salon: Provides grooming, bathing, and spa services for pets. Groomer certification may be required.', 'トリミングサロン：ペットのトリミング・入浴・スパサービスを提供します。', '美容院：提供宠物美容、洗澡、SPA服务。可能需要美容师资格证。', '美容院：提供寵物美容、洗澡、SPA服務。可能需要美容師資格證。', 'Peluquería: Ofrece servicios de peluquería, baño y spa para mascotas.', 'Salon de Toilettage : Offre des services de toilettage, bain et spa pour animaux.', 'Tiersalon: Bietet Pflege-, Bade- und Spa-Dienste für Haustiere an.', 'Salão de Beleza: Oferece serviços de beleza, banho e spa para pets.', 'Tiệm cắt tỉa: Cung cấp dịch vụ cắt tỉa, tắm và spa cho thú cưng.', 'ร้านตัดขน: ให้บริการตัดขน อาบน้ำ และสปาสำหรับสัตว์เลี้ยง', 'Salon Grooming: Menyediakan layanan grooming, mandi, dan spa untuk hewan peliharaan.', 'صالون تجميل: يقدم خدمات التجميل والاستحمام والسبا للحيوانات الأليفة.', true, NOW(), NOW()),

(md5('i18n_ps_info_petshop'), 'public.signup.provider_info_petshop', 'public', '펫샵: 반려동물 용품·사료·간식 등을 판매합니다. 생체 판매 시 별도 허가가 필요합니다.', 'Pet Shop: Sells pet supplies, food, and treats. Live animal sales require additional permits.', 'ペットショップ：ペット用品・フード・おやつ等を販売します。生体販売には別途許可が必要です。', '宠物店：销售宠物用品、饲料、零食等。活体销售需要额外许可。', '寵物店：銷售寵物用品、飼料、零食等。活體銷售需要額外許可。', 'Tienda de Mascotas: Vende suministros, alimentos y golosinas para mascotas.', 'Animalerie : Vend des fournitures, de la nourriture et des friandises pour animaux.', 'Tierhandlung: Verkauft Heimtierbedarf, Futter und Leckerlis.', 'Pet Shop: Vende suprimentos, rações e petiscos para pets.', 'Cửa hàng thú cưng: Bán đồ dùng, thức ăn và đồ ăn vặt cho thú cưng.', 'ร้านสัตว์เลี้ยง: จำหน่ายอุปกรณ์ อาหาร และขนมสำหรับสัตว์เลี้ยง', 'Pet Shop: Menjual perlengkapan, makanan, dan camilan hewan peliharaan.', 'متجر حيوانات: يبيع مستلزمات وأغذية ومكافآت الحيوانات الأليفة.', true, NOW(), NOW()),

(md5('i18n_ps_info_hotel'), 'public.signup.provider_info_hotel', 'public', '펫호텔: 반려동물 돌봄·위탁·데이케어 서비스를 제공합니다.', 'Pet Hotel: Provides pet boarding, daycare, and overnight care services.', 'ペットホテル：ペットの預かり・デイケアサービスを提供します。', '宠物酒店：提供宠物寄养、日托和过夜看护服务。', '寵物旅館：提供寵物寄養、日托和過夜看護服務。', 'Hotel para Mascotas: Ofrece servicios de alojamiento, guardería y cuidado nocturno.', 'Hôtel pour Animaux : Offre des services de pension, garderie et garde de nuit.', 'Tierhotel: Bietet Tierpension, Tagesbetreuung und Nachtpflege an.', 'Hotel Pet: Oferece serviços de hospedagem, creche e cuidados noturnos.', 'Khách sạn thú cưng: Cung cấp dịch vụ trông giữ, chăm sóc ban ngày và qua đêm.', 'โรงแรมสัตว์เลี้ยง: ให้บริการรับฝาก ดูแลกลางวัน และดูแลค้างคืน', 'Hotel Hewan: Menyediakan layanan penitipan, penitipan harian, dan perawatan menginap.', 'فندق حيوانات: يقدم خدمات الإيواء والرعاية النهارية والليلية.', true, NOW(), NOW()),

(md5('i18n_ps_info_training'), 'public.signup.provider_info_training', 'public', '훈련소: 반려동물 행동 교정·복종 훈련·사회화 프로그램을 제공합니다. 훈련사 자격증이 필요할 수 있습니다.', 'Training Center: Provides behavior correction, obedience training, and socialization programs. Trainer certification may be required.', '訓練所：行動矯正・服従訓練・社会化プログラムを提供します。', '训练中心：提供行为矫正、服从训练和社会化计划。可能需要训练师资格证。', '訓練中心：提供行為矯正、服從訓練和社會化計劃。可能需要訓練師資格證。', 'Centro de Entrenamiento: Ofrece corrección de comportamiento, entrenamiento de obediencia y socialización.', 'Centre de Dressage : Offre correction comportementale, obéissance et socialisation.', 'Trainingszentrum: Bietet Verhaltenskorrektur, Gehorsamkeitstraining und Sozialisation.', 'Centro de Treinamento: Oferece correção comportamental, treinamento de obediência e socialização.', 'Trung tâm huấn luyện: Cung cấp chương trình chỉnh hành vi, huấn luyện và xã hội hóa.', 'ศูนย์ฝึก: ให้บริการแก้ไขพฤติกรรม ฝึกเชื่อฟัง และโปรแกรมสังคม', 'Pusat Pelatihan: Menyediakan koreksi perilaku, pelatihan kepatuhan, dan sosialisasi.', 'مركز تدريب: يقدم تصحيح السلوك وتدريب الطاعة وبرامج التنشئة الاجتماعية.', true, NOW(), NOW()),

-- ── Address labels ──────────────────────────────────────────────────────────────
(md5('i18n_ps_addr_state'), 'public.signup.provider_address_state', 'public', '시/도', 'State/Province', '都道府県', '省/市', '省/市', 'Estado/Provincia', 'État/Province', 'Bundesland', 'Estado/Província', 'Tỉnh/Thành phố', 'จังหวัด', 'Provinsi', 'المحافظة', true, NOW(), NOW()),
(md5('i18n_ps_addr_city'), 'public.signup.provider_address_city', 'public', '시/군/구', 'City/District', '市区町村', '区/县', '區/縣', 'Ciudad/Distrito', 'Ville/District', 'Stadt/Bezirk', 'Cidade/Distrito', 'Quận/Huyện', 'อำเภอ/เขต', 'Kota/Kabupaten', 'المدينة/المنطقة', true, NOW(), NOW()),
(md5('i18n_ps_addr_detail'), 'public.signup.provider_address_detail', 'public', '상세 주소', 'Detailed Address', '詳細住所', '详细地址', '詳細地址', 'Dirección detallada', 'Adresse détaillée', 'Detaillierte Adresse', 'Endereço detalhado', 'Địa chỉ chi tiết', 'ที่อยู่โดยละเอียด', 'Alamat Lengkap', 'العنوان التفصيلي', true, NOW(), NOW()),
(md5('i18n_ps_addr_flat'), 'public.signup.provider_address_flat', 'public', '주소', 'Address', '住所', '地址', '地址', 'Dirección', 'Adresse', 'Adresse', 'Endereço', 'Địa chỉ', 'ที่อยู่', 'Alamat', 'العنوان', true, NOW(), NOW()),

-- ── Operating hours ─────────────────────────────────────────────────────────────
(md5('i18n_ps_hours_mon'), 'public.signup.provider_hours_mon', 'public', '월', 'Mon', '月', '一', '一', 'Lun', 'Lun', 'Mo', 'Seg', 'T2', 'จ.', 'Sen', 'الإثنين', true, NOW(), NOW()),
(md5('i18n_ps_hours_tue'), 'public.signup.provider_hours_tue', 'public', '화', 'Tue', '火', '二', '二', 'Mar', 'Mar', 'Di', 'Ter', 'T3', 'อ.', 'Sel', 'الثلاثاء', true, NOW(), NOW()),
(md5('i18n_ps_hours_wed'), 'public.signup.provider_hours_wed', 'public', '수', 'Wed', '水', '三', '三', 'Mié', 'Mer', 'Mi', 'Qua', 'T4', 'พ.', 'Rab', 'الأربعاء', true, NOW(), NOW()),
(md5('i18n_ps_hours_thu'), 'public.signup.provider_hours_thu', 'public', '목', 'Thu', '木', '四', '四', 'Jue', 'Jeu', 'Do', 'Qui', 'T5', 'พฤ.', 'Kam', 'الخميس', true, NOW(), NOW()),
(md5('i18n_ps_hours_fri'), 'public.signup.provider_hours_fri', 'public', '금', 'Fri', '金', '五', '五', 'Vie', 'Ven', 'Fr', 'Sex', 'T6', 'ศ.', 'Jum', 'الجمعة', true, NOW(), NOW()),
(md5('i18n_ps_hours_sat'), 'public.signup.provider_hours_sat', 'public', '토', 'Sat', '土', '六', '六', 'Sáb', 'Sam', 'Sa', 'Sáb', 'T7', 'ส.', 'Sab', 'السبت', true, NOW(), NOW()),
(md5('i18n_ps_hours_sun'), 'public.signup.provider_hours_sun', 'public', '일', 'Sun', '日', '日', '日', 'Dom', 'Dim', 'So', 'Dom', 'CN', 'อา.', 'Min', 'الأحد', true, NOW(), NOW()),
(md5('i18n_ps_hours_open'), 'public.signup.provider_hours_open', 'public', '오픈', 'Open', '開店', '开门', '開門', 'Apertura', 'Ouverture', 'Öffnung', 'Abertura', 'Mở cửa', 'เปิด', 'Buka', 'مفتوح', true, NOW(), NOW()),
(md5('i18n_ps_hours_close'), 'public.signup.provider_hours_close', 'public', '마감', 'Close', '閉店', '关门', '關門', 'Cierre', 'Fermeture', 'Schluss', 'Fechamento', 'Đóng cửa', 'ปิด', 'Tutup', 'مغلق', true, NOW(), NOW()),
(md5('i18n_ps_hours_closed'), 'public.signup.provider_hours_closed', 'public', '휴무', 'Closed', '定休日', '休息', '休息', 'Cerrado', 'Fermé', 'Geschlossen', 'Fechado', 'Nghỉ', 'หยุด', 'Libur', 'عطلة', true, NOW(), NOW()),
(md5('i18n_ps_hours_title'), 'public.signup.provider_hours_title', 'public', '운영 시간', 'Operating Hours', '営業時間', '营业时间', '營業時間', 'Horario de operación', 'Heures d''ouverture', 'Öffnungszeiten', 'Horário de funcionamento', 'Giờ hoạt động', 'เวลาทำการ', 'Jam Operasional', 'ساعات العمل', true, NOW(), NOW()),

-- ── Certifications ──────────────────────────────────────────────────────────────
(md5('i18n_ps_cert_add'), 'public.signup.provider_cert_add', 'public', '자격증 추가', 'Add Certificate', '資格証追加', '添加证书', '添加證書', 'Agregar certificado', 'Ajouter un certificat', 'Zertifikat hinzufügen', 'Adicionar certificado', 'Thêm chứng chỉ', 'เพิ่มใบรับรอง', 'Tambah Sertifikat', 'إضافة شهادة', true, NOW(), NOW()),
(md5('i18n_ps_cert_placeholder'), 'public.signup.provider_cert_placeholder', 'public', '자격증명을 입력하고 Enter', 'Type certificate name and press Enter', '資格名を入力してEnter', '输入证书名称并按Enter', '輸入證書名稱並按Enter', 'Escriba y presione Enter', 'Tapez et appuyez sur Entrée', 'Eingeben und Enter drücken', 'Digite e pressione Enter', 'Nhập và nhấn Enter', 'พิมพ์แล้วกด Enter', 'Ketik lalu tekan Enter', 'اكتب واضغط Enter', true, NOW(), NOW()),

-- ── Business info label ─────────────────────────────────────────────────────────
(md5('i18n_ps_biz_info'), 'public.signup.provider_biz_info', 'public', '업종 안내', 'Business Info', '業種案内', '行业说明', '行業說明', 'Info del negocio', 'Info entreprise', 'Brancheninfo', 'Info do negócio', 'Thông tin ngành', 'ข้อมูลธุรกิจ', 'Info Bisnis', 'معلومات العمل', true, NOW(), NOW())

ON CONFLICT (id) DO UPDATE SET
  ko = EXCLUDED.ko, en = EXCLUDED.en, ja = EXCLUDED.ja,
  zh_cn = EXCLUDED.zh_cn, zh_tw = EXCLUDED.zh_tw,
  es = EXCLUDED.es, fr = EXCLUDED.fr, de = EXCLUDED.de,
  pt = EXCLUDED.pt, vi = EXCLUDED.vi, th = EXCLUDED.th,
  id_lang = EXCLUDED.id_lang, ar = EXCLUDED.ar,
  updated_at = NOW();
