-- 090: i18n keys for appointment booking + grooming completion + guardian approval + feed display (13 languages)

INSERT INTO i18n_translations (id, key, page, ko, en, ja, zh_cn, zh_tw, es, fr, de, pt, vi, th, id_lang, ar, is_active, created_at, updated_at)
VALUES

-- ── Booking (Guardian) ─────────────────────────────────────────────────────
(md5('i18n_bk_title'),          'booking.title',            'booking', '예약 신청', 'Book Appointment', '予約申請', '预约申请', '預約申請', 'Reservar cita', 'Prendre rendez-vous', 'Termin buchen', 'Agendar consulta', 'Đặt lịch hẹn', 'จองนัดหมาย', 'Buat Janji', 'حجز موعد', true, NOW(), NOW()),
(md5('i18n_bk_pet_select'),     'booking.pet_select',       'booking', '반려동물 선택', 'Select Pet', 'ペットを選択', '选择宠物', '選擇寵物', 'Seleccionar mascota', 'Sélectionner un animal', 'Haustier wählen', 'Selecionar pet', 'Chọn thú cưng', 'เลือกสัตว์เลี้ยง', 'Pilih Hewan', 'اختيار الحيوان', true, NOW(), NOW()),
(md5('i18n_bk_service_select'), 'booking.service_select',   'booking', '서비스 선택', 'Select Service', 'サービスを選択', '选择服务', '選擇服務', 'Seleccionar servicio', 'Sélectionner un service', 'Service wählen', 'Selecionar serviço', 'Chọn dịch vụ', 'เลือกบริการ', 'Pilih Layanan', 'اختيار الخدمة', true, NOW(), NOW()),
(md5('i18n_bk_date_select'),    'booking.date_select',      'booking', '날짜 선택', 'Select Date', '日付を選択', '选择日期', '選擇日期', 'Seleccionar fecha', 'Sélectionner une date', 'Datum wählen', 'Selecionar data', 'Chọn ngày', 'เลือกวันที่', 'Pilih Tanggal', 'اختيار التاريخ', true, NOW(), NOW()),
(md5('i18n_bk_time_select'),    'booking.time_select',      'booking', '시간 선택', 'Select Time', '時間を選択', '选择时间', '選擇時間', 'Seleccionar hora', 'Sélectionner une heure', 'Zeit wählen', 'Selecionar horário', 'Chọn giờ', 'เลือกเวลา', 'Pilih Waktu', 'اختيار الوقت', true, NOW(), NOW()),
(md5('i18n_bk_request_note'),   'booking.request_note',     'booking', '요청사항', 'Request Note', 'リクエストメモ', '备注', '備註', 'Nota de solicitud', 'Note de demande', 'Anmerkung', 'Observação', 'Ghi chú yêu cầu', 'หมายเหตุ', 'Catatan Permintaan', 'ملاحظات الطلب', true, NOW(), NOW()),
(md5('i18n_bk_summary'),        'booking.summary',          'booking', '예약 요약', 'Booking Summary', '予約概要', '预约摘要', '預約摘要', 'Resumen de reserva', 'Résumé de réservation', 'Buchungsübersicht', 'Resumo da reserva', 'Tóm tắt đặt lịch', 'สรุปการจอง', 'Ringkasan Pemesanan', 'ملخص الحجز', true, NOW(), NOW()),
(md5('i18n_bk_confirm_btn'),    'booking.confirm_btn',      'booking', '예약 신청하기', 'Book Now', '予約を申請する', '提交预约', '提交預約', 'Reservar ahora', 'Réserver maintenant', 'Jetzt buchen', 'Reservar agora', 'Đặt lịch ngay', 'จองเลย', 'Pesan Sekarang', 'احجز الآن', true, NOW(), NOW()),
(md5('i18n_bk_success_toast'),  'booking.success_toast',    'booking', '예약 신청이 완료되었습니다', 'Booking request submitted', '予約申請が完了しました', '预约申请已提交', '預約申請已提交', 'Solicitud de reserva enviada', 'Demande de réservation envoyée', 'Buchungsanfrage gesendet', 'Solicitação enviada', 'Đã gửi yêu cầu đặt lịch', 'ส่งคำขอจองแล้ว', 'Permintaan pemesanan terkirim', 'تم إرسال طلب الحجز', true, NOW(), NOW()),
(md5('i18n_bk_service_type'),   'booking.service_type',     'booking', '서비스 유형', 'Service Type', 'サービス種類', '服务类型', '服務類型', 'Tipo de servicio', 'Type de service', 'Serviceart', 'Tipo de serviço', 'Loại dịch vụ', 'ประเภทบริการ', 'Jenis Layanan', 'نوع الخدمة', true, NOW(), NOW()),
(md5('i18n_bk_duration'),       'booking.duration',         'booking', '소요시간', 'Duration', '所要時間', '所需时间', '所需時間', 'Duración', 'Durée', 'Dauer', 'Duração', 'Thời gian', 'ระยะเวลา', 'Durasi', 'المدة', true, NOW(), NOW()),
(md5('i18n_bk_price'),          'booking.price',            'booking', '금액', 'Price', '料金', '价格', '價格', 'Precio', 'Prix', 'Preis', 'Preço', 'Giá', 'ราคา', 'Harga', 'السعر', true, NOW(), NOW()),
(md5('i18n_bk_minutes'),        'booking.minutes',          'booking', '분', 'min', '分', '分钟', '分鐘', 'min', 'min', 'Min', 'min', 'phút', 'นาที', 'menit', 'دقيقة', true, NOW(), NOW()),

-- ── Supplier: Appointment management ───────────────────────────────────────
(md5('i18n_sa_new_request'),    'supplier.appointment.new_request',    'supplier', '새 예약 요청', 'New Appointment Request', '新規予約リクエスト', '新预约请求', '新預約請求', 'Nueva solicitud de cita', 'Nouvelle demande de rendez-vous', 'Neue Terminanfrage', 'Nova solicitação de consulta', 'Yêu cầu đặt lịch mới', 'คำขอนัดหมายใหม่', 'Permintaan Janji Baru', 'طلب موعد جديد', true, NOW(), NOW()),
(md5('i18n_sa_confirm_btn'),    'supplier.appointment.confirm_btn',    'supplier', '예약 수락', 'Accept', '予約を承認', '接受预约', '接受預約', 'Aceptar', 'Accepter', 'Annehmen', 'Aceitar', 'Chấp nhận', 'ยอมรับ', 'Terima', 'قبول', true, NOW(), NOW()),
(md5('i18n_sa_reject_btn'),     'supplier.appointment.reject_btn',     'supplier', '예약 거절', 'Reject', '予約を拒否', '拒绝预约', '拒絕預約', 'Rechazar', 'Refuser', 'Ablehnen', 'Recusar', 'Từ chối', 'ปฏิเสธ', 'Tolak', 'رفض', true, NOW(), NOW()),
(md5('i18n_sa_reject_reason'),  'supplier.appointment.reject_reason',  'supplier', '거절 사유', 'Rejection Reason', '拒否理由', '拒绝理由', '拒絕理由', 'Motivo de rechazo', 'Motif de refus', 'Ablehnungsgrund', 'Motivo da recusa', 'Lý do từ chối', 'เหตุผลในการปฏิเสธ', 'Alasan Penolakan', 'سبب الرفض', true, NOW(), NOW()),
(md5('i18n_sa_confirmed'),      'supplier.appointment.confirmed',      'supplier', '확정된 예약', 'Confirmed Appointments', '確定済み予約', '已确认预约', '已確認預約', 'Citas confirmadas', 'Rendez-vous confirmés', 'Bestätigte Termine', 'Consultas confirmadas', 'Lịch hẹn đã xác nhận', 'นัดหมายที่ยืนยันแล้ว', 'Janji Terkonfirmasi', 'المواعيد المؤكدة', true, NOW(), NOW()),
(md5('i18n_sa_complete_btn'),   'supplier.appointment.complete_btn',   'supplier', '완료 처리', 'Complete', '完了処理', '完成处理', '完成處理', 'Completar', 'Terminer', 'Abschließen', 'Concluir', 'Hoàn thành', 'เสร็จสิ้น', 'Selesai', 'إكمال', true, NOW(), NOW()),
(md5('i18n_sa_pending'),        'supplier.appointment.status.pending', 'supplier', '대기중', 'Pending', '待機中', '待处理', '待處理', 'Pendiente', 'En attente', 'Ausstehend', 'Pendente', 'Đang chờ', 'รอดำเนินการ', 'Menunggu', 'قيد الانتظار', true, NOW(), NOW()),
(md5('i18n_sa_st_confirmed'),   'supplier.appointment.status.confirmed', 'supplier', '확정', 'Confirmed', '確定', '已确认', '已確認', 'Confirmada', 'Confirmé', 'Bestätigt', 'Confirmada', 'Đã xác nhận', 'ยืนยันแล้ว', 'Dikonfirmasi', 'مؤكد', true, NOW(), NOW()),
(md5('i18n_sa_st_rejected'),    'supplier.appointment.status.rejected', 'supplier', '거절됨', 'Rejected', '拒否済み', '已拒绝', '已拒絕', 'Rechazada', 'Refusé', 'Abgelehnt', 'Recusada', 'Đã từ chối', 'ถูกปฏิเสธ', 'Ditolak', 'مرفوض', true, NOW(), NOW()),
(md5('i18n_sa_st_completed'),   'supplier.appointment.status.completed', 'supplier', '완료', 'Completed', '完了', '已完成', '已完成', 'Completada', 'Terminé', 'Abgeschlossen', 'Concluída', 'Hoàn thành', 'เสร็จสิ้น', 'Selesai', 'مكتمل', true, NOW(), NOW()),

-- ── Grooming: Supplier completion modal ────────────────────────────────────
(md5('i18n_gc_title'),          'grooming.complete.title',      'grooming', '미용 완료 보고', 'Grooming Completion Report', 'グルーミング完了報告', '美容完成报告', '美容完成報告', 'Informe de acicalamiento', 'Rapport de toilettage', 'Pflegebericht', 'Relatório de tosa', 'Báo cáo hoàn thành', 'รายงานการตัดแต่ง', 'Laporan Grooming', 'تقرير العناية', true, NOW(), NOW()),
(md5('i18n_gc_photos'),         'grooming.complete.photos',     'grooming', '완료 사진', 'Completion Photos', '完了写真', '完成照片', '完成照片', 'Fotos completadas', 'Photos terminées', 'Fertige Fotos', 'Fotos concluídas', 'Ảnh hoàn thành', 'รูปที่เสร็จแล้ว', 'Foto Selesai', 'صور مكتملة', true, NOW(), NOW()),
(md5('i18n_gc_main_photo'),     'grooming.complete.main_photo', 'grooming', '대표 사진', 'Main Photo', 'メイン写真', '主照片', '主照片', 'Foto principal', 'Photo principale', 'Hauptfoto', 'Foto principal', 'Ảnh chính', 'รูปหลัก', 'Foto Utama', 'الصورة الرئيسية', true, NOW(), NOW()),
(md5('i18n_gc_style'),          'grooming.complete.style',      'grooming', '미용 스타일 정보', 'Grooming Style Info', 'スタイル情報', '造型信息', '造型資訊', 'Info de estilo', 'Info de style', 'Stil-Info', 'Info de estilo', 'Thông tin kiểu', 'ข้อมูลสไตล์', 'Info Gaya', 'معلومات الأسلوب', true, NOW(), NOW()),
(md5('i18n_gc_type'),           'grooming.complete.type',       'grooming', '미용 종류', 'Grooming Type', 'グルーミング種類', '美容类型', '美容類型', 'Tipo de acicalamiento', 'Type de toilettage', 'Pflegeart', 'Tipo de tosa', 'Loại chải chuốt', 'ประเภทการตัดแต่ง', 'Jenis Grooming', 'نوع العناية', true, NOW(), NOW()),
(md5('i18n_gc_cut'),            'grooming.complete.cut',        'grooming', '커트 스타일', 'Cut Style', 'カットスタイル', '剪裁风格', '剪裁風格', 'Estilo de corte', 'Style de coupe', 'Schnittstil', 'Estilo de corte', 'Kiểu cắt', 'สไตล์การตัด', 'Gaya Potongan', 'أسلوب القص', true, NOW(), NOW()),
(md5('i18n_gc_duration'),       'grooming.complete.duration',   'grooming', '소요시간', 'Duration', '所要時間', '所需时间', '所需時間', 'Duración', 'Durée', 'Dauer', 'Duração', 'Thời gian', 'ระยะเวลา', 'Durasi', 'المدة', true, NOW(), NOW()),
(md5('i18n_gc_products'),       'grooming.complete.products',   'grooming', '사용 제품', 'Products Used', '使用製品', '使用产品', '使用產品', 'Productos usados', 'Produits utilisés', 'Verwendete Produkte', 'Produtos usados', 'Sản phẩm sử dụng', 'ผลิตภัณฑ์ที่ใช้', 'Produk Digunakan', 'المنتجات المستخدمة', true, NOW(), NOW()),
(md5('i18n_gc_comment'),        'grooming.complete.comment',    'grooming', '보호자에게 코멘트', 'Comment to Guardian', '飼い主へのコメント', '给主人的评语', '給主人的評語', 'Comentario al guardián', 'Commentaire au gardien', 'Kommentar an Besitzer', 'Comentário ao guardião', 'Bình luận cho chủ', 'ความเห็นถึงเจ้าของ', 'Komentar untuk Pemilik', 'تعليق للمالك', true, NOW(), NOW()),
(md5('i18n_gc_send_btn'),       'grooming.complete.send_btn',   'grooming', '보호자에게 전송', 'Send to Guardian', '飼い主に送信', '发送给主人', '傳送給主人', 'Enviar al guardián', 'Envoyer au gardien', 'An Besitzer senden', 'Enviar ao guardião', 'Gửi cho chủ', 'ส่งถึงเจ้าของ', 'Kirim ke Pemilik', 'إرسال للمالك', true, NOW(), NOW()),

-- ── Grooming: Guardian approval modal ──────────────────────────────────────
(md5('i18n_gg_noti_title'),     'grooming.guardian.noti_title',      'grooming', '미용이 완료되었습니다', 'Grooming is complete', 'グルーミングが完了しました', '美容已完成', '美容已完成', 'El acicalamiento está listo', 'Le toilettage est terminé', 'Die Pflege ist abgeschlossen', 'A tosa foi concluída', 'Chải chuốt hoàn tất', 'การตัดแต่งเสร็จแล้ว', 'Grooming selesai', 'اكتملت العناية', true, NOW(), NOW()),
(md5('i18n_gg_choice_feed'),    'grooming.guardian.choice_feed',     'grooming', '피드에 공유', 'Share to Feed', 'フィードに共有', '分享到动态', '分享到動態', 'Compartir en feed', 'Partager dans le fil', 'Im Feed teilen', 'Compartilhar no feed', 'Chia sẻ lên bảng tin', 'แชร์ไปยังฟีด', 'Bagikan ke Feed', 'مشاركة في الخلاصة', true, NOW(), NOW()),
(md5('i18n_gg_choice_approve'), 'grooming.guardian.choice_approve',  'grooming', '승인만', 'Approve Only', '承認のみ', '仅批准', '僅批准', 'Solo aprobar', 'Approuver seulement', 'Nur genehmigen', 'Apenas aprovar', 'Chỉ phê duyệt', 'อนุมัติเท่านั้น', 'Hanya Setujui', 'موافقة فقط', true, NOW(), NOW()),
(md5('i18n_gg_choice_both'),    'grooming.guardian.choice_both',     'grooming', '승인 + 피드 공유', 'Approve & Share', '承認＆共有', '批准并分享', '批准並分享', 'Aprobar y compartir', 'Approuver et partager', 'Genehmigen & teilen', 'Aprovar e compartilhar', 'Phê duyệt & chia sẻ', 'อนุมัติและแชร์', 'Setujui & Bagikan', 'موافقة ومشاركة', true, NOW(), NOW()),
(md5('i18n_gg_confirm_btn'),    'grooming.guardian.confirm_btn',     'grooming', '선택 완료', 'Confirm Choice', '選択を確定', '确认选择', '確認選擇', 'Confirmar elección', 'Confirmer le choix', 'Auswahl bestätigen', 'Confirmar escolha', 'Xác nhận lựa chọn', 'ยืนยันตัวเลือก', 'Konfirmasi Pilihan', 'تأكيد الاختيار', true, NOW(), NOW()),

-- ── Grooming: Feed card display ────────────────────────────────────────────
(md5('i18n_gf_badge'),          'grooming.feed.badge',              'grooming', '미용완료', 'Grooming Done', 'グルーミング完了', '美容完成', '美容完成', 'Acicalamiento listo', 'Toilettage terminé', 'Pflege fertig', 'Tosa concluída', 'Đã hoàn thành', 'ตัดแต่งเสร็จ', 'Grooming Selesai', 'عناية مكتملة', true, NOW(), NOW()),
(md5('i18n_gf_view_store'),     'grooming.feed.view_store',         'grooming', '매장 보기', 'View Store', 'ストアを見る', '查看店铺', '查看店鋪', 'Ver tienda', 'Voir le magasin', 'Shop ansehen', 'Ver loja', 'Xem cửa hàng', 'ดูร้านค้า', 'Lihat Toko', 'عرض المتجر', true, NOW(), NOW()),
(md5('i18n_gf_detail_type'),    'grooming.feed.detail.type',        'grooming', '미용 종류', 'Grooming Type', 'グルーミング種類', '美容类型', '美容類型', 'Tipo', 'Type', 'Art', 'Tipo', 'Loại', 'ประเภท', 'Jenis', 'النوع', true, NOW(), NOW()),
(md5('i18n_gf_detail_cut'),     'grooming.feed.detail.cut',         'grooming', '커트 스타일', 'Cut Style', 'カットスタイル', '剪裁风格', '剪裁風格', 'Estilo de corte', 'Style de coupe', 'Schnittstil', 'Estilo de corte', 'Kiểu cắt', 'สไตล์การตัด', 'Gaya Potongan', 'أسلوب القص', true, NOW(), NOW()),
(md5('i18n_gf_detail_duration'),'grooming.feed.detail.duration',    'grooming', '소요시간', 'Duration', '所要時間', '所需时间', '所需時間', 'Duración', 'Durée', 'Dauer', 'Duração', 'Thời gian', 'ระยะเวลา', 'Durasi', 'المدة', true, NOW(), NOW()),
(md5('i18n_gf_detail_products'),'grooming.feed.detail.products',    'grooming', '사용 제품', 'Products', '使用製品', '使用产品', '使用產品', 'Productos', 'Produits', 'Produkte', 'Produtos', 'Sản phẩm', 'ผลิตภัณฑ์', 'Produk', 'المنتجات', true, NOW(), NOW()),
(md5('i18n_gf_detail_comment'), 'grooming.feed.detail.comment',     'grooming', '업종 코멘트', 'Stylist Comment', 'スタイリストコメント', '造型师评语', '造型師評語', 'Comentario del estilista', 'Commentaire du styliste', 'Stylist-Kommentar', 'Comentário do estilista', 'Nhận xét của thợ', 'ความเห็นช่าง', 'Komentar Stylist', 'تعليق المصمم', true, NOW(), NOW()),

-- ── Grooming service types (master-like options) ───────────────────────────
(md5('i18n_gs_full'),           'grooming.service.full',        'grooming', '전체미용', 'Full Grooming', 'フルグルーミング', '全身美容', '全身美容', 'Acicalamiento completo', 'Toilettage complet', 'Vollpflege', 'Tosa completa', 'Tỉa lông toàn bộ', 'ตัดแต่งขนทั้งตัว', 'Grooming Penuh', 'عناية كاملة', true, NOW(), NOW()),
(md5('i18n_gs_partial'),        'grooming.service.partial',     'grooming', '부분미용', 'Partial Grooming', '部分グルーミング', '局部美容', '局部美容', 'Acicalamiento parcial', 'Toilettage partiel', 'Teilpflege', 'Tosa parcial', 'Tỉa lông cục bộ', 'ตัดแต่งขนบางส่วน', 'Grooming Parsial', 'عناية جزئية', true, NOW(), NOW()),
(md5('i18n_gs_bath_dry'),       'grooming.service.bath_dry',    'grooming', '목욕+드라이', 'Bath & Dry', 'バス＆ドライ', '洗澡+吹干', '洗澡+吹乾', 'Baño y secado', 'Bain et séchage', 'Bad & Trocknen', 'Banho e secagem', 'Tắm & sấy', 'อาบน้ำ & เป่าแห้ง', 'Mandi & Keringkan', 'حمام وتجفيف', true, NOW(), NOW()),
(md5('i18n_gs_spa'),            'grooming.service.spa',         'grooming', '스파', 'Spa', 'スパ', '水疗', '水療', 'Spa', 'Spa', 'Spa', 'Spa', 'Spa', 'สปา', 'Spa', 'سبا', true, NOW(), NOW()),

-- ── Cut styles ─────────────────────────────────────────────────────────────
(md5('i18n_cs_teddy'),          'grooming.cut.teddy_bear',      'grooming', '테디베어컷', 'Teddy Bear Cut', 'テディベアカット', '泰迪熊造型', '泰迪熊造型', 'Corte osito', 'Coupe nounours', 'Teddybär-Schnitt', 'Corte ursinho', 'Kiểu gấu bông', 'ตัดทรงหมีเท็ดดี้', 'Potongan Teddy Bear', 'قصة الدب', true, NOW(), NOW()),
(md5('i18n_cs_bear'),           'grooming.cut.bear',            'grooming', '곰돌이컷', 'Bear Cut', 'ベアカット', '小熊造型', '小熊造型', 'Corte oso', 'Coupe ourson', 'Bärchen-Schnitt', 'Corte urso', 'Kiểu gấu', 'ตัดทรงหมี', 'Potongan Beruang', 'قصة الدبدوب', true, NOW(), NOW()),
(md5('i18n_cs_sporty'),         'grooming.cut.sporty',          'grooming', '스포츠컷', 'Sporty Cut', 'スポーツカット', '运动造型', '運動造型', 'Corte deportivo', 'Coupe sport', 'Sport-Schnitt', 'Corte esportivo', 'Kiểu thể thao', 'ตัดทรงสปอร์ต', 'Potongan Sporty', 'قصة رياضية', true, NOW(), NOW()),
(md5('i18n_cs_natural'),        'grooming.cut.natural',         'grooming', '자연컷', 'Natural Cut', 'ナチュラルカット', '自然造型', '自然造型', 'Corte natural', 'Coupe naturelle', 'Natürlicher Schnitt', 'Corte natural', 'Kiểu tự nhiên', 'ตัดทรงธรรมชาติ', 'Potongan Natural', 'قصة طبيعية', true, NOW(), NOW()),

-- ── Notification messages ──────────────────────────────────────────────────
(md5('i18n_noti_apt_request'),  'notification.appointment_request',   'notification', '새 예약 요청이 있습니다', 'New appointment request', '新しい予約リクエストがあります', '有新的预约请求', '有新的預約請求', 'Nueva solicitud de cita', 'Nouvelle demande de rendez-vous', 'Neue Terminanfrage', 'Nova solicitação de consulta', 'Có yêu cầu đặt lịch mới', 'มีคำขอนัดหมายใหม่', 'Ada permintaan janji baru', 'طلب موعد جديد', true, NOW(), NOW()),
(md5('i18n_noti_apt_confirmed'),'notification.appointment_confirmed', 'notification', '예약이 수락되었습니다', 'Appointment confirmed', '予約が承認されました', '预约已确认', '預約已確認', 'Cita confirmada', 'Rendez-vous confirmé', 'Termin bestätigt', 'Consulta confirmada', 'Đã xác nhận lịch hẹn', 'นัดหมายได้รับการยืนยัน', 'Janji dikonfirmasi', 'تم تأكيد الموعد', true, NOW(), NOW()),
(md5('i18n_noti_apt_rejected'), 'notification.appointment_rejected',  'notification', '예약이 거절되었습니다', 'Appointment rejected', '予約が拒否されました', '预约被拒绝', '預約被拒絕', 'Cita rechazada', 'Rendez-vous refusé', 'Termin abgelehnt', 'Consulta recusada', 'Lịch hẹn bị từ chối', 'นัดหมายถูกปฏิเสธ', 'Janji ditolak', 'تم رفض الموعد', true, NOW(), NOW()),
(md5('i18n_noti_groom_done'),   'notification.grooming_complete',     'notification', '미용이 완료되었습니다', 'Grooming is complete', 'グルーミングが完了しました', '美容已完成', '美容已完成', 'Acicalamiento completado', 'Toilettage terminé', 'Pflege abgeschlossen', 'Tosa concluída', 'Đã hoàn thành chải chuốt', 'การตัดแต่งเสร็จแล้ว', 'Grooming selesai', 'اكتملت العناية', true, NOW(), NOW())

ON CONFLICT (id) DO UPDATE SET
  ko = EXCLUDED.ko, en = EXCLUDED.en, ja = EXCLUDED.ja,
  zh_cn = EXCLUDED.zh_cn, zh_tw = EXCLUDED.zh_tw,
  es = EXCLUDED.es, fr = EXCLUDED.fr, de = EXCLUDED.de,
  pt = EXCLUDED.pt, vi = EXCLUDED.vi, th = EXCLUDED.th,
  id_lang = EXCLUDED.id_lang, ar = EXCLUDED.ar,
  is_active = EXCLUDED.is_active, updated_at = NOW();
